// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/facade. DO NOT EDIT.

// Package rulestest re-exports [go.dokimi.dev/eidos/core/rules/rulestest]:
// one alias, constant or wrapper per exported symbol, so plugin
// code speaks the facade's paths while the kernel package stays
// the single home of every definition.
//
// # Dependency position
//
// sdk/rulestest imports core/rules/rulestest, sdk/meta,
// sdk/plugin, sdk/rules, go.dokimi.dev/assert and the Go stdlib.
package rulestest

import (
	"io/fs"
	"testing"

	"go.dokimi.dev/assert"

	core "go.dokimi.dev/eidos/core/rules/rulestest"
	"go.dokimi.dev/eidos/sdk/meta"
	"go.dokimi.dev/eidos/sdk/plugin"
	"go.dokimi.dev/eidos/sdk/rules"
)

// Budget is the ceiling a benchmark checks a language against.
type Budget = core.Budget

// BenchRules drives the four hot projections over the setup's
// graph, one iteration projecting every callable, every type's
// members, every reference's shape and every field's samples, and
// fails when the allocations per iteration exceed the budget. The
// fixture builds once outside the loop, and every iteration binds a
// fresh view.
func BenchRules(b *testing.B, setup Setup, budget Budget) {
	core.BenchRules(b, setup, budget)
}

// Loaded loads a source tree through one frontend into a fixture:
// the sealed graph, and a fact store holding the load's
// classification stamps under the kernel's keys and every key the
// registrations add. A load that reports an Error fails the test,
// because a tree the language refuses proves nothing about its
// rules.
func Loaded(tb assert.TB, f plugin.Frontend, sources fs.FS, keys ...func(*meta.Registry) error) *Fixture {
	return core.Loaded(tb, f, sources, keys...)
}

// Scripted returns the rules of the scripted language: a member
// walk over embeds under promotion, every parameter an input, an
// error model of none, three builtins, resolution in the subject's
// package, and samples for the builtins alone. It is the language
// the kernel proves its walks on.
func Scripted() rules.SourceRules {
	return core.Scripted()
}

// Fixture is what a language brings to the suite: a sealed graph
// its frontend loaded, the facts the run stamped on it, and the
// kernel's keys those facts registered under.
type Fixture = core.Fixture

// Setup builds the rules under test and their fixture, fresh per
// check.
type Setup = core.Setup

// RunRulesSuite checks a language's rules against the projection
// contract: equal values from two bounds over one view, a total fold
// and mapping, refusals and gaps with reasons, distinct samples,
// witnesses a backend can spell and substitute, sample reads
// recorded on the view the language is handed, and the serial
// values under concurrency.
func RunRulesSuite(t *testing.T, setup Setup) {
	core.RunRulesSuite(t, setup)
}

// AssertDeterministic checks that two bounds over one view return
// equal values from every projection. Each bound memoises its own
// fold, so the second pass derives every value again.
func AssertDeterministic(tb assert.TB, setup Setup) {
	core.AssertDeterministic(tb, setup)
}

// AssertTotal checks that the fold returns a shape for every
// reference and that the mapping reports false for every
// non-callable kind, without panicking.
func AssertTotal(tb assert.TB, setup Setup) {
	core.AssertTotal(tb, setup)
}

// AssertRefusesWithReason checks that every refused sample has a
// refusal other than none and that every gap names a reason.
func AssertRefusesWithReason(tb assert.TB, setup Setup) {
	core.AssertRefusesWithReason(tb, setup)
}

// AssertDistinctSamples checks that the two halves of every derived
// pair differ, compared field by field at every depth.
func AssertDistinctSamples(tb assert.TB, setup Setup) {
	core.AssertDistinctSamples(tb, setup)
}

// AssertWitnesses checks a language's generics capability over every
// generic declaration in the fixture. Derive returns a reference
// with a spelling wherever it reports a witness, because a backend
// writes the instantiation from the spelling. Substitute rewrites
// every reference that targets a parameter into the parameter's
// witness and leaves the reference it is handed unchanged. A
// language without the capability, and a fixture declaring no type
// parameter, have nothing to check. A fixture that declares type
// parameters references one whose witnesses derive, or the check
// fails as proving nothing.
func AssertWitnesses(tb assert.TB, setup Setup) {
	core.AssertWitnesses(tb, setup)
}

// AssertRecorded checks that a language's samples read through the
// view they are handed. A sample of a reference that targets a
// declaration reads the declaration, so the read set the view
// records into contains the target, and a change to the declaration
// re-runs every generator that wrote the sample. The check calls the
// language's own SamplesOf with a fresh view per field, so no read
// the kernel's walks make counts toward it.
func AssertRecorded(tb assert.TB, setup Setup) {
	core.AssertRecorded(tb, setup)
}

// AssertConcurrent checks that the projections, run from parallel
// goroutines each over its own view, return the serial values.
func AssertConcurrent(tb assert.TB, setup Setup) {
	core.AssertConcurrent(tb, setup)
}
