// Copyright Dokimasia B.V. 2026
// SPDX-License-Identifier: Apache-2.0

package toolchain_test

import (
	"errors"
	"testing"

	"go.dokimi.dev/assert"
	"go.dokimi.dev/assert/files"

	"go.dokimi.dev/eidos/core/internal/coretest"
	"go.dokimi.dev/eidos/core/toolchain"
)

// absentToolchain is the reason the fixture adapter gives for a
// toolchain the machine lacks.
const absentToolchain = "scriptedc is not on PATH"

// The layout contract and the CI rule are what let a satellite run
// the same suite on a machine with the toolchain and without it.
func TestGate(t *testing.T) {
	t.Parallel()

	t.Run("Prepare", func(t *testing.T) {
		t.Parallel()

		t.Run("hands the fixture to the adapter and cleans up after", func(t *testing.T) {
			t.Parallel()

			var (
				dir string
				saw map[string]string
			)
			got, done := toolchain.Prepare(t, scripted{laidOut: &dir, sawFiles: &saw}, output())
			assert.Equal(t, got, dir, "the assertion receives the directory the adapter wrote")
			files.IsDir(t, got, "which is on disk while the check runs")
			assert.Equal(t, saw, map[string]string{"gen/row.s": "row\n"}, "and the adapter saw the generated bytes")
			done()
			files.Absent(t, got, "the cleanup removes the scratch project")
		})

		t.Run("records a layout the language refused", func(t *testing.T) {
			t.Parallel()

			refusal := errors.New("no room")
			var dir string
			got := assert.Rejects(t, "a refused layout fails the check", func(tb assert.TB) {
				var done func()
				dir, done = toolchain.Prepare(tb, scripted{layoutErr: refusal}, output())
				done()
			})
			assert.Equal(t, dir, "", "nothing was laid out")
			assert.Equal(t, coretest.Contracts(got),
				[]string{"scripted: the generated output lays out for the toolchain"}, "the failure names the step")
			reason, stated := got[0].Got()
			assert.True(t, stated, "the record states the error")
			assert.Equal(t, reason, any(refusal), "which is the language's reason")
		})

		t.Run("records no adapter at all", func(t *testing.T) {
			t.Parallel()

			var dir string
			got := assert.Rejects(t, "a missing adapter fails the check", func(tb assert.TB) {
				var done func()
				dir, done = toolchain.Prepare(tb, nil, output())
				done()
			})
			assert.Equal(t, dir, "", "nothing was laid out")
			assert.Equal(t, coretest.Contracts(got), []string{"toolchain: an adapter lays the fixture out"},
				"a fixture with nothing to lay it out proves nothing")
		})
	})
}

// The CI rule reads a process-wide variable, so it runs on its own
// rather than beside the parallel cases above.
func TestRequiredInCI(t *testing.T) {
	t.Run("reads the one variable every runner sets", func(t *testing.T) {
		t.Setenv("CI", "")
		assert.False(t, toolchain.RequiredInCI(), "unset locally, so a missing toolchain skips")
		t.Setenv("CI", "true")
		assert.True(t, toolchain.RequiredInCI(), "set in CI, so a missing toolchain fails")
	})

	t.Run("reads a false boolean as local", func(t *testing.T) {
		for _, off := range []string{"false", "0", "FALSE"} {
			t.Setenv("CI", off)
			assert.False(t, toolchain.RequiredInCI(), "CI="+off+" runs as local")
		}
		t.Setenv("CI", "woodpecker")
		assert.True(t, toolchain.RequiredInCI(), "a runner naming itself runs as CI")
	})

	t.Run("skips a missing toolchain locally, naming the reason", func(t *testing.T) {
		t.Setenv("CI", "")
		s := &seat{Recorder: assert.NewRecorder()}
		assert.False(t, toolchain.Require(s, scripted{absent: absentToolchain}), "nothing can run without it")
		assert.Contains(t, s.skipped, absentToolchain, "the skip carries the adapter's reason")
		assert.Contains(t, s.skipped, "required in CI", "and says where it will not be skipped")
		assert.Empty(t, s.Failures(), "a missing toolchain is not a local failure")
	})

	t.Run("records a missing toolchain in CI", func(t *testing.T) {
		t.Setenv("CI", "true")
		s := &seat{Recorder: assert.NewRecorder()}
		assert.False(t, toolchain.Require(s, scripted{absent: absentToolchain}), "nothing can run without it")
		assert.Equal(t, coretest.Contracts(s.Failures()),
			[]string{"scripted: the toolchain CI requires is present: " + absentToolchain},
			"so a regression cannot hide behind a missing compiler")
		assert.Equal(t, s.skipped, "", "and nothing is skipped")
	})
}
