// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

package toolchain_test

import (
	"errors"
	"testing"

	"go.dokimi.dev/assert"

	"go.dokimi.dev/eidos/core/toolchain"
)

// The layout contract and the CI rule are what let a satellite run
// the same suite on a machine with the toolchain and without it.
func TestGate(t *testing.T) {
	t.Parallel()

	t.Run("Prepare", func(t *testing.T) {
		t.Parallel()

		t.Run("hands the fixture to the adapter and cleans up after", func(t *testing.T) {
			t.Parallel()

			var dir string
			var saw map[string]string
			var r recorder
			got, done := toolchain.Prepare(&r, scripted{laidOut: &dir, sawFiles: &saw}, output())
			assert.False(t, r.failed(), "the layout succeeds")
			assert.Equal(t, got, dir, "the assertion receives the directory the adapter wrote")
			assert.True(t, exists(got), "which is on disk while the check runs")
			assert.Equal(t, saw["gen/row.s"], "row\n", "and the adapter saw the generated bytes")
			done()
			assert.False(t, exists(got), "the cleanup removes the scratch project")
		})

		t.Run("reports a layout the language refused", func(t *testing.T) {
			t.Parallel()

			var r recorder
			dir, done := toolchain.Prepare(&r, scripted{layoutErr: errors.New("no room")}, output())
			done()
			assert.Equal(t, dir, "", "nothing was laid out")
			assert.True(t, r.says("laying the generated output out"), "the refusal names the step")
			assert.True(t, r.says("no room"), "and carries the language's reason")
		})

		t.Run("refuses no adapter at all", func(t *testing.T) {
			t.Parallel()

			var r recorder
			dir, done := toolchain.Prepare(&r, nil, output())
			done()
			assert.Equal(t, dir, "", "nothing was laid out")
			assert.True(t, r.says("no adapter"), "a fixture with nothing to lay it out proves nothing")
		})
	})
}

// The CI rule reads a process-wide variable, so it runs on its own
// rather than beside the parallel cases above.
func TestRequiredInCI(t *testing.T) {
	t.Run("reads the one variable every runner sets", func(t *testing.T) {
		t.Setenv("CI", "")
		assert.False(t, toolchain.RequiredInCI(), "unset locally, so a missing toolchain skips")
		t.Setenv("CI", "true")
		assert.True(t, toolchain.RequiredInCI(), "set in CI, so a missing toolchain fails")
	})

	t.Run("reads a false boolean as local", func(t *testing.T) {
		for _, off := range []string{"false", "0", "FALSE"} {
			t.Setenv("CI", off)
			assert.False(t, toolchain.RequiredInCI(), "CI="+off+" runs as local")
		}
		t.Setenv("CI", "woodpecker")
		assert.True(t, toolchain.RequiredInCI(), "a runner naming itself runs as CI")
	})

	t.Run("skips a missing toolchain locally, naming the reason", func(t *testing.T) {
		t.Setenv("CI", "")
		var r recorder
		assert.False(t, toolchain.Require(&r, scripted{absent: "scriptedc is not on PATH"}),
			"nothing can run without it")
		assert.Contains(t, r.skipped, "scriptedc is not on PATH", "the skip carries the adapter's reason")
		assert.Contains(t, r.skipped, "required in CI", "and says where it will not be skipped")
		assert.False(t, r.failed(), "a missing toolchain is not a local failure")
	})

	t.Run("fails a missing toolchain in CI", func(t *testing.T) {
		t.Setenv("CI", "true")
		var r recorder
		assert.False(t, toolchain.Require(&r, scripted{absent: "scriptedc is not on PATH"}),
			"nothing can run without it")
		assert.True(t, r.says("required in CI and is absent"),
			"so a regression cannot hide behind a missing compiler")
		assert.Equal(t, r.skipped, "", "and nothing is skipped")
	})
}
