// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/facade. DO NOT EDIT.

// Package node re-exports [go.dokimi.dev/eidos/core/node]:
// one alias, constant or wrapper per exported symbol, so plugin
// code speaks the facade's paths while the kernel package stays
// the single home of every definition.
//
// # Dependency position
//
// sdk/node imports core/node, sdk/symbol and the Go stdlib.
package node

import (
	"iter"

	core "go.dokimi.dev/eidos/core/node"
	"go.dokimi.dev/eidos/sdk/symbol"
)

// ModelFingerprint identifies the node model's shape: a sha256 over
// every kind and node-side field the schema declares, hex-spelled.
//
// Every unit key folds it, because a schema change reshapes the
// graph the same source produces: a graph recorded under one shape
// must not be served under another. The hash reads the lowered
// schema rather than the rendered files, so a documentation edit
// does not change it.
const ModelFingerprint = core.ModelFingerprint

// Imports returns a package's imports: the union of its files'
// import statements, in file order and then statement order. The
// model carries no package-level import list, because the files
// record the scope as written and a second list would drift from
// them; this is the one derivation.
func Imports(p *Package) iter.Seq[*Import] {
	return core.Imports(p)
}

// Function is a callable declared outside any type: a Go or Rust
// free function, a Python module-level def, a TypeScript exported
// function.
//
// Async marks a result that arrives asynchronously in the
// language's own form: a TypeScript async function, a Rust async
// fn, a Python async def. Go leaves it false, because its
// concurrency is caller-side and invisible in signatures.
//
// Throws lists the failure types the declaration announces: Java
// checked exceptions, Swift typed throws. A language without
// declared throws leaves it empty, and the error model stays the
// projection's neutral question.
//
// The node model carries the signature and never a body, because
// parsed bodies are out of scope entirely. The emit model carries
// what a generated body holds in its Body field: the standard
// slots, and one content form.
//
// This is the node spelling of the kind.
type Function = core.Function

// Method is a callable attached to a type.
//
// Receiver holds the explicit receiver where the language writes
// one, as Go and Rust do, and stays nil where the receiver is
// implicit. Level says whether the method belongs to instances or
// to the type itself, which covers JVM statics and Kotlin
// companions.
//
// Receives carries the type a method attaches to when it is
// declared outside that type's own declaration: a Kotlin extension
// function, a Swift extension member, a C# extension method, a Rust
// impl for a type from another crate. Host stays the declaration
// that contains the method, so the two answer different questions
// and neither has to lie. A method declared inside its type leaves
// Receives nil.
//
// Abstract marks a member with no body that a subtype must supply.
// Final forbids overriding. Override marks a member that replaces a
// supertype's, which Kotlin, C#, Swift and TypeScript spell as a
// keyword the emitted code has to carry; Java spells it as an
// annotation instead, so a Java frontend leaves the field false.
//
// HasDefault marks an interface method that carries a body: a Java
// default method, a Kotlin interface method, a Rust default impl.
// It differs from Abstract's inverse, because a class method with a
// body is ordinary rather than a default.
//
// Async and Throws carry what [Function]'s carry: the
// asynchronous result in the language's own form, and the failure
// types the declaration announces.
//
// The node model carries the signature and never a body; the emit
// model carries what a generated body holds in its Body field.
//
// This is the node spelling of the kind.
type Method = core.Method

// Param is one parameter of a callable, or its receiver.
//
// Name is empty where the language allows an unnamed parameter, as
// Go and Java interfaces do. Label is the caller-facing name where
// a language gives a parameter two, which Swift and Objective-C do:
// in "func greet(person name: String)" the label is "person" and
// the name is "name".
//
// Default holds the source spelling of the default value,
// unevaluated, and is empty when the parameter has none. A
// generator that drops a default changes the callee's contract, so
// the spelling is carried with the parameter rather than living in
// metadata.
//
// Variadic distinguishes the positional and keyword forms, because
// Python, Ruby and PHP have both. It is legal on the trailing
// parameters only, and frontends enforce that rather than the
// model.
//
// A parameter is a subject: an authored value sits on it in a
// language whose comments reach it, and its identity is the host's
// chain, its name or its position, and the host's discriminator.
//
// This is the node spelling of the kind.
type Param = core.Param

// Return is one result of a callable.
//
// The list is a slice because Go returns several values. A language
// with one result fills one entry, and a language with none fills
// none. Name carries a Go named result and is empty elsewhere.
//
// A return is a subject the way a parameter is, named by its
// position where the language leaves it unnamed.
//
// This is the node spelling of the kind.
type Return = core.Return

// Package is a namespace holding declarations.
//
// Path holds the namespace as hierarchical segments, so Rust module
// nesting and TypeScript namespaces map into it the way Go import
// paths do. The original spelling stays in language metadata. Name
// is the declared name, which Go lets differ from the last path
// segment.
//
// Files is node-only: a generated package is a set of files the
// layout routes, never a parsed directory.
//
// This is the node spelling of the kind.
type Package = core.Package

// File is one source file and the declarations it holds.
//
// Imports and Exports record the file's module boundary as written,
// which is what the resolution step reads to turn a spelling into
// an identity: a name means what the file's imports say it means.
// Decls holds any kind, because a file admits whatever its language
// admits at top level.
//
// This is the node spelling of the kind.
type File = core.File

// Import is one import statement and everything it binds.
//
// One statement is one Import, however many names it binds. Path
// names the module. Alias is the module-level alias, which covers a
// Go renamed import, a Python "import numpy as np" and a TypeScript
// namespace import. Names holds the per-symbol bindings, so
// "import {a as b, c} from 'x'" carries two. Default holds the
// local name bound to the module's default export, which
// TypeScript has and most languages do not.
//
// Wildcard means the statement pulls every exported name into
// scope: a Java "import java.util.*", a Rust glob use, a Python
// star import. Resolution treats a wildcard scope differently from
// a named one, so it is a field rather than a spelling.
//
// Import is node-only. A generated file's imports are a side effect
// of spelling types, collected per file as the backend renders,
// never a declaration a generator writes.
//
// This is the node spelling of the kind.
type Import = core.Import

// Export is one re-export statement: a name this file publishes
// that it did not declare.
//
// A declaration's own export is its [symbol.Visibility], not an
// Export. This kind carries the statement forms that publish
// something else: a TypeScript "export { a } from './x'" or
// "export * from './x'", a Rust "pub use", a Python __all__ entry.
// Path names the source module and is empty when the file
// re-exports its own local names.
//
// The public surface of a package is its exported declarations plus
// these, which is why a binding generator has to read both.
//
// This is the node spelling of the kind.
type Export = core.Export

// Binding is one name bound by an [Import] or published by an
// [Export].
//
// Name is the name as the source module spells it. Alias is the
// local spelling when the statement renames it, so "a as b" carries
// Name "a" and Alias "b", and an unrenamed binding leaves Alias
// empty. It carries its own position, so a diagnostic about one
// unused name in a ten-name import points at that name.
//
// This is the node spelling of the kind.
type Binding = core.Binding

// Enum is a closed set of named values carrying no payload: a Java
// enum class, a TypeScript enum, a proto enum, a Go constant group.
//
// The split from [Sum] goes by payload rather than by syntax. A
// variant set where no variant carries fields is an Enum; one where
// any variant does is a Sum.
//
// Fields and Methods exist because a Java enum is a class: it
// declares instance state and behaviour alongside its variants.
// Most languages leave both empty.
//
// This is the node spelling of the kind.
type Enum = core.Enum

// EnumVariant is one member of an [Enum].
//
// Value holds the source spelling of the value expression verbatim,
// including an unevaluated form such as a Go iota arithmetic
// expression or a Java variant's constructor arguments. Evaluating
// it is the language's job, not the model's, and a variant whose
// language assigns values implicitly leaves it empty.
//
// This is the node spelling of the kind.
type EnumVariant = core.EnumVariant

// Sum is a closed set of named variants carrying payloads: a Rust
// data enum, a Kotlin or Java sealed class hierarchy, a proto
// oneof, a Swift associated-value enum.
//
// Sum is a declaration kind. The untagged union that TypeScript and
// Python spell with a bar is a type shape instead, and the two stay
// separate because conflating them is how a target language ends up
// guessing which one it is spelling.
//
// This is the node spelling of the kind.
type Sum = core.Sum

// SumVariant is one variant of a [Sum]: a name and a field list.
//
// A variant whose payload is positional, as a Rust tuple variant
// is, fills Fields with unnamed entries in declaration order.
//
// This is the node spelling of the kind.
type SumVariant = core.SumVariant

// Field is a data member of a type: a Go struct field, a Java or
// TypeScript property, a Rust struct field, a Sum variant's payload
// entry.
//
// Level distinguishes an instance field from a static or companion
// one. Mutability carries the Kotlin val against var distinction,
// TypeScript readonly and Java final, which a generator emitting a
// data class has to reproduce. A field declared without a name, as
// a positional Sum variant payload is, leaves Name empty and
// carries only its type.
//
// Tag holds the tag text in the source language's spelling with
// its enclosing delimiters stripped, unevaluated, the way
// [Constant.Value] holds an expression; the target's template
// supplies the delimiters its language writes. Only languages with
// per-field tags fill it.
//
// This is the node spelling of the kind.
type Field = core.Field

// Variable is a binding declared outside any type: a Go
// package-level var, a TypeScript exported let, a Python
// module-level assignment, a Kotlin top-level val.
//
// Mutability separates a Kotlin val from a var. A binding fixed at
// compile time is a [Constant] instead, which is what a Kotlin
// const val and a Go const are.
//
// Type is nil when the source states none and the language infers
// it. That is a declared limit rather than a failure: the
// declaration still projects, and the language's own metadata
// carries the inferred spelling for anyone who needs it.
//
// This is the node spelling of the kind.
type Variable = core.Variable

// Constant is a binding fixed at compile time: a Go const, a Java
// static final, a TypeScript const, a Kotlin const val, a Rust
// const.
//
// Type is nil for an untyped constant, which Go has and most
// languages do not. Value holds the source spelling of the value
// expression verbatim, unevaluated, the same contract
// [EnumVariant.Value] carries.
//
// This is the node spelling of the kind.
type Constant = core.Constant

// Struct is a type values can be made of: a Go struct, a Java,
// Kotlin, TypeScript or Python class, a Rust struct.
//
// Struct and [Interface] differ by whether a language can
// instantiate them, never by which members they may declare. Both
// carry fields and methods, and one source construct maps to one
// kind whatever its body holds. Abstract is what keeps that line
// intact for a Java or Kotlin abstract class: it holds state and
// constructors like a class, so it is a Struct, and the flag says
// no value of it can be made directly.
//
// Final says the language forbids subclassing. It is the first
// question a doubling generator asks, and it is not a rare case:
// Kotlin classes are final unless declared open.
//
// Three supertype fields stay separate because they answer
// different questions. Embeds is compositional promotion, which Go
// fills. Extends and Implements are nominal, which the JVM
// languages fill; Python fills Extends in method-resolution order.
// A language fills what it has.
//
// Types holds declarations nested inside this one, which Java,
// Kotlin, C#, TypeScript and Python all allow. Without it the walk
// never reaches an inner class and no generator can see one. Level
// says whether a nested type binds to an enclosing instance, which
// a Java inner class and a Kotlin inner class do, or stands at
// type level, which Java writes as static; a file-level type
// leaves it unstated.
//
// Sealed says the direct subtypes are enumerated, which Java and
// Kotlin declare; Permits carries the enumeration where the
// language states one beyond the file, as Java's permits clause
// does.
//
// This is the node spelling of the kind.
type Struct = core.Struct

// Interface is a shape values are checked against: a Go or Java
// interface, a TypeScript interface, a Rust trait, a Swift
// protocol.
//
// It carries Fields because interfaces in several languages are
// mostly properties, and a TypeScript interface body usually holds
// them. A plugin asking what contracts exist finds every interface
// by kind, never by filtering another kind on a metadata key.
//
// Interfaces have no Implements: an interface that names another
// interface is widening its own contract, which is Extends. They
// need no Abstract either, since nothing instantiates one.
//
// Types holds nested declarations. An [Alias] in there with a nil
// Target is an associated type, which is how a Rust trait's "type
// Item;" and a Swift associatedtype project: a name the
// implementation supplies, rather than a parameter the caller
// chooses.
//
// Sealed and Permits carry what [Struct]'s carry: the direct
// subtypes are enumerated, and the enumeration where the language
// states one.
//
// This is the node spelling of the kind.
type Interface = core.Interface

// Alias is a name for another type: a Go type alias or defined
// type, a TypeScript type alias, a Rust type alias.
//
// Target carries the aliased type as written, and is nil for an
// associated type declared inside an [Interface], where the
// implementation supplies it. An alias may be generic, so a
// language that parameterizes aliases fills TypeParams and the
// target references them.
//
// Defined marks a distinct type rather than a transparent alias:
// a Go defined type, which attaches methods and converts
// explicitly, against the alias form that is only another
// spelling. A language without the distinction leaves it false,
// and one whose aliases are transparent alone refuses it.
//
// This is the node spelling of the kind.
type Alias = core.Alias

// TypeRef is a type as a declaration mentions it.
//
// Spelling holds the source text verbatim. Target holds the
// canonical identity the spelling resolves to, and it stays zero
// until the resolution step runs, and permanently for builtins and
// types outside the workspace. That is legitimate degradation, so a
// consumer asks before relying on a target.
//
// Target is an identity rather than a pointer. A key can be stored,
// compared and carried across runs; a pointer cannot, and following
// one would make the walk cyclic.
//
// Args holds the type arguments of an instantiation, so
// Map[string, User] carries two. A reference carrying Args holds
// the bare name in Spelling, and a target writes the argument
// list in its own brackets, so the one instantiation spells
// Map[K, V] in Go and Map<K, V> in Java.
//
// Form and Elems carry the structure the frontend parsed, in the
// form's fixed child order: one child for Optional, List, Array,
// Stream and Borrow; the key then the value for Map; the
// parameters then the returns for Func, the returns from Split;
// the members for Tuple and Union; the bound for Wildcard, with
// Variance; none for Inline and Named. The spelling stays verbatim
// beside them, so a backend spells what it read, and the
// resolution step reaches the named types inside a composite
// through the children. A structural reference carries no target
// of its own; its Named children do. Length holds a fixed array
// length written as a literal, and 0 where the length is an
// expression the spelling keeps.
//
// This is the node spelling of the kind.
type TypeRef = core.TypeRef

// TypeParam is one parameter of a generic declaration.
//
// Variance is Invariant for Go and Rust, and carries the declared
// variance for Kotlin, C# and Java wildcards. Bounds holds the
// constraint as type references: a Go constraint interface, a Java
// or Kotlin upper bound, a Rust trait bound. What a bound cannot
// express in references, such as a Go constraint's full type set,
// stays in language metadata.
//
// Default is the type argument used when a caller supplies none,
// which TypeScript writes as "<T = string>". It is nil where the
// language has no such form.
//
// Const marks a parameter whose argument is a value rather than a
// type, which Rust writes as "<const N: usize>". Type then carries
// the value's type and DefaultValue its default spelling; both stay
// empty for an ordinary type parameter.
//
// This is the node spelling of the kind.
type TypeParam = core.TypeParam

// Embed is one embedded type in a declaration that promotes
// members: a Go embedded field or embedded interface, a PHP trait
// use.
//
// Embedding differs from nominal supertyping because the members
// arrive promoted rather than inherited, and resolving what a type
// effectively holds across embeds is a language rule rather than a
// model one.
//
// An embed is a declaration in its own right: it carries the
// documentation, trailing comment, tag and annotations an embedded
// field takes like any field, and its identity, named by the
// embedded type's bare name, is what a directive attaches to.
//
// This is the node spelling of the kind.
type Embed = core.Embed

// Symbols is the type of a field that admits declarations of any
// kind, such as a file's declaration list.
//
// Decoding a plain `[]symbol.Symbol` fails, because nothing tells
// the decoder which kind to allocate for an element. Every other
// field is typed concretely and decodes through the struct tags on
// the models.
type Symbols = core.Symbols

// EncodeJSON encodes a declaration with its kind, so a decoder can
// allocate the right kind.
//
// The fields come from the declaration's own struct tags, and
// EncodeJSON writes the kind in front of them. A nil declaration
// encodes as JSON null, which [DecodeJSON] reads back as nil. A
// declaration whose own encoding is not an object is refused,
// because the kind can only be spliced into an object.
func EncodeJSON(s symbol.Symbol) ([]byte, error) {
	return core.EncodeJSON(s)
}

// DecodeJSON decodes a declaration encoded by [EncodeJSON].
//
// It reads the kind, allocates a declaration of that kind and
// decodes the fields through its struct tags. JSON null decodes to
// a nil declaration, and an unknown or absent kind is an error
// naming what it read.
func DecodeJSON(data []byte) (symbol.Symbol, error) {
	return core.DecodeJSON(data)
}

// Walk visits s and every declaration it contains, depth first, in
// schema field order.
//
// Returning false from visit prunes that subtree and continues.
// Only containment edges are followed, so the walk is a tree even
// though the graph is not: a back-pointer is never traversed, and a
// cross-reference is an identity rather than a pointer.
func Walk(s symbol.Symbol, visit func(symbol.Symbol) bool) {
	core.Walk(s, visit)
}

// All returns the same traversal as [Walk], as an iterator.
//
// Stopping the range stops the walk, which differs from Walk's own
// visit: there, false prunes one subtree.
func All(s symbol.Symbol) iter.Seq[symbol.Symbol] {
	return core.All(s)
}

// Declaration is a declaration that names itself.
//
// Every kind on this side satisfies it. The interface exists because
// the fields typed [Symbols] admit any symbol, so a traversal is
// statically a sequence of [symbol.Symbol] even where every element
// is one of these.
type Declaration = core.Declaration

// Declarations returns the traversal [All] makes, typed as the
// declarations it yields.
//
// A symbol that does not name itself is skipped rather than
// answered, which only a foreign implementation placed in a
// [Symbols] field can be. Its subtree still walks, because
// containment does not depend on identity.
func Declarations(s symbol.Symbol) iter.Seq[Declaration] {
	return core.Declarations(s)
}
