// Copyright Dokimasia B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/model. DO NOT EDIT.

package symbol_test

import (
	"testing"

	"go.dokimi.dev/assert"
	"go.dokimi.dev/assert/bench"
	. "go.dokimi.dev/eidos/core/symbol"
)

// factNamings pairs every fact with the name String returns.
var factNamings = []struct {
	fact Fact
	want string
}{
	{fact: FactInvalid, want: "Invalid"},
	{fact: FactComment, want: "Comment"},
	{fact: FactVisibility, want: "Visibility"},
	{fact: FactAsync, want: "Async"},
	{fact: FactTypeParams, want: "TypeParams"},
	{fact: FactMultiReturn, want: "MultiReturn"},
	{fact: FactThrows, want: "Throws"},
	{fact: FactAnnotations, want: "Annotations"},
	{fact: FactLevel, want: "Level"},
	{fact: FactAbstract, want: "Abstract"},
	{fact: FactFinal, want: "Final"},
	{fact: FactOverride, want: "Override"},
	{fact: FactDefaultBody, want: "DefaultBody"},
	{fact: FactAccessor, want: "Accessor"},
	{fact: FactIndexer, want: "Indexer"},
	{fact: FactConstructs, want: "Constructs"},
	{fact: FactHardPrivate, want: "HardPrivate"},
	{fact: FactLabel, want: "Label"},
	{fact: FactParamDefault, want: "ParamDefault"},
	{fact: FactOptional, want: "Optional"},
	{fact: FactVariadic, want: "Variadic"},
	{fact: FactNamedReturn, want: "NamedReturn"},
	{fact: FactConstEnum, want: "ConstEnum"},
	{fact: FactFields, want: "Fields"},
	{fact: FactMethods, want: "Methods"},
	{fact: FactValue, want: "Value"},
	{fact: FactMutability, want: "Mutability"},
	{fact: FactTag, want: "Tag"},
	{fact: FactSealed, want: "Sealed"},
	{fact: FactTypes, want: "Types"},
	{fact: FactEmbeds, want: "Embeds"},
	{fact: FactExtends, want: "Extends"},
	{fact: FactImplements, want: "Implements"},
	{fact: FactPermits, want: "Permits"},
	{fact: FactProperties, want: "Properties"},
	{fact: FactDefined, want: "Defined"},
	{fact: FactVariance, want: "Variance"},
	{fact: FactConstParam, want: "ConstParam"},
	{fact: FactTypeParamDefault, want: "TypeParamDefault"},
}

// A fact is what a coverage declaration is held total against, so
// each spells its schema name and Facts lists every one.
func TestFact(t *testing.T) {
	t.Parallel()

	t.Run("String", func(t *testing.T) {
		t.Parallel()

		for _, tt := range factNamings {
			t.Run("returns "+tt.want+" for its fact", func(t *testing.T) {
				t.Parallel()

				assert.Equal(t, tt.fact.String(), tt.want,
					"the fact spells its schema name")
			})
		}

		t.Run("returns a distinct name for every fact", func(t *testing.T) {
			t.Parallel()

			seen := make(map[string]struct{}, len(factNamings))
			for _, tt := range factNamings {
				seen[tt.want] = struct{}{}
			}
			assert.Length(t, seen, len(factNamings),
				"every fact returns its own name")
		})

		t.Run("returns a placeholder for a value outside the set", func(t *testing.T) {
			t.Parallel()

			// The first value past the set is the one the bound
			// itself decides: a guard admitting it would index the
			// name table out of range.
			edge := Fact(len(factNamings))
			assert.NotEqual(t, edge.String(), "",
				"the first value outside the set returns a placeholder")

			outside := Fact(len(factNamings) + 1)
			assert.NotEqual(t, outside.String(), "",
				"and so does one well past it")
		})
	})

	t.Run("Facts", func(t *testing.T) {
		t.Parallel()

		t.Run("returns every declared fact in constant order", func(t *testing.T) {
			t.Parallel()

			all := Facts()
			assert.Length(t, all, len(factNamings)-1,
				"every declared fact arrives, the invalid zero left out")
			for i, f := range all {
				assert.Equal(t, f, factNamings[i+1].fact,
					"in constant order")
			}
		})
	})
}

// String allocates nothing and Facts allocates its one slice in the
// ordinary run, which runs no benchmark.
func TestFactAllocs(t *testing.T) {
	var spelled int
	assert.MaxAllocs(t, func() { spelled = spellEveryFact() }, 0, "String allocates nothing")
	assert.Equal(t, spelled, len(factNamings), "String spells every fact")
	var all []Fact
	assert.MaxAllocs(t, func() { all = Facts() }, 1, "Facts allocates its one slice")
	assert.Length(t, all, len(factNamings)-1, "Facts returns every declared fact")
}

// BenchmarkFact measures the spelling of every fact and the list of
// every fact.
func BenchmarkFact(b *testing.B) {
	b.Run("String", func(b *testing.B) {
		b.Run("every fact", func(b *testing.B) {
			c := bench.Start(b).MaxAllocs(0)
			defer c.End()
			var spelled int
			for c.Loop() {
				spelled = spellEveryFact()
			}
			assert.Equal(b, spelled, len(factNamings), "String spells every fact")
		})
	})

	b.Run("Facts", func(b *testing.B) {
		c := bench.Start(b).MaxAllocs(1)
		defer c.End()
		var all []Fact
		for c.Loop() {
			all = Facts()
		}
		assert.Length(b, all, len(factNamings)-1, "Facts returns every declared fact")
	})
}

// spellEveryFact spells every fact, and returns how many spellings
// were not empty.
func spellEveryFact() int {
	spelled := 0
	for _, tt := range factNamings {
		if tt.fact.String() != "" {
			spelled++
		}
	}
	return spelled
}
