// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: MIT

// Code generated by internal/gen/model. DO NOT EDIT.

package symbol

import (
	"testing"

	"go.dokimi.dev/assert"
)

// factNamings pairs every fact with the name String returns.
var factNamings = []struct {
	fact Fact
	want string
}{
	{fact: FactInvalid, want: "Invalid"},
	{fact: FactVisibility, want: "Visibility"},
	{fact: FactAsync, want: "Async"},
	{fact: FactTypeParams, want: "TypeParams"},
	{fact: FactMultiReturn, want: "MultiReturn"},
	{fact: FactThrows, want: "Throws"},
	{fact: FactAnnotations, want: "Annotations"},
	{fact: FactLevel, want: "Level"},
	{fact: FactAbstract, want: "Abstract"},
	{fact: FactFinal, want: "Final"},
	{fact: FactOverride, want: "Override"},
	{fact: FactDefaultBody, want: "DefaultBody"},
	{fact: FactLabel, want: "Label"},
	{fact: FactParamDefault, want: "ParamDefault"},
	{fact: FactVariadic, want: "Variadic"},
	{fact: FactNamedReturn, want: "NamedReturn"},
	{fact: FactFields, want: "Fields"},
	{fact: FactMethods, want: "Methods"},
	{fact: FactValue, want: "Value"},
	{fact: FactComment, want: "Comment"},
	{fact: FactMutability, want: "Mutability"},
	{fact: FactTag, want: "Tag"},
	{fact: FactSealed, want: "Sealed"},
	{fact: FactTypes, want: "Types"},
	{fact: FactEmbeds, want: "Embeds"},
	{fact: FactExtends, want: "Extends"},
	{fact: FactImplements, want: "Implements"},
	{fact: FactPermits, want: "Permits"},
	{fact: FactProperties, want: "Properties"},
	{fact: FactDefined, want: "Defined"},
	{fact: FactVariance, want: "Variance"},
	{fact: FactTypeParamDefault, want: "TypeParamDefault"},
	{fact: FactConstParam, want: "ConstParam"},
}

func TestFact(t *testing.T) {
	t.Parallel()

	t.Run("String", func(t *testing.T) {
		t.Parallel()

		for _, tt := range factNamings {
			t.Run(tt.want, func(t *testing.T) {
				t.Parallel()
				assert.Equal(t, tt.fact.String(), tt.want,
					"the fact spells its schema name")
			})
		}

		t.Run("names are unique", func(t *testing.T) {
			t.Parallel()

			seen := make(map[string]struct{}, len(factNamings))
			for _, tt := range factNamings {
				seen[tt.want] = struct{}{}
			}
			assert.Length(t, seen, len(factNamings),
				"every fact returns its own name")
		})

		t.Run("a value outside the set returns a placeholder", func(t *testing.T) {
			t.Parallel()

			outside := Fact(len(factNamings) + 1)
			assert.NotEqual(t, outside.String(), "",
				"a value outside the set returns a placeholder")
		})
	})

	t.Run("Facts", func(t *testing.T) {
		t.Parallel()

		all := Facts()
		assert.Length(t, all, len(factNamings)-1,
			"every declared fact arrives, the invalid zero left out")
		for i, f := range all {
			assert.Equal(t, f, factNamings[i+1].fact,
				"in constant order")
		}
	})
}
