// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: MIT

// Code generated by internal/gen/model. DO NOT EDIT.

package symbol

import (
	"testing"

	"go.dokimi.dev/assert"
)

// kindNamings pairs every kind with the name it answers, which is
// what String writes and ParseKind reads back.
var kindNamings = []struct {
	kind Kind
	want string
}{
	{kind: KindInvalid, want: "Invalid"},
	{kind: KindFunction, want: "Function"},
	{kind: KindMethod, want: "Method"},
	{kind: KindParam, want: "Param"},
	{kind: KindReturn, want: "Return"},
	{kind: KindPackage, want: "Package"},
	{kind: KindFile, want: "File"},
	{kind: KindImport, want: "Import"},
	{kind: KindExport, want: "Export"},
	{kind: KindBinding, want: "Binding"},
	{kind: KindEnum, want: "Enum"},
	{kind: KindEnumVariant, want: "EnumVariant"},
	{kind: KindSum, want: "Sum"},
	{kind: KindSumVariant, want: "SumVariant"},
	{kind: KindField, want: "Field"},
	{kind: KindVariable, want: "Variable"},
	{kind: KindConstant, want: "Constant"},
	{kind: KindStruct, want: "Struct"},
	{kind: KindInterface, want: "Interface"},
	{kind: KindAlias, want: "Alias"},
	{kind: KindTypeRef, want: "TypeRef"},
	{kind: KindTypeParam, want: "TypeParam"},
	{kind: KindConstraint, want: "Constraint"},
	{kind: KindEmbed, want: "Embed"},
}

func TestKind(t *testing.T) {
	t.Parallel()

	t.Run("String", func(t *testing.T) {
		t.Parallel()

		for _, tt := range kindNamings {
			t.Run(tt.want, func(t *testing.T) {
				t.Parallel()
				assert.Equal(t, tt.kind.String(), tt.want,
					"the kind spells its schema name")
			})
		}

		t.Run("names are unique", func(t *testing.T) {
			t.Parallel()

			seen := make(map[string]struct{}, len(kindNamings))
			for _, tt := range kindNamings {
				seen[tt.want] = struct{}{}
			}
			assert.Length(t, seen, len(kindNamings),
				"every kind answers its own name")
		})

		t.Run("a value outside the set answers a placeholder", func(t *testing.T) {
			t.Parallel()

			outside := Kind(len(kindNamings) + 1)
			assert.NotEqual(t, outside.String(), "",
				"a value outside the set answers a placeholder")
		})
	})

	t.Run("ParseKind", func(t *testing.T) {
		t.Parallel()

		t.Run("answers the kind a name spells", func(t *testing.T) {
			t.Parallel()

			for _, tt := range kindNamings {
				if tt.kind == KindInvalid {
					continue
				}
				t.Run(tt.want, func(t *testing.T) {
					t.Parallel()

					got, known := ParseKind(tt.want)
					assert.True(t, known, "a name a kind carries parses")
					assert.Equal(t, got, tt.kind, "to the kind that carries it")
				})
			}
		})

		// The pair is what lets a kind cross a boundary carrying
		// names: whatever String writes, ParseKind has to read back.
		t.Run("inverts String for every kind", func(t *testing.T) {
			t.Parallel()

			for _, tt := range kindNamings {
				if tt.kind == KindInvalid {
					continue
				}
				got, known := ParseKind(tt.kind.String())
				assert.True(t, known, "whatever String writes, ParseKind reads back")
				assert.Equal(t, got, tt.kind, "to the same kind")
			}
		})

		t.Run("answers KindInvalid when it refuses", func(t *testing.T) {
			t.Parallel()

			// A caller that drops the boolean must not receive a
			// usable kind, so the refusal answers the zero value
			// rather than whatever the lookup left behind.
			got, known := ParseKind("Nonexistent")
			assert.False(t, known, "a name no kind carries is refused")
			assert.Equal(t, got, KindInvalid,
				"and a caller that drops the boolean holds no usable kind")
		})

		t.Run("refuses a name no kind answers", func(t *testing.T) {
			t.Parallel()

			// A kind's name is its Go type name, matched exactly:
			// nothing trims, folds case or accepts a near miss.
			tests := []struct {
				name string
				why  string
			}{
				{name: "", why: "the empty name"},
				{name: "Nonexistent", why: "a name no kind carries"},
				{name: "struct", why: "the lowered spelling"},
				{name: "STRUCT", why: "the upper spelling"},
				{name: " Struct", why: "a leading space"},
				{name: "Struct ", why: "a trailing space"},
				{name: "Struct\n", why: "a trailing newline"},
				{name: "Invalid", why: "the placeholder String answers for a non-kind"},
				{name: "Kind(0)", why: "the placeholder String answers outside the set"},
			}
			for _, tt := range tests {
				t.Run(tt.why, func(t *testing.T) {
					t.Parallel()

					_, known := ParseKind(tt.name)
					assert.False(t, known,
						"a name is matched exactly: nothing trims, folds case "+
							"or accepts a near miss")
				})
			}
		})
	})
}
