// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/facade. DO NOT EDIT.

// Package plugintest re-exports [go.dokimi.dev/eidos/core/plugin/plugintest]:
// one alias, constant or wrapper per exported symbol, so plugin
// code speaks the facade's paths while the kernel package stays
// the single home of every definition.
//
// # Dependency position
//
// sdk/plugintest imports core/plugin/plugintest, sdk/meta,
// sdk/symbol, go.dokimi.dev/assert and the Go stdlib.
package plugintest

import (
	"testing"

	"go.dokimi.dev/assert"

	core "go.dokimi.dev/eidos/core/plugin/plugintest"
	"go.dokimi.dev/eidos/sdk/meta"
	"go.dokimi.dev/eidos/sdk/symbol"
)

// Fixture is a hand-built run: the graph, the fact store, the
// validated directive table and the scope one plugin's phase calls
// see. Build it, load packages, stamp facts, then hand a plugin to
// [Fixture.Annotate] or [Fixture.Generate].
//
// The graph freezes on the first phase call, so every load and
// attach comes before it. A later structural write fails the test
// through the store's error. A Fixture belongs to one test and is
// not safe for concurrent use.
type Fixture = core.Fixture

// New returns an empty fixture at bucket one, with the kernel's
// keys registered.
func New(tb assert.TB) *Fixture {
	return core.New(tb)
}

// Key registers a typed key under the fixture's registry, claiming
// the name's namespace on first use.
func Key[T meta.FactValue](tb assert.TB, f *Fixture, name meta.KeyName, doc string) meta.Key[T] {
	return core.Key[T](tb, f, name, doc)
}

// Stamp records one subject-bound fact at plugin authority, as an
// earlier annotator's stamp records it.
func Stamp[T meta.FactValue](tb assert.TB, f *Fixture, k meta.Key[T], subject symbol.Identity, v T) {
	core.Stamp[T](tb, f, k, subject, v)
}

// Result is what one phase call left behind: the plan's emit store,
// the findings, and the fatal error where the phase returned one.
type Result = core.Result

// Setup builds the plugin under test together with the fixture it
// runs over, the way a composition builds them: sharing one key
// registry, one schema set, one graph. The suite calls it more
// than once, because declaration stability compares two builds and
// determinism compares two isolated runs, so a Setup returns a
// fresh pair every call.
type Setup = core.Setup

// RunPluginSuite runs the conformance checks a fixture needs no
// workspace for: declaration stability, byte-equal emit across
// isolated runs, the same output under parallel dispatch, annotator
// idempotence, positioned diagnostics, attribution, declared tags,
// the options schema, the template lint, and no panics. It skips the
// checks for a role or a surface the plugin does not implement.
func RunPluginSuite(t *testing.T, setup Setup) {
	core.RunPluginSuite(t, setup)
}

// AssertPopulatedFixture refuses a fixture whose files declare
// nothing: every other check in the suite passes vacuously over an
// empty run and proves nothing, which is the emptiness this kit's
// siblings already refuse. Every declaration a file declares is of
// a kind a trigger matches, so one is enough.
func AssertPopulatedFixture(tb assert.TB, setup Setup) {
	core.AssertPopulatedFixture(tb, setup)
}

// AssertStableDeclaration fails unless two builds of one plugin
// declare the same name, gate records, outputs and schemas. A
// declaration that varies between builds breaks every consumer
// that keys on it.
func AssertStableDeclaration(tb assert.TB, setup Setup) {
	core.AssertStableDeclaration(tb, setup)
}

// AssertTemplates lints every declared template tree through the
// lint the render pass runs, once per language the fixture has,
// with the helpers and overrides the plugin declares for that
// language: a plugin that would fail at CI fails in its own tests
// first. A setup that declares no tree for any fixture language
// fails the check, because a lint over nothing proves nothing, and
// [RunPluginSuite] runs it only for a plugin that declares one.
func AssertTemplates(tb assert.TB, setup Setup) {
	core.AssertTemplates(tb, setup)
}

// AssertOptionsSchema checks the plugin's options struct against
// the tag contract, through the check the composition runs, so a
// plugin that would fail at Build fails in its own tests first.
func AssertOptionsSchema(tb assert.TB, setup Setup) {
	core.AssertOptionsSchema(tb, setup)
}

// AssertDeterministicEmit runs one plugin over two isolated
// fixtures and fails unless both runs emit the same bytes: the
// byte-identity contract, checked before any renderer exists.
func AssertDeterministicEmit(tb assert.TB, setup Setup) {
	core.AssertDeterministicEmit(tb, setup)
}

// AssertParallelDispatch runs every phase the plugin implements over
// two isolated fixtures, one dispatching sequentially and one on eight
// workers, and fails unless both runs emit the same bytes, end with the
// same fact values and report the same findings in the same order: the
// output of a phase call does not depend on its worker count. Run under
// the race detector, the parallel run also exposes state a handler
// writes outside its effects.
func AssertParallelDispatch(tb assert.TB, setup Setup) {
	core.AssertParallelDispatch(tb, setup)
}

// AssertIdempotentAnnotate runs one plugin's annotate phase twice
// over one fixture. It fails unless both passes stamp clean and the
// second pass leaves every fact's value unchanged. A stamp that
// depends on run state either claims a second value from the same
// rank source, which the fact store refuses, or changes the value
// that ranks first, which the comparison refuses.
func AssertIdempotentAnnotate(tb assert.TB, setup Setup) {
	core.AssertIdempotentAnnotate(tb, setup)
}

// AssertPositionedDiagnostics runs every phase the plugin implements and
// refuses a finding without a position: a diagnostic nobody can
// jump to is a defect in whatever reported it.
func AssertPositionedDiagnostics(tb assert.TB, setup Setup) {
	core.AssertPositionedDiagnostics(tb, setup)
}

// AssertAttributedEmit runs the generate phase and checks every
// unit the plugin flushed against the plugin's name and its
// declared families: output nobody can attribute, or under a tag
// nothing declared, is a routing hole. The check skips the units
// the fixture seeded, which are other plugins' output.
func AssertAttributedEmit(tb assert.TB, setup Setup) {
	core.AssertAttributedEmit(tb, setup)
}

// AssertTwins fails unless two spellings of one plugin, usually a
// facade build and a hand-rolled SPI twin, emit the same bytes: the
// lowering guarantee, checked from outside the facade. Each setup
// returns its own spelling over an equivalent fixture.
func AssertTwins(tb assert.TB, facade, twin Setup) {
	core.AssertTwins(tb, facade, twin)
}

// AssertNoStructuralWrites runs every phase the plugin implements
// and fails unless the graph's bytes are unchanged afterwards:
// annotators and generators read declarations through shared
// pointers, so mutating one in place is the structural write the
// sealed store cannot refuse, and this check catches it.
func AssertNoStructuralWrites(tb assert.TB, setup Setup) {
	core.AssertNoStructuralWrites(tb, setup)
}
