// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/facade. DO NOT EDIT.

package symbol_test

import (
	"reflect"
	"testing"

	"go.dokimi.dev/assert"

	core "go.dokimi.dev/eidos/core/symbol"
	"go.dokimi.dev/eidos/sdk/symbol"
)

// The facade re-exports go.dokimi.dev/eidos/core/symbol: every type is the kernel's
// own type, every constant and variable equals the kernel's value,
// and every wrapper has the kernel function's signature.
func TestFacade(t *testing.T) {
	t.Parallel()

	t.Run("Annotation", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[symbol.Annotation](), reflect.TypeFor[core.Annotation](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Annotations", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[symbol.Annotations](), reflect.TypeFor[core.Annotations](), "the facade aliases the kernel's type")
		})
	})

	t.Run("FactInvalid", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactInvalid, core.FactInvalid, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactComment", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactComment, core.FactComment, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactVisibility", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactVisibility, core.FactVisibility, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactAsync", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactAsync, core.FactAsync, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactTypeParams", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactTypeParams, core.FactTypeParams, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactMultiReturn", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactMultiReturn, core.FactMultiReturn, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactThrows", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactThrows, core.FactThrows, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactAnnotations", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactAnnotations, core.FactAnnotations, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactLevel", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactLevel, core.FactLevel, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactAbstract", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactAbstract, core.FactAbstract, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactFinal", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactFinal, core.FactFinal, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactOverride", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactOverride, core.FactOverride, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactDefaultBody", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactDefaultBody, core.FactDefaultBody, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactAccessor", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactAccessor, core.FactAccessor, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactIndexer", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactIndexer, core.FactIndexer, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactConstructs", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactConstructs, core.FactConstructs, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactHardPrivate", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactHardPrivate, core.FactHardPrivate, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactLabel", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactLabel, core.FactLabel, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactParamDefault", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactParamDefault, core.FactParamDefault, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactOptional", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactOptional, core.FactOptional, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactVariadic", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactVariadic, core.FactVariadic, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactNamedReturn", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactNamedReturn, core.FactNamedReturn, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactConstEnum", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactConstEnum, core.FactConstEnum, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactFields", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactFields, core.FactFields, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactMethods", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactMethods, core.FactMethods, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactValue", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactValue, core.FactValue, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactMutability", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactMutability, core.FactMutability, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactTag", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactTag, core.FactTag, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactSealed", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactSealed, core.FactSealed, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactTypes", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactTypes, core.FactTypes, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactEmbeds", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactEmbeds, core.FactEmbeds, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactExtends", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactExtends, core.FactExtends, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactImplements", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactImplements, core.FactImplements, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactPermits", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactPermits, core.FactPermits, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactProperties", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactProperties, core.FactProperties, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactDefined", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactDefined, core.FactDefined, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactVariance", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactVariance, core.FactVariance, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactTypeParamDefault", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactTypeParamDefault, core.FactTypeParamDefault, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FactConstParam", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FactConstParam, core.FactConstParam, "the facade re-declares the kernel's value")
		})
	})

	t.Run("Facts", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(symbol.Facts), reflect.TypeOf(core.Facts), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("Fact", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[symbol.Fact](), reflect.TypeFor[core.Fact](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Lang", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[symbol.Lang](), reflect.TypeFor[core.Lang](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Identity", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[symbol.Identity](), reflect.TypeFor[core.Identity](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Parse", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(symbol.Parse), reflect.TypeOf(core.Parse), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("KindInvalid", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindInvalid, core.KindInvalid, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindFunction", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindFunction, core.KindFunction, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindMethod", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindMethod, core.KindMethod, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindParam", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindParam, core.KindParam, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindReturn", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindReturn, core.KindReturn, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindPackage", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindPackage, core.KindPackage, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindFile", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindFile, core.KindFile, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindImport", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindImport, core.KindImport, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindExport", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindExport, core.KindExport, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindBinding", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindBinding, core.KindBinding, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindEnum", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindEnum, core.KindEnum, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindEnumVariant", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindEnumVariant, core.KindEnumVariant, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindSum", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindSum, core.KindSum, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindSumVariant", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindSumVariant, core.KindSumVariant, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindField", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindField, core.KindField, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindVariable", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindVariable, core.KindVariable, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindConstant", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindConstant, core.KindConstant, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindStruct", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindStruct, core.KindStruct, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindInterface", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindInterface, core.KindInterface, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindAlias", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindAlias, core.KindAlias, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindTypeRef", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindTypeRef, core.KindTypeRef, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindTypeParam", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindTypeParam, core.KindTypeParam, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KindEmbed", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.KindEmbed, core.KindEmbed, "the facade re-declares the kernel's value")
		})
	})

	t.Run("ParseKind", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(symbol.ParseKind), reflect.TypeOf(core.ParseKind), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("Kind", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[symbol.Kind](), reflect.TypeFor[core.Kind](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Visibility", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[symbol.Visibility](), reflect.TypeFor[core.Visibility](), "the facade aliases the kernel's type")
		})
	})

	t.Run("VisibilityUnknown", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.VisibilityUnknown, core.VisibilityUnknown, "the facade re-declares the kernel's value")
		})
	})

	t.Run("VisibilityPublic", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.VisibilityPublic, core.VisibilityPublic, "the facade re-declares the kernel's value")
		})
	})

	t.Run("VisibilityPackage", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.VisibilityPackage, core.VisibilityPackage, "the facade re-declares the kernel's value")
		})
	})

	t.Run("VisibilityProtected", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.VisibilityProtected, core.VisibilityProtected, "the facade re-declares the kernel's value")
		})
	})

	t.Run("VisibilityPrivate", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.VisibilityPrivate, core.VisibilityPrivate, "the facade re-declares the kernel's value")
		})
	})

	t.Run("VisibilityInternal", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.VisibilityInternal, core.VisibilityInternal, "the facade re-declares the kernel's value")
		})
	})

	t.Run("Level", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[symbol.Level](), reflect.TypeFor[core.Level](), "the facade aliases the kernel's type")
		})
	})

	t.Run("LevelInstance", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.LevelInstance, core.LevelInstance, "the facade re-declares the kernel's value")
		})
	})

	t.Run("LevelType", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.LevelType, core.LevelType, "the facade re-declares the kernel's value")
		})
	})

	t.Run("Accessor", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[symbol.Accessor](), reflect.TypeFor[core.Accessor](), "the facade aliases the kernel's type")
		})
	})

	t.Run("AccessorNone", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.AccessorNone, core.AccessorNone, "the facade re-declares the kernel's value")
		})
	})

	t.Run("AccessorGet", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.AccessorGet, core.AccessorGet, "the facade re-declares the kernel's value")
		})
	})

	t.Run("AccessorSet", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.AccessorSet, core.AccessorSet, "the facade re-declares the kernel's value")
		})
	})

	t.Run("Variance", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[symbol.Variance](), reflect.TypeFor[core.Variance](), "the facade aliases the kernel's type")
		})
	})

	t.Run("VarianceInvariant", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.VarianceInvariant, core.VarianceInvariant, "the facade re-declares the kernel's value")
		})
	})

	t.Run("VarianceIn", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.VarianceIn, core.VarianceIn, "the facade re-declares the kernel's value")
		})
	})

	t.Run("VarianceOut", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.VarianceOut, core.VarianceOut, "the facade re-declares the kernel's value")
		})
	})

	t.Run("Mutability", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[symbol.Mutability](), reflect.TypeFor[core.Mutability](), "the facade aliases the kernel's type")
		})
	})

	t.Run("MutabilityUnknown", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.MutabilityUnknown, core.MutabilityUnknown, "the facade re-declares the kernel's value")
		})
	})

	t.Run("MutabilityMutable", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.MutabilityMutable, core.MutabilityMutable, "the facade re-declares the kernel's value")
		})
	})

	t.Run("MutabilityImmutable", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.MutabilityImmutable, core.MutabilityImmutable, "the facade re-declares the kernel's value")
		})
	})

	t.Run("TypeForm", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[symbol.TypeForm](), reflect.TypeFor[core.TypeForm](), "the facade aliases the kernel's type")
		})
	})

	t.Run("FormNamed", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormNamed, core.FormNamed, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormOptional", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormOptional, core.FormOptional, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormList", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormList, core.FormList, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormArray", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormArray, core.FormArray, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormMap", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormMap, core.FormMap, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormFunc", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormFunc, core.FormFunc, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormTuple", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormTuple, core.FormTuple, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormUnion", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormUnion, core.FormUnion, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormIntersection", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormIntersection, core.FormIntersection, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormStream", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormStream, core.FormStream, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormBorrow", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormBorrow, core.FormBorrow, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormWildcard", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormWildcard, core.FormWildcard, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormInline", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormInline, core.FormInline, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormScalar", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormScalar, core.FormScalar, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormBool", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormBool, core.FormBool, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormText", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormText, core.FormText, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormBytes", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormBytes, core.FormBytes, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormReference", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormReference, core.FormReference, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormSum", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormSum, core.FormSum, "the facade re-declares the kernel's value")
		})
	})

	t.Run("FormOpaque", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.FormOpaque, core.FormOpaque, "the facade re-declares the kernel's value")
		})
	})

	t.Run("Variadic", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[symbol.Variadic](), reflect.TypeFor[core.Variadic](), "the facade aliases the kernel's type")
		})
	})

	t.Run("VariadicNone", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.VariadicNone, core.VariadicNone, "the facade re-declares the kernel's value")
		})
	})

	t.Run("VariadicPositional", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.VariadicPositional, core.VariadicPositional, "the facade re-declares the kernel's value")
		})
	})

	t.Run("VariadicKeyword", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, symbol.VariadicKeyword, core.VariadicKeyword, "the facade re-declares the kernel's value")
		})
	})

	t.Run("Symbol", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[symbol.Symbol](), reflect.TypeFor[core.Symbol](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Membered", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[symbol.Membered](), reflect.TypeFor[core.Membered](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Typed", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[symbol.Typed](), reflect.TypeFor[core.Typed](), "the facade aliases the kernel's type")
		})
	})
}
