// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

package genfile

import (
	"bytes"
	"errors"
	"fmt"
	"go/format"
	"io/fs"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

// Set is a generator's whole output: each file's module-relative
// slash path mapped to the file's bytes.
//
// Paths are slash-separated on every platform, so a set compares
// equal wherever it was produced.
type Set map[string][]byte

// GeneratedSuffix and GeneratedTestSuffix mark a generated Go file.
// The mirror guard reads them to tell generated output from
// hand-written source. A generator that emits tests beside its code
// uses both.
const (
	// GeneratedSuffix marks generated source.
	GeneratedSuffix = ".gen.go"
	// GeneratedTestSuffix marks a generated test. A test file name
	// does not end in GeneratedSuffix, so the guard matches this
	// suffix separately.
	GeneratedTestSuffix = ".gen_test.go"
)

// dirPerm and filePerm are the modes of generated directories and
// files.
const (
	dirPerm  fs.FileMode = 0o750
	filePerm fs.FileMode = 0o600
)

// license, markerPrefix and markerSuffix are the fixed parts of the
// preamble. The license lines match the ones the repository stamps
// on hand-written sources. Go's tools read the marker as generated
// code, which exempts the file from the tools that restamp sources.
const (
	license      = "// Copyright ThesmOS B.V. 2026\n// SPDX-License-Identifier: Apache-2.0\n"
	markerPrefix = "// Code generated by internal/gen/"
	markerSuffix = ". DO NOT EDIT.\n"
)

// Header returns the preamble every generated file opens with: the
// license lines, a blank line, the generated-code marker naming the
// generator under internal/gen, and a blank line.
func Header(generator string) string {
	return license + "\n" + markerPrefix + generator + markerSuffix + "\n"
}

// Render formats a generator's rendered files into one set: render
// returns each item's module-relative slash path and source.
//
// Render returns a set only when every file rendered and formatted,
// so a template fault cannot leave a half-generated tree.
func Render[T any](items []T, render func(T) (string, []byte, error)) (Set, error) {
	set := make(Set, len(items))
	for _, item := range items {
		path, src, err := render(item)
		if err != nil {
			return nil, err
		}
		formatted, err := Format(path, src)
		if err != nil {
			return nil, err
		}
		set[path] = formatted
	}
	return set, nil
}

// Regenerate renders one generator's set under root and writes it
// there. It writes nothing unless the whole set rendered. The
// wrapper behind a go:generate directive calls it once it has
// resolved its root.
func Regenerate(root string, generate func(root string) (Set, error)) error {
	set, err := generate(root)
	if err != nil {
		return err
	}
	return Write(root, set)
}

// Format canonicalizes one generated file through gofmt.
//
// path names the file in the error only. A file that does not parse
// is a defect in the template that rendered it, so Format returns no
// bytes and an error that names the file and wraps the parse
// failure.
func Format(path string, src []byte) ([]byte, error) {
	out, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("genfile: format %s: %w", path, err)
	}
	return out, nil
}

// Write puts every file of the set on disk under root, creating
// directories as needed.
//
// A path that escapes root is refused before anything is written,
// so a template that composes a bad path cannot scatter files
// outside the module.
func Write(root string, set Set) error {
	paths := slices.Sorted(maps.Keys(set))
	targets := make([]string, len(paths))
	for i, path := range paths {
		target, err := resolve(root, path)
		if err != nil {
			return err
		}
		targets[i] = target
	}
	for i, path := range paths {
		if err := os.MkdirAll(filepath.Dir(targets[i]), dirPerm); err != nil {
			return fmt.Errorf("genfile: create directory for %s: %w", path, err)
		}
		if err := os.WriteFile(targets[i], set[path], filePerm); err != nil {
			return fmt.Errorf("genfile: write %s: %w", path, err)
		}
	}
	return nil
}

// Verify reports whether the tree under root matches the set: the
// mirror guard.
//
// dirs are the module-relative directories the generator writes,
// and every generated file in them has to belong to the set. The
// error names every problem in path order, so one run reports
// everything that is wrong.
func Verify(root string, set Set, dirs []string) error {
	var problems []string

	for _, path := range slices.Sorted(maps.Keys(set)) {
		target, err := resolve(root, path)
		if err != nil {
			return err
		}
		onDisk, err := os.ReadFile(target)
		switch {
		case errors.Is(err, fs.ErrNotExist):
			problems = append(problems, fmt.Sprintf("%s is missing", path))
		case err != nil:
			return fmt.Errorf("genfile: read %s: %w", path, err)
		case !bytes.Equal(onDisk, set[path]):
			problems = append(problems, fmt.Sprintf("%s differs from what the generator produces", path))
		}
	}

	strays, err := strays(root, set, dirs)
	if err != nil {
		return err
	}
	for _, path := range strays {
		problems = append(problems, fmt.Sprintf("%s is generated but no generator claims it", path))
	}

	if len(problems) == 0 {
		return nil
	}
	slices.Sort(problems)
	return fmt.Errorf("genfile: the tree does not match the generator:\n  %s",
		strings.Join(problems, "\n  "))
}

// strays lists generated files under dirs that the set does not
// name, in path order.
func strays(root string, set Set, dirs []string) ([]string, error) {
	var found []string
	for _, dir := range dirs {
		base, err := resolve(root, dir)
		if err != nil {
			return nil, err
		}
		walkErr := filepath.WalkDir(base, func(path string, d fs.DirEntry, err error) error {
			switch {
			case errors.Is(err, fs.ErrNotExist):
				return nil
			case err != nil:
				return err
			case d.IsDir():
				// The root entry "." scans its own files alone, so a
				// generator writing beside its owned directories is
				// covered without claiming every other directory of
				// the module.
				if dir == "." && path != base {
					return fs.SkipDir
				}
				return nil
			case !generated(d.Name()):
				return nil
			}
			rel, err := filepath.Rel(root, path)
			if err != nil {
				return err
			}
			if slash := filepath.ToSlash(rel); slash != "" {
				if _, claimed := set[slash]; !claimed {
					found = append(found, slash)
				}
			}
			return nil
		})
		if walkErr != nil && !errors.Is(walkErr, fs.ErrNotExist) {
			return nil, fmt.Errorf("genfile: scan %s: %w", dir, walkErr)
		}
	}
	slices.Sort(found)
	return found, nil
}

// generated reports whether a filename is generated output.
func generated(name string) bool {
	return strings.HasSuffix(name, GeneratedSuffix) ||
		strings.HasSuffix(name, GeneratedTestSuffix)
}

// resolve joins a module-relative path onto root, refusing one that
// would escape it.
func resolve(root, path string) (string, error) {
	local := filepath.FromSlash(path)
	if !filepath.IsLocal(local) {
		return "", fmt.Errorf("genfile: %s escapes the module root", path)
	}
	return filepath.Join(root, local), nil
}
