// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

package genfile_test

import (
	"errors"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"testing"

	"go.dokimi.dev/assert"
	"go.dokimi.dev/assert/bench"

	"go.dokimi.dev/eidos/core/internal/genfile"
)

// wellFormed is a source in gofmt's layout, and unformatted the same
// source before it.
const (
	wellFormed  = "package p\n\ntype T struct{ A int }\n"
	unformatted = "package p\ntype T struct{A int}\n"
)

// ownedDir, ownedPath and ownedName name the generated file most
// cases use, so the code of each case is about its fault.
const (
	ownedDir  = "node"
	ownedPath = ownedDir + "/kinds.gen.go"
	ownedName = "kinds.gen.go"
)

// The ceilings of the generator plumbing over the fixture's one or two
// files.
const (
	// formatAllocs is one gofmt of the unformatted fixture source:
	// go/format's parse of the file and its print of the tree.
	formatAllocs = 41
	// renderAllocs is one Render of two items: a gofmt of each item's
	// source, 41 each, the bytes each render returns, and the set.
	renderAllocs = 88
	// writeAllocs is one Write of one file into a tree that has its
	// directory: the sorted paths, the target path, the directory check
	// and the file the write opens.
	writeAllocs = 10
	// regenerateAllocs is one Regenerate of one file: the Write of the
	// set the generator returns.
	regenerateAllocs = writeAllocs
	// verifyAllocs is one Verify of a tree that matches its set of one
	// file: the sorted paths, the read of the file, and the walk of the
	// owned directory.
	verifyAllocs = 22
)

// owned is the fixture set of one generated file.
var owned = genfile.Set{ownedPath: []byte(wellFormed)}

// blocked puts a directory where the set's file belongs and
// returns the root. The parent directory then creates, and the
// read or the write of the file itself is what fails.
func blocked(t *testing.T) string {
	t.Helper()

	root := t.TempDir()
	assert.NoError(t, os.MkdirAll(filepath.Join(root, ownedDir, ownedName), 0o750),
		"the blocking directory is created")
	return root
}

// The plumbing every generator writes and verifies through: the
// preamble, the formatted set, the write and the mirror guard.
func TestGenfile(t *testing.T) {
	t.Parallel()

	t.Run("Header", func(t *testing.T) {
		t.Parallel()

		t.Run("returns the license lines then the generator's generated-code marker", func(t *testing.T) {
			t.Parallel()

			header := genfile.Header("model")
			assert.HasPrefix(t, header,
				"// Copyright ThesmOS B.V. 2026\n// SPDX-License-Identifier: Apache-2.0\n\n",
				"the license lines open the file, as on hand-written sources")
			assert.Contains(t, header, "// Code generated by internal/gen/model. DO NOT EDIT.\n",
				"the marker names the generator")
			file, err := parser.ParseFile(token.NewFileSet(), "x.gen.go",
				header+"package p\n", parser.ParseComments)
			assert.NoError(t, err, "a header over a package clause parses")
			assert.True(t, ast.IsGenerated(file), "and go/ast reads the file as generated")
		})
	})

	t.Run("Render", func(t *testing.T) {
		t.Parallel()

		t.Run("returns every rendered file formatted", func(t *testing.T) {
			t.Parallel()

			set, err := genfile.Render([]string{"node", "emit"}, renderKinds)
			assert.NoError(t, err, "every file renders and formats")
			assert.Length(t, set, 2, "one entry per item, under the path each render names")
			assert.Contains(t, string(set["node/kinds.gen.go"]), "type T struct{ A int }",
				"in canonical layout")
		})

		t.Run("returns no set for a render's error", func(t *testing.T) {
			t.Parallel()

			refusal := errors.New("genfile_test: the template refuses")
			set, err := genfile.Render([]string{"node", "emit"}, func(dir string) (string, []byte, error) {
				if dir == "emit" {
					return "", nil, refusal
				}
				return dir + "/kinds.gen.go", []byte(wellFormed), nil
			})
			assert.ErrorIs(t, err, refusal, "the render's own error returns")
			assert.Nil(t, set, "and no half-rendered set comes back")
		})

		t.Run("returns no set for a file that does not format", func(t *testing.T) {
			t.Parallel()

			set, err := genfile.Render([]string{"broken"}, func(string) (string, []byte, error) {
				return "broken.gen.go", []byte("package p\nfunc ("), nil
			})
			assert.HasError(t, err, "a file that does not parse is refused")
			assert.Contains(t, err.Error(), "broken.gen.go", "naming the file")
			assert.Nil(t, set, "and no set comes back")
		})
	})

	t.Run("Regenerate", func(t *testing.T) {
		t.Parallel()

		t.Run("writes the set the generator renders under its root", func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			err := genfile.Regenerate(root, func(got string) (genfile.Set, error) {
				assert.Equal(t, got, root, "the generator renders under the root it is handed")
				return owned, nil
			})
			assert.NoError(t, err, "the set writes")
			_, err = os.Stat(filepath.Join(root, filepath.FromSlash(ownedPath)))
			assert.NoError(t, err, "and the file is under the root")
		})

		t.Run("writes nothing for the generator's error", func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			refusal := errors.New("genfile_test: the schema refuses")
			err := genfile.Regenerate(root, func(string) (genfile.Set, error) { return nil, refusal })
			assert.ErrorIs(t, err, refusal, "the generator's own error returns")
			entries, readErr := os.ReadDir(root)
			assert.NoError(t, readErr, "the root reads")
			assert.Length(t, entries, 0, "and nothing was written")
		})
	})

	t.Run("Format", func(t *testing.T) {
		t.Parallel()

		t.Run("returns the source in gofmt's layout", func(t *testing.T) {
			t.Parallel()

			got, err := genfile.Format("x.gen.go", []byte(unformatted))
			assert.NoError(t, err, "well-formed source formats")
			assert.Equal(t, string(got), wellFormed, "and comes back in canonical layout")
		})

		t.Run("returns an error naming a file that does not parse", func(t *testing.T) {
			t.Parallel()

			_, err := genfile.Format("broken.gen.go", []byte("package p\nfunc ("))
			assert.HasError(t, err, "source that does not parse is refused")
			assert.Contains(t, err.Error(), "broken.gen.go", "naming the file")
			assert.HasPrefix(t, err.Error(), "genfile: ", "under the package prefix")
		})
	})

	t.Run("Write", func(t *testing.T) {
		t.Parallel()

		t.Run("creates every file under the root", func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			set := genfile.Set{
				"node/kinds.gen.go": []byte(wellFormed),
				"emit/kinds.gen.go": []byte(wellFormed),
			}
			assert.NoError(t, genfile.Write(root, set), "the set writes")
			for path := range set {
				_, err := os.Stat(filepath.Join(root, filepath.FromSlash(path)))
				assert.NoError(t, err, "every file arrives under the root")
			}
		})

		t.Run("returns an error for a path escaping the root", func(t *testing.T) {
			t.Parallel()

			err := genfile.Write(t.TempDir(), genfile.Set{"../escape.gen.go": []byte(wellFormed)})
			assert.HasError(t, err, "a path escaping the root is refused")
		})

		t.Run("writes no file before an escaping path's error", func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			err := genfile.Write(root, genfile.Set{
				"a.gen.go":         []byte(wellFormed),
				"b/../../x.gen.go": []byte(wellFormed),
			})
			assert.HasError(t, err, "the escaping path is refused")
			_, statErr := os.Stat(filepath.Join(root, "a.gen.go"))
			assert.True(t, os.IsNotExist(statErr),
				"and the path sorting before it was never written")
		})

		t.Run("returns an error for a directory it cannot create", func(t *testing.T) {
			t.Parallel()

			root := t.TempDir()
			blocker := filepath.Join(root, ownedDir)
			assert.NoError(t, os.WriteFile(blocker, []byte("not a directory"), 0o600),
				"the blocking file writes")
			assert.HasError(t, genfile.Write(root, owned),
				"a directory it cannot create is reported")
		})

		t.Run("returns an error for a file it cannot write", func(t *testing.T) {
			t.Parallel()

			err := genfile.Write(blocked(t), owned)
			assert.HasError(t, err, "a file it cannot write is reported")
			assert.Contains(t, err.Error(), ownedPath, "naming the file it could not put down")
			assert.HasPrefix(t, err.Error(), "genfile: ", "under the package prefix")
		})
	})

	t.Run("Verify", func(t *testing.T) {
		t.Parallel()

		t.Run("returns an error for a set path escaping the root", func(t *testing.T) {
			t.Parallel()

			set := genfile.Set{"../escape.gen.go": []byte(wellFormed)}
			assert.HasError(t, genfile.Verify(t.TempDir(), set, nil),
				"a set path escaping the root is refused")
		})

		t.Run("returns an error for an owned directory escaping the root", func(t *testing.T) {
			t.Parallel()

			err := genfile.Verify(t.TempDir(), genfile.Set{}, []string{"../elsewhere"})
			assert.HasError(t, err, "an owned directory escaping the root is refused")
		})

		t.Run("returns an error for a file it cannot read", func(t *testing.T) {
			t.Parallel()

			err := genfile.Verify(blocked(t), owned, nil)
			assert.HasError(t, err, "a set path it cannot read is reported")
			assert.Contains(t, err.Error(), ownedPath, "naming the file it could not read")
			assert.HasPrefix(t, err.Error(), "genfile: ", "under the package prefix")
		})

		t.Run("returns an error for a directory it cannot scan", func(t *testing.T) {
			t.Parallel()

			if os.Geteuid() == 0 {
				t.Skip("root reads a directory whatever its mode")
			}
			root := t.TempDir()
			locked := filepath.Join(root, ownedDir, "locked")
			assert.NoError(t, os.MkdirAll(locked, 0o750), "the locked directory is created")
			assert.NoError(t, os.Chmod(locked, 0o000), "and is closed to the scan")
			t.Cleanup(func() { _ = os.Chmod(locked, 0o750) })

			err := genfile.Verify(root, genfile.Set{}, []string{ownedDir})
			assert.HasError(t, err, "a directory it cannot scan is reported")
			assert.Contains(t, err.Error(), ownedDir, "naming the owned directory it was scanning")
			assert.HasPrefix(t, err.Error(), "genfile: ", "under the package prefix")
		})

		t.Run("returns nil for a directory the generator has not created", func(t *testing.T) {
			t.Parallel()

			assert.NoError(t, genfile.Verify(t.TempDir(), genfile.Set{}, []string{ownedDir}),
				"a directory the generator has not created passes")
		})

		t.Run("returns nil for a tree that matches the set", func(t *testing.T) {
			t.Parallel()

			assert.NoError(t, genfile.Verify(written(t), owned, []string{ownedDir}),
				"a tree matching its set verifies")
		})

		t.Run("returns an error for a file whose bytes differ", func(t *testing.T) {
			t.Parallel()

			root := written(t)
			edited := filepath.Join(root, ownedDir, ownedName)
			assert.NoError(t, os.WriteFile(edited, []byte("package p\n"), 0o600),
				"the edit arrives")
			err := genfile.Verify(root, owned, []string{ownedDir})
			assert.HasError(t, err, "a file whose bytes differ fails the mirror")
			assert.Contains(t, err.Error(), ownedName, "and is named")
		})

		t.Run("returns an error for a missing file", func(t *testing.T) {
			t.Parallel()

			assert.HasError(t, genfile.Verify(t.TempDir(), owned, []string{ownedDir}),
				"a file the set holds and the tree lacks fails the mirror")
		})

		t.Run("returns an error for a stray generated file", func(t *testing.T) {
			t.Parallel()

			root := written(t)
			stray := filepath.Join(root, ownedDir, "orphan.gen.go")
			assert.NoError(t, os.WriteFile(stray, []byte(wellFormed), 0o600),
				"the stray arrives")
			err := genfile.Verify(root, owned, []string{ownedDir})
			assert.HasError(t, err, "a generated file the set does not name is a stray")
			assert.Contains(t, err.Error(), "orphan.gen.go", "and is named")
		})

		t.Run("returns an error for a stray generated test", func(t *testing.T) {
			t.Parallel()

			root := written(t)
			stray := filepath.Join(root, ownedDir, "orphan.gen_test.go")
			assert.NoError(t, os.WriteFile(stray, []byte(wellFormed), 0o600),
				"the stray arrives")
			err := genfile.Verify(root, owned, []string{ownedDir})
			assert.HasError(t, err, "a generated test the set does not name is a stray too")
			assert.Contains(t, err.Error(), "orphan.gen_test.go", "and is named")
		})

		t.Run("returns nil beside a hand-written file", func(t *testing.T) {
			t.Parallel()

			root := written(t)
			hand := filepath.Join(root, ownedDir, "resolver.go")
			assert.NoError(t, os.WriteFile(hand, []byte(wellFormed), 0o600),
				"the hand-written file arrives")
			assert.NoError(t, genfile.Verify(root, owned, []string{ownedDir}),
				"a hand-written file is no stray: the guard owns generated names alone")
		})
	})
}

// The plumbing allocates within its ceilings in the ordinary run, which
// runs no benchmark. The check runs alone, because AllocsPerRun counts
// every goroutine's allocations and refuses to run beside parallel
// tests.
func TestGenfileAllocs(t *testing.T) {
	var header string
	assert.MaxAllocs(t, func() { header = genfile.Header("model") }, 1, "Header allocates the preamble")
	assert.NotEmpty(t, header, "Header returns the preamble")
	items := []string{"node", "emit"}
	assert.MaxAllocs(t, func() {
		if _, err := genfile.Render(items, renderKinds); err != nil {
			t.Fatalf("Render: unexpected error: %v", err)
		}
	}, renderAllocs, "Render allocates the set and each formatted file")
	root := written(t)
	assert.MaxAllocs(t, func() {
		if err := genfile.Regenerate(root, generateOwned); err != nil {
			t.Fatalf("Regenerate: unexpected error: %v", err)
		}
	}, regenerateAllocs, "Regenerate allocates the write")
	src := []byte(unformatted)
	assert.MaxAllocs(t, func() {
		if _, err := genfile.Format(ownedName, src); err != nil {
			t.Fatalf("Format: unexpected error: %v", err)
		}
	}, formatAllocs, "Format allocates gofmt's parse and print")
	assert.MaxAllocs(t, func() {
		if err := genfile.Write(root, owned); err != nil {
			t.Fatalf("Write: unexpected error: %v", err)
		}
	}, writeAllocs, "Write allocates the sorted paths and each file's write")
	dirs := []string{ownedDir}
	assert.MaxAllocs(t, func() {
		if err := genfile.Verify(root, owned, dirs); err != nil {
			t.Fatalf("Verify: unexpected error: %v", err)
		}
	}, verifyAllocs, "Verify allocates each file's read and the scan of each directory")
}

// BenchmarkGenfile measures the plumbing over the fixture's files: the
// preamble, a set's rendering, its write and its verification.
func BenchmarkGenfile(b *testing.B) {
	b.Run("Header", func(b *testing.B) {
		c := bench.Start(b).MaxAllocs(1)
		defer c.End()
		var got string
		for c.Loop() {
			got = genfile.Header("model")
		}
		assert.Contains(b, got, "internal/gen/model", "Header names the generator")
	})

	b.Run("Render/two items", func(b *testing.B) {
		items := []string{"node", "emit"}
		c := bench.Start(b).MaxAllocs(renderAllocs)
		defer c.End()
		var (
			got genfile.Set
			err error
		)
		for c.Loop() {
			got, err = genfile.Render(items, renderKinds)
		}
		assert.NoError(b, err, "every file renders")
		assert.Length(b, got, 2, "one file per item")
	})

	b.Run("Regenerate/one file", func(b *testing.B) {
		root := written(b)
		c := bench.Start(b).MaxAllocs(regenerateAllocs)
		defer c.End()
		var err error
		for c.Loop() {
			err = genfile.Regenerate(root, generateOwned)
		}
		assert.NoError(b, err, "the set writes")
	})

	b.Run("Format", func(b *testing.B) {
		src := []byte(unformatted)
		c := bench.Start(b).MaxAllocs(formatAllocs)
		defer c.End()
		var (
			got []byte
			err error
		)
		for c.Loop() {
			got, err = genfile.Format(ownedName, src)
		}
		assert.NoError(b, err, "the source formats")
		assert.Equal(b, string(got), wellFormed, "into canonical layout")
	})

	b.Run("Write/one file", func(b *testing.B) {
		root := written(b)
		c := bench.Start(b).MaxAllocs(writeAllocs)
		defer c.End()
		var err error
		for c.Loop() {
			err = genfile.Write(root, owned)
		}
		assert.NoError(b, err, "the set writes")
	})

	b.Run("Verify/a tree of one file that matches", func(b *testing.B) {
		root, dirs := written(b), []string{ownedDir}
		c := bench.Start(b).MaxAllocs(verifyAllocs)
		defer c.End()
		var err error
		for c.Loop() {
			err = genfile.Verify(root, owned, dirs)
		}
		assert.NoError(b, err, "the tree matches")
	})
}

// renderKinds renders one unformatted kinds file under dir.
func renderKinds(dir string) (string, []byte, error) {
	return dir + "/kinds.gen.go", []byte(unformatted), nil
}

// generateOwned returns the fixture set whatever root it is handed.
func generateOwned(string) (genfile.Set, error) { return owned, nil }

// written returns a temporary root the fixture set was written under.
func written(tb testing.TB) string {
	tb.Helper()

	root := tb.TempDir()
	assert.NoError(tb, genfile.Write(root, owned), "the set writes")
	return root
}
