// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: MIT

// Code generated by internal/gen/model. DO NOT EDIT.

package eidos_test

import (
	"testing"

	"go.dokimi.dev/assert"

	eidos "go.dokimi.dev/eidos/core"
	"go.dokimi.dev/eidos/core/plugin"
	"go.dokimi.dev/eidos/core/symbol"
)

// Every subject kind's constructor lowers one way: the effect
// parameter picks the phase, the record carries the kind, and the
// roles a plugin asserts are exactly what its handlers imply.
func TestMatches(t *testing.T) {
	t.Parallel()

	t.Run("Function", func(t *testing.T) {
		t.Parallel()

		emits := eidos.NewPlugin("t").
			Handle(eidos.OnFunction(func(m *eidos.FunctionMatch, e *eidos.Emitter) error {
				return nil
			})).
			Build()
		_, generates := emits.(plugin.Generator)
		assert.True(t, generates, "an emitter handler makes a generator")
		subscribed, held := emits.(plugin.Subscribed)
		assert.True(t, held, "a built plugin declares its gates")
		assert.Equal(t, subscribed.Subscriptions(), []plugin.Subscription{{
			Kind: symbol.KindFunction, Phase: plugin.PhaseGenerate,
		}}, "the record carries the trigger's kind in the generate phase")

		stamps := eidos.NewPlugin("t").
			Handle(eidos.OnFunction(func(m *eidos.FunctionMatch, st *eidos.Stamper) error {
				return nil
			})).
			Build()
		_, annotates := stamps.(plugin.Annotator)
		assert.True(t, annotates, "a stamper handler makes an annotator")
		_, alsoGenerates := stamps.(plugin.Generator)
		assert.False(t, alsoGenerates, "and only an annotator")
	})

	t.Run("Method", func(t *testing.T) {
		t.Parallel()

		emits := eidos.NewPlugin("t").
			Handle(eidos.OnMethod(func(m *eidos.MethodMatch, e *eidos.Emitter) error {
				return nil
			})).
			Build()
		_, generates := emits.(plugin.Generator)
		assert.True(t, generates, "an emitter handler makes a generator")
		subscribed, held := emits.(plugin.Subscribed)
		assert.True(t, held, "a built plugin declares its gates")
		assert.Equal(t, subscribed.Subscriptions(), []plugin.Subscription{{
			Kind: symbol.KindMethod, Phase: plugin.PhaseGenerate,
		}}, "the record carries the trigger's kind in the generate phase")

		stamps := eidos.NewPlugin("t").
			Handle(eidos.OnMethod(func(m *eidos.MethodMatch, st *eidos.Stamper) error {
				return nil
			})).
			Build()
		_, annotates := stamps.(plugin.Annotator)
		assert.True(t, annotates, "a stamper handler makes an annotator")
		_, alsoGenerates := stamps.(plugin.Generator)
		assert.False(t, alsoGenerates, "and only an annotator")
	})

	t.Run("Enum", func(t *testing.T) {
		t.Parallel()

		emits := eidos.NewPlugin("t").
			Handle(eidos.OnEnum(func(m *eidos.EnumMatch, e *eidos.Emitter) error {
				return nil
			})).
			Build()
		_, generates := emits.(plugin.Generator)
		assert.True(t, generates, "an emitter handler makes a generator")
		subscribed, held := emits.(plugin.Subscribed)
		assert.True(t, held, "a built plugin declares its gates")
		assert.Equal(t, subscribed.Subscriptions(), []plugin.Subscription{{
			Kind: symbol.KindEnum, Phase: plugin.PhaseGenerate,
		}}, "the record carries the trigger's kind in the generate phase")

		stamps := eidos.NewPlugin("t").
			Handle(eidos.OnEnum(func(m *eidos.EnumMatch, st *eidos.Stamper) error {
				return nil
			})).
			Build()
		_, annotates := stamps.(plugin.Annotator)
		assert.True(t, annotates, "a stamper handler makes an annotator")
		_, alsoGenerates := stamps.(plugin.Generator)
		assert.False(t, alsoGenerates, "and only an annotator")
	})

	t.Run("Sum", func(t *testing.T) {
		t.Parallel()

		emits := eidos.NewPlugin("t").
			Handle(eidos.OnSum(func(m *eidos.SumMatch, e *eidos.Emitter) error {
				return nil
			})).
			Build()
		_, generates := emits.(plugin.Generator)
		assert.True(t, generates, "an emitter handler makes a generator")
		subscribed, held := emits.(plugin.Subscribed)
		assert.True(t, held, "a built plugin declares its gates")
		assert.Equal(t, subscribed.Subscriptions(), []plugin.Subscription{{
			Kind: symbol.KindSum, Phase: plugin.PhaseGenerate,
		}}, "the record carries the trigger's kind in the generate phase")

		stamps := eidos.NewPlugin("t").
			Handle(eidos.OnSum(func(m *eidos.SumMatch, st *eidos.Stamper) error {
				return nil
			})).
			Build()
		_, annotates := stamps.(plugin.Annotator)
		assert.True(t, annotates, "a stamper handler makes an annotator")
		_, alsoGenerates := stamps.(plugin.Generator)
		assert.False(t, alsoGenerates, "and only an annotator")
	})

	t.Run("Field", func(t *testing.T) {
		t.Parallel()

		emits := eidos.NewPlugin("t").
			Handle(eidos.OnField(func(m *eidos.FieldMatch, e *eidos.Emitter) error {
				return nil
			})).
			Build()
		_, generates := emits.(plugin.Generator)
		assert.True(t, generates, "an emitter handler makes a generator")
		subscribed, held := emits.(plugin.Subscribed)
		assert.True(t, held, "a built plugin declares its gates")
		assert.Equal(t, subscribed.Subscriptions(), []plugin.Subscription{{
			Kind: symbol.KindField, Phase: plugin.PhaseGenerate,
		}}, "the record carries the trigger's kind in the generate phase")

		stamps := eidos.NewPlugin("t").
			Handle(eidos.OnField(func(m *eidos.FieldMatch, st *eidos.Stamper) error {
				return nil
			})).
			Build()
		_, annotates := stamps.(plugin.Annotator)
		assert.True(t, annotates, "a stamper handler makes an annotator")
		_, alsoGenerates := stamps.(plugin.Generator)
		assert.False(t, alsoGenerates, "and only an annotator")
	})

	t.Run("Variable", func(t *testing.T) {
		t.Parallel()

		emits := eidos.NewPlugin("t").
			Handle(eidos.OnVariable(func(m *eidos.VariableMatch, e *eidos.Emitter) error {
				return nil
			})).
			Build()
		_, generates := emits.(plugin.Generator)
		assert.True(t, generates, "an emitter handler makes a generator")
		subscribed, held := emits.(plugin.Subscribed)
		assert.True(t, held, "a built plugin declares its gates")
		assert.Equal(t, subscribed.Subscriptions(), []plugin.Subscription{{
			Kind: symbol.KindVariable, Phase: plugin.PhaseGenerate,
		}}, "the record carries the trigger's kind in the generate phase")

		stamps := eidos.NewPlugin("t").
			Handle(eidos.OnVariable(func(m *eidos.VariableMatch, st *eidos.Stamper) error {
				return nil
			})).
			Build()
		_, annotates := stamps.(plugin.Annotator)
		assert.True(t, annotates, "a stamper handler makes an annotator")
		_, alsoGenerates := stamps.(plugin.Generator)
		assert.False(t, alsoGenerates, "and only an annotator")
	})

	t.Run("Constant", func(t *testing.T) {
		t.Parallel()

		emits := eidos.NewPlugin("t").
			Handle(eidos.OnConstant(func(m *eidos.ConstantMatch, e *eidos.Emitter) error {
				return nil
			})).
			Build()
		_, generates := emits.(plugin.Generator)
		assert.True(t, generates, "an emitter handler makes a generator")
		subscribed, held := emits.(plugin.Subscribed)
		assert.True(t, held, "a built plugin declares its gates")
		assert.Equal(t, subscribed.Subscriptions(), []plugin.Subscription{{
			Kind: symbol.KindConstant, Phase: plugin.PhaseGenerate,
		}}, "the record carries the trigger's kind in the generate phase")

		stamps := eidos.NewPlugin("t").
			Handle(eidos.OnConstant(func(m *eidos.ConstantMatch, st *eidos.Stamper) error {
				return nil
			})).
			Build()
		_, annotates := stamps.(plugin.Annotator)
		assert.True(t, annotates, "a stamper handler makes an annotator")
		_, alsoGenerates := stamps.(plugin.Generator)
		assert.False(t, alsoGenerates, "and only an annotator")
	})

	t.Run("Struct", func(t *testing.T) {
		t.Parallel()

		emits := eidos.NewPlugin("t").
			Handle(eidos.OnStruct(func(m *eidos.StructMatch, e *eidos.Emitter) error {
				return nil
			})).
			Build()
		_, generates := emits.(plugin.Generator)
		assert.True(t, generates, "an emitter handler makes a generator")
		subscribed, held := emits.(plugin.Subscribed)
		assert.True(t, held, "a built plugin declares its gates")
		assert.Equal(t, subscribed.Subscriptions(), []plugin.Subscription{{
			Kind: symbol.KindStruct, Phase: plugin.PhaseGenerate,
		}}, "the record carries the trigger's kind in the generate phase")

		stamps := eidos.NewPlugin("t").
			Handle(eidos.OnStruct(func(m *eidos.StructMatch, st *eidos.Stamper) error {
				return nil
			})).
			Build()
		_, annotates := stamps.(plugin.Annotator)
		assert.True(t, annotates, "a stamper handler makes an annotator")
		_, alsoGenerates := stamps.(plugin.Generator)
		assert.False(t, alsoGenerates, "and only an annotator")
	})

	t.Run("Interface", func(t *testing.T) {
		t.Parallel()

		emits := eidos.NewPlugin("t").
			Handle(eidos.OnInterface(func(m *eidos.InterfaceMatch, e *eidos.Emitter) error {
				return nil
			})).
			Build()
		_, generates := emits.(plugin.Generator)
		assert.True(t, generates, "an emitter handler makes a generator")
		subscribed, held := emits.(plugin.Subscribed)
		assert.True(t, held, "a built plugin declares its gates")
		assert.Equal(t, subscribed.Subscriptions(), []plugin.Subscription{{
			Kind: symbol.KindInterface, Phase: plugin.PhaseGenerate,
		}}, "the record carries the trigger's kind in the generate phase")

		stamps := eidos.NewPlugin("t").
			Handle(eidos.OnInterface(func(m *eidos.InterfaceMatch, st *eidos.Stamper) error {
				return nil
			})).
			Build()
		_, annotates := stamps.(plugin.Annotator)
		assert.True(t, annotates, "a stamper handler makes an annotator")
		_, alsoGenerates := stamps.(plugin.Generator)
		assert.False(t, alsoGenerates, "and only an annotator")
	})

	t.Run("Alias", func(t *testing.T) {
		t.Parallel()

		emits := eidos.NewPlugin("t").
			Handle(eidos.OnAlias(func(m *eidos.AliasMatch, e *eidos.Emitter) error {
				return nil
			})).
			Build()
		_, generates := emits.(plugin.Generator)
		assert.True(t, generates, "an emitter handler makes a generator")
		subscribed, held := emits.(plugin.Subscribed)
		assert.True(t, held, "a built plugin declares its gates")
		assert.Equal(t, subscribed.Subscriptions(), []plugin.Subscription{{
			Kind: symbol.KindAlias, Phase: plugin.PhaseGenerate,
		}}, "the record carries the trigger's kind in the generate phase")

		stamps := eidos.NewPlugin("t").
			Handle(eidos.OnAlias(func(m *eidos.AliasMatch, st *eidos.Stamper) error {
				return nil
			})).
			Build()
		_, annotates := stamps.(plugin.Annotator)
		assert.True(t, annotates, "a stamper handler makes an annotator")
		_, alsoGenerates := stamps.(plugin.Generator)
		assert.False(t, alsoGenerates, "and only an annotator")
	})
}
