// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/model. DO NOT EDIT.

package eidos

import (
	"go.dokimi.dev/eidos/core/node"
	"go.dokimi.dev/eidos/core/symbol"
)

// FunctionMatch is the OnFunction subject.
type FunctionMatch struct {
	match
	Function *node.Function
}

// OnFunction fires the handler once per subject of its kind in
// scope, or once per gating instance under a Directive wrapper.
// The effect parameter picks the role: an Emitter generates, a
// Stamper annotates.
func OnFunction[E Effect](h func(*FunctionMatch, E) error) Rule {
	return Rule{leaf: &leaf{
		kind:  symbol.KindFunction,
		phase: phaseOf[E](),
		invoke: func(inv invocation) error {
			decl, held := inv.value.(*node.Function)
			if !held {
				return nil
			}
			m, reused := inv.scratch().(*FunctionMatch)
			if !reused {
				m = &FunctionMatch{}
				inv.keep(m)
			}
			m.match = newMatch(inv)
			m.Function = decl
			return h(m, effectFor[E](inv.rs, &m.match))
		},
	}}
}

// MethodMatch is the OnMethod subject.
type MethodMatch struct {
	match
	Method *node.Method
}

// OnMethod fires the handler once per subject of its kind in
// scope, or once per gating instance under a Directive wrapper.
// The effect parameter picks the role: an Emitter generates, a
// Stamper annotates.
func OnMethod[E Effect](h func(*MethodMatch, E) error) Rule {
	return Rule{leaf: &leaf{
		kind:  symbol.KindMethod,
		phase: phaseOf[E](),
		invoke: func(inv invocation) error {
			decl, held := inv.value.(*node.Method)
			if !held {
				return nil
			}
			m, reused := inv.scratch().(*MethodMatch)
			if !reused {
				m = &MethodMatch{}
				inv.keep(m)
			}
			m.match = newMatch(inv)
			m.Method = decl
			return h(m, effectFor[E](inv.rs, &m.match))
		},
	}}
}

// ParamMatch is the OnParam subject.
type ParamMatch struct {
	match
	Param *node.Param
}

// OnParam fires the handler once per subject of its kind in
// scope, or once per gating instance under a Directive wrapper.
// The effect parameter picks the role: an Emitter generates, a
// Stamper annotates.
func OnParam[E Effect](h func(*ParamMatch, E) error) Rule {
	return Rule{leaf: &leaf{
		kind:  symbol.KindParam,
		phase: phaseOf[E](),
		invoke: func(inv invocation) error {
			decl, held := inv.value.(*node.Param)
			if !held {
				return nil
			}
			m, reused := inv.scratch().(*ParamMatch)
			if !reused {
				m = &ParamMatch{}
				inv.keep(m)
			}
			m.match = newMatch(inv)
			m.Param = decl
			return h(m, effectFor[E](inv.rs, &m.match))
		},
	}}
}

// ReturnMatch is the OnReturn subject.
type ReturnMatch struct {
	match
	Return *node.Return
}

// OnReturn fires the handler once per subject of its kind in
// scope, or once per gating instance under a Directive wrapper.
// The effect parameter picks the role: an Emitter generates, a
// Stamper annotates.
func OnReturn[E Effect](h func(*ReturnMatch, E) error) Rule {
	return Rule{leaf: &leaf{
		kind:  symbol.KindReturn,
		phase: phaseOf[E](),
		invoke: func(inv invocation) error {
			decl, held := inv.value.(*node.Return)
			if !held {
				return nil
			}
			m, reused := inv.scratch().(*ReturnMatch)
			if !reused {
				m = &ReturnMatch{}
				inv.keep(m)
			}
			m.match = newMatch(inv)
			m.Return = decl
			return h(m, effectFor[E](inv.rs, &m.match))
		},
	}}
}

// EnumMatch is the OnEnum subject.
type EnumMatch struct {
	match
	Enum *node.Enum
}

// OnEnum fires the handler once per subject of its kind in
// scope, or once per gating instance under a Directive wrapper.
// The effect parameter picks the role: an Emitter generates, a
// Stamper annotates.
func OnEnum[E Effect](h func(*EnumMatch, E) error) Rule {
	return Rule{leaf: &leaf{
		kind:  symbol.KindEnum,
		phase: phaseOf[E](),
		invoke: func(inv invocation) error {
			decl, held := inv.value.(*node.Enum)
			if !held {
				return nil
			}
			m, reused := inv.scratch().(*EnumMatch)
			if !reused {
				m = &EnumMatch{}
				inv.keep(m)
			}
			m.match = newMatch(inv)
			m.Enum = decl
			return h(m, effectFor[E](inv.rs, &m.match))
		},
	}}
}

// SumMatch is the OnSum subject.
type SumMatch struct {
	match
	Sum *node.Sum
}

// OnSum fires the handler once per subject of its kind in
// scope, or once per gating instance under a Directive wrapper.
// The effect parameter picks the role: an Emitter generates, a
// Stamper annotates.
func OnSum[E Effect](h func(*SumMatch, E) error) Rule {
	return Rule{leaf: &leaf{
		kind:  symbol.KindSum,
		phase: phaseOf[E](),
		invoke: func(inv invocation) error {
			decl, held := inv.value.(*node.Sum)
			if !held {
				return nil
			}
			m, reused := inv.scratch().(*SumMatch)
			if !reused {
				m = &SumMatch{}
				inv.keep(m)
			}
			m.match = newMatch(inv)
			m.Sum = decl
			return h(m, effectFor[E](inv.rs, &m.match))
		},
	}}
}

// FieldMatch is the OnField subject.
type FieldMatch struct {
	match
	Field *node.Field
}

// OnField fires the handler once per subject of its kind in
// scope, or once per gating instance under a Directive wrapper.
// The effect parameter picks the role: an Emitter generates, a
// Stamper annotates.
func OnField[E Effect](h func(*FieldMatch, E) error) Rule {
	return Rule{leaf: &leaf{
		kind:  symbol.KindField,
		phase: phaseOf[E](),
		invoke: func(inv invocation) error {
			decl, held := inv.value.(*node.Field)
			if !held {
				return nil
			}
			m, reused := inv.scratch().(*FieldMatch)
			if !reused {
				m = &FieldMatch{}
				inv.keep(m)
			}
			m.match = newMatch(inv)
			m.Field = decl
			return h(m, effectFor[E](inv.rs, &m.match))
		},
	}}
}

// VariableMatch is the OnVariable subject.
type VariableMatch struct {
	match
	Variable *node.Variable
}

// OnVariable fires the handler once per subject of its kind in
// scope, or once per gating instance under a Directive wrapper.
// The effect parameter picks the role: an Emitter generates, a
// Stamper annotates.
func OnVariable[E Effect](h func(*VariableMatch, E) error) Rule {
	return Rule{leaf: &leaf{
		kind:  symbol.KindVariable,
		phase: phaseOf[E](),
		invoke: func(inv invocation) error {
			decl, held := inv.value.(*node.Variable)
			if !held {
				return nil
			}
			m, reused := inv.scratch().(*VariableMatch)
			if !reused {
				m = &VariableMatch{}
				inv.keep(m)
			}
			m.match = newMatch(inv)
			m.Variable = decl
			return h(m, effectFor[E](inv.rs, &m.match))
		},
	}}
}

// ConstantMatch is the OnConstant subject.
type ConstantMatch struct {
	match
	Constant *node.Constant
}

// OnConstant fires the handler once per subject of its kind in
// scope, or once per gating instance under a Directive wrapper.
// The effect parameter picks the role: an Emitter generates, a
// Stamper annotates.
func OnConstant[E Effect](h func(*ConstantMatch, E) error) Rule {
	return Rule{leaf: &leaf{
		kind:  symbol.KindConstant,
		phase: phaseOf[E](),
		invoke: func(inv invocation) error {
			decl, held := inv.value.(*node.Constant)
			if !held {
				return nil
			}
			m, reused := inv.scratch().(*ConstantMatch)
			if !reused {
				m = &ConstantMatch{}
				inv.keep(m)
			}
			m.match = newMatch(inv)
			m.Constant = decl
			return h(m, effectFor[E](inv.rs, &m.match))
		},
	}}
}

// StructMatch is the OnStruct subject.
type StructMatch struct {
	match
	Struct *node.Struct
}

// OnStruct fires the handler once per subject of its kind in
// scope, or once per gating instance under a Directive wrapper.
// The effect parameter picks the role: an Emitter generates, a
// Stamper annotates.
func OnStruct[E Effect](h func(*StructMatch, E) error) Rule {
	return Rule{leaf: &leaf{
		kind:  symbol.KindStruct,
		phase: phaseOf[E](),
		invoke: func(inv invocation) error {
			decl, held := inv.value.(*node.Struct)
			if !held {
				return nil
			}
			m, reused := inv.scratch().(*StructMatch)
			if !reused {
				m = &StructMatch{}
				inv.keep(m)
			}
			m.match = newMatch(inv)
			m.Struct = decl
			return h(m, effectFor[E](inv.rs, &m.match))
		},
	}}
}

// InterfaceMatch is the OnInterface subject.
type InterfaceMatch struct {
	match
	Interface *node.Interface
}

// OnInterface fires the handler once per subject of its kind in
// scope, or once per gating instance under a Directive wrapper.
// The effect parameter picks the role: an Emitter generates, a
// Stamper annotates.
func OnInterface[E Effect](h func(*InterfaceMatch, E) error) Rule {
	return Rule{leaf: &leaf{
		kind:  symbol.KindInterface,
		phase: phaseOf[E](),
		invoke: func(inv invocation) error {
			decl, held := inv.value.(*node.Interface)
			if !held {
				return nil
			}
			m, reused := inv.scratch().(*InterfaceMatch)
			if !reused {
				m = &InterfaceMatch{}
				inv.keep(m)
			}
			m.match = newMatch(inv)
			m.Interface = decl
			return h(m, effectFor[E](inv.rs, &m.match))
		},
	}}
}

// AliasMatch is the OnAlias subject.
type AliasMatch struct {
	match
	Alias *node.Alias
}

// OnAlias fires the handler once per subject of its kind in
// scope, or once per gating instance under a Directive wrapper.
// The effect parameter picks the role: an Emitter generates, a
// Stamper annotates.
func OnAlias[E Effect](h func(*AliasMatch, E) error) Rule {
	return Rule{leaf: &leaf{
		kind:  symbol.KindAlias,
		phase: phaseOf[E](),
		invoke: func(inv invocation) error {
			decl, held := inv.value.(*node.Alias)
			if !held {
				return nil
			}
			m, reused := inv.scratch().(*AliasMatch)
			if !reused {
				m = &AliasMatch{}
				inv.keep(m)
			}
			m.match = newMatch(inv)
			m.Alias = decl
			return h(m, effectFor[E](inv.rs, &m.match))
		},
	}}
}
