// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/facade. DO NOT EDIT.

// Package frontendtest re-exports [go.dokimi.dev/eidos/core/frontend/frontendtest]:
// one alias, constant or wrapper per exported symbol, so plugin
// code speaks the facade's paths while the kernel package stays
// the single home of every definition.
//
// # Dependency position
//
// sdk/frontendtest imports core/frontend/frontendtest,
// sdk/directive, sdk/meta, go.dokimi.dev/assert and the Go stdlib.
package frontendtest

import (
	"testing"

	"go.dokimi.dev/assert"

	core "go.dokimi.dev/eidos/core/frontend/frontendtest"
	"go.dokimi.dev/eidos/sdk/directive"
	"go.dokimi.dev/eidos/sdk/meta"
)

// AssertDeterministicParse loads the fixture twice and compares
// what each load recorded: the graphs byte for byte, the attached
// directives and classification stamps, and the findings in report
// order. Reparsing unchanged files yields the same identities, or
// diff-by-identity later stands on sand.
func AssertDeterministicParse(tb assert.TB, setup Setup) {
	core.AssertDeterministicParse(tb, setup)
}

// AssertPositionedDiagnostics holds every finding to its address:
// a finding without a position or an origin is a defect in the
// frontend that reported it.
func AssertPositionedDiagnostics(tb assert.TB, setup Setup) {
	core.AssertPositionedDiagnostics(tb, setup)
}

// AssertClassified holds the claim to account: every selected file
// either declares into the graph or has a finding naming it, so
// nothing drops in silence. A fixture declaring classification keys
// is stamped by the load, and the recorded stamps apply cleanly
// under those keys, the way the workspace run applies them. A load
// that stamps under a fixture declaring no keys fails, because
// nothing could apply its stamps.
func AssertClassified(tb assert.TB, setup Setup) {
	core.AssertClassified(tb, setup)
}

// AssertOwnedExcluded holds the one exclusion the kernel owns: a
// selected file framed under the load's own brand is the
// workspace's output and never reaches a unit, while the same file
// framed under another brand is ordinary input and loads. The
// check stamps the copies itself through the language's own
// comment syntax, so a fixture states nothing.
func AssertOwnedExcluded(tb assert.TB, setup Setup) {
	core.AssertOwnedExcluded(tb, setup)
}

// AssertFingerprinted holds the unit keys honest: stable across
// two identical loads, and changed by each folded part — a read, a
// depth, a declared version, the options, the plugin set. The
// model fingerprint is a compiled constant no test can vary. A
// unit missing from the load a key is compared against fails the
// comparison rather than differing from nothing.
func AssertFingerprinted(tb assert.TB, setup Setup) {
	core.AssertFingerprinted(tb, setup)
}

// AssertJailedReads proves the one door from the frontend's side:
// every unit reads its members through the unit, so a unit's key
// moves when its members' bytes move. A frontend reading its
// members any other way — the operating system's filesystem, a
// cache it keeps across loads — keys a unit by bytes it never read
// through the door, and a cache keyed that way serves a stale
// graph. The check loads a copy of the fixture twice, then a copy
// whose every selected file gained a line break, and requires every
// unit of the second load to key differently in the third. The
// kernel's side of the door, a read outside the unit refusing and
// naming the path, is the plugin package's own contract.
func AssertJailedReads(tb assert.TB, setup Setup) {
	core.AssertJailedReads(tb, setup)
}

// AssertSignatureDepth loads the fixture once full and once under
// its signature roots: the shallow graph's identities are a subset
// of the full graph's, under the same spellings, and the report
// says which units loaded shallow.
func AssertSignatureDepth(tb assert.TB, setup Setup) {
	core.AssertSignatureDepth(tb, setup)
}

// AssertAttachedDirectives validates every attached instance under
// the fixture's schemas at the suite's stand-in freeze, after the
// resolution step — the same point the workspace validates at. It
// also holds the comment pipeline to its exclusion: a carrier line
// left in a declaration's documentation, with or without the
// carrier mark, is a strip the frontend missed. What it does not
// check is the carrier marker itself, which is each kit's own
// convention.
func AssertAttachedDirectives(tb assert.TB, setup Setup) {
	core.AssertAttachedDirectives(tb, setup)
}

// AssertLinked checks the resolution step's outcome: at least one
// in-graph spelling resolves, every resolved reference targets a
// declaration in the graph, every reference left unresolved — a
// builtin, an external — keeps its spelling, a multi-package
// fixture resolves across its packages, and the tracked reader
// joins the same targets afterwards.
func AssertLinked(tb assert.TB, setup Setup) {
	core.AssertLinked(tb, setup)
}

// ScriptedLang is the language of every scripted declaration.
const ScriptedLang = core.ScriptedLang

// ScriptedID is the name the scripted frontend declares, and the
// origin of every finding it reports.
const ScriptedID = core.ScriptedID

// ScriptedTestKey is the classification key the scripted stamps
// write.
const ScriptedTestKey = core.ScriptedTestKey

// ScriptedBadFile is the scripted frontend's one finding: a file
// with no package line declares nothing.
var ScriptedBadFile = core.ScriptedBadFile

// ScriptedOptions is the scripted frontend's declared
// configuration.
type ScriptedOptions = core.ScriptedOptions

// Scripted is the language the suite proves itself on and any
// consumer can drive. Its grammar is small, and it exercises every
// load phase: packages, bindings, cross-package references, type
// parameters, members, directives, classification stamps and a
// signature-sensitive declaration. One statement per line:
//
//	package PATH          the file's package path
//	import ALIAS PATH...  bind an alias to one or more packages
//	type NAME REF...      a struct, fields f0..fn typed by the refs
//	typeparam NAME        a type parameter on the last type
//	method NAME REF...    a method on the last type, params by ref
//	const name            a constant; skipped at signature depth
//	+NAME ARGS            a directive on the last type
//	// TEXT               a comment, split by the kernel: its
//	                      documentation and its +marked lines
//	                      attach to the next type, and a tool:name
//	                      line lowers as an annotation; above the
//	                      package line it is the file's header and
//	                      lowers to nothing
//	stamp KEY VALUE       a classification stamp on the file
//	pkgnote NAME ARGS     a directive on the package node itself
//
// It partitions by directory, with one shared input when the tree
// has mod.zz at its root. The fields are open so a test can rename,
// re-version, re-claim or re-tag it.
type Scripted = core.Scripted

// NewScripted returns the scripted frontend under its usual claim.
func NewScripted() *Scripted {
	return core.NewScripted()
}

// ScriptedKeys registers the classification key the scripted stamps write,
// in the shape a suite fixture declares its keys.
func ScriptedKeys(r *meta.Registry) error {
	return core.ScriptedKeys(r)
}

// ScriptedSchemas declares the one directive the scripted carriers write,
// in the shape a suite fixture declares its schemas.
func ScriptedSchemas() []directive.Schema {
	return core.ScriptedSchemas()
}

// Fixture is what a frontend brings to the suite: the tree the
// selection claims from, and what the checks that need more can
// read. A field left empty skips the checks that need it, and the
// suite states each skip.
type Fixture = core.Fixture

// Setup builds the frontend under test and its fixture, fresh per
// check.
type Setup = core.Setup

// RunFrontendSuite holds a frontend to the read side's contract:
// deterministic parses, positioned findings, no silently dropped
// file, the workspace's own outputs refused, honest unit keys, the
// jailed read, signature depth, validated directive attachments
// and resolved references. It
// drives the SPI, so a kit-built frontend and a hand-rolled one
// meet the same checks.
//
// One survey load up front finds what the fixture cannot state:
// classification keys, a unit loading full beside its signature
// roots, a second package. The suite states each such skip as a
// skipped subtest of its own.
func RunFrontendSuite(t *testing.T, setup Setup) {
	core.RunFrontendSuite(t, setup)
}
