// Copyright Dokimasia B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/facade. DO NOT EDIT.

package jsonschema_test

import (
	"reflect"
	"testing"

	"go.dokimi.dev/assert"

	core "go.dokimi.dev/eidos/core/jsonschema"
	"go.dokimi.dev/eidos/sdk/jsonschema"
)

// The facade re-exports go.dokimi.dev/eidos/core/jsonschema: every type is the kernel's
// own type, every constant and variable equals the kernel's value,
// and every wrapper has the kernel function's signature.
func TestFacade(t *testing.T) {
	t.Parallel()

	t.Run("Schemer", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[jsonschema.Schemer](), reflect.TypeFor[core.Schemer](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Of", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(jsonschema.Of), reflect.TypeOf(core.Of), "the wrapper has the kernel function's signature")
		})
	})
}
