// Code generated by shapegen. DO NOT EDIT.
// shapegen:plugin registry

package catalog

import (
	"go.dokimi.dev/eidos/plugin/shape"
	"go.dokimi.dev/eidos/plugin/shape/detectors"
)

// Detections returns every detected shape and its detector, in the order of
// precedence. A shape comes before every shape that yields to it. Each call
// returns a new slice.
func Detections() []shape.Detection {
	return []shape.Detection{
		{Shape: shape.BatchReader, Detect: detectors.BatchReader},
		{Shape: shape.Closer, Detect: detectors.Closer},
		{Shape: shape.CompositeWriter, Detect: detectors.CompositeWriter},
		{Shape: shape.Deleter, Detect: detectors.Deleter},
		{Shape: shape.Lifecycle, Detect: detectors.Lifecycle},
		{Shape: shape.Lookup, Detect: detectors.Lookup},
		{Shape: shape.MultiAggregator, Detect: detectors.MultiAggregator},
		{Shape: shape.MultiArgWriter, Detect: detectors.MultiArgWriter},
		{Shape: shape.MultiReader, Detect: detectors.MultiReader},
		{Shape: shape.Mutator, Detect: detectors.Mutator},
		{Shape: shape.PoisonAccessor, Detect: detectors.PoisonAccessor},
		{Shape: shape.Predicate, Detect: detectors.Predicate},
		{Shape: shape.ReaderWithBool, Detect: detectors.ReaderWithBool},
		{Shape: shape.StreamConsumer, Detect: detectors.StreamConsumer},
		{Shape: shape.AnsweringWriter, Detect: detectors.AnsweringWriter},
		{Shape: shape.Reader, Detect: detectors.Reader},
		{Shape: shape.StreamReader, Detect: detectors.StreamReader},
		{Shape: shape.Computation, Detect: detectors.Computation},
		{Shape: shape.Aggregator, Detect: detectors.Aggregator},
		{Shape: shape.PointerReader, Detect: detectors.PointerReader},
		{Shape: shape.ReaderNoError, Detect: detectors.ReaderNoError},
		{Shape: shape.VoidLifecycle, Detect: detectors.VoidLifecycle},
		{Shape: shape.Writer, Detect: detectors.Writer},
	}
}
// shapegen:provenance sha256:cb67a236b14c7376607ae52f8fc75a501aac933cec77021ec25fef7f75ae74bd
