// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/facade. DO NOT EDIT.

package meta_test

import (
	"reflect"
	"testing"

	"go.dokimi.dev/assert"

	core "go.dokimi.dev/eidos/core/meta"
	"go.dokimi.dev/eidos/sdk/meta"
)

// The facade re-exports go.dokimi.dev/eidos/core/meta: every type is the kernel's
// own type, every constant and variable equals the kernel's value,
// and every wrapper has the kernel function's signature.
func TestFacade(t *testing.T) {
	t.Parallel()

	t.Run("Authority", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[meta.Authority](), reflect.TypeFor[core.Authority](), "the facade aliases the kernel's type")
		})
	})

	t.Run("AuthorityPlugin", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, meta.AuthorityPlugin, core.AuthorityPlugin, "the facade re-declares the kernel's value")
		})
	})

	t.Run("AuthorityDirective", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, meta.AuthorityDirective, core.AuthorityDirective, "the facade re-declares the kernel's value")
		})
	})

	t.Run("AuthorityManual", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, meta.AuthorityManual, core.AuthorityManual, "the facade re-declares the kernel's value")
		})
	})

	t.Run("Order", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[meta.Order](), reflect.TypeFor[core.Order](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Claim", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[meta.Claim](), reflect.TypeFor[core.Claim](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Read", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[meta.Read](), reflect.TypeFor[core.Read](), "the facade aliases the kernel's type")
		})
	})

	t.Run("FactRef", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[meta.FactRef](), reflect.TypeFor[core.FactRef](), "the facade aliases the kernel's type")
		})
	})

	t.Run("RefusedStamp", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, meta.RefusedStamp, core.RefusedStamp, "the facade re-declares the kernel's value")
		})
	})

	t.Run("Facts", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[meta.Facts](), reflect.TypeFor[core.Facts](), "the facade aliases the kernel's type")
		})
	})

	t.Run("NewFacts", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(meta.NewFacts), reflect.TypeOf(core.NewFacts), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("Recorder", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[meta.Recorder](), reflect.TypeFor[core.Recorder](), "the facade aliases the kernel's type")
		})
	})

	t.Run("KernelNamespace", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, meta.KernelNamespace, core.KernelNamespace, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KernelOwner", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, meta.KernelOwner, core.KernelOwner, "the facade re-declares the kernel's value")
		})
	})

	t.Run("ModuleKey", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, meta.ModuleKey, core.ModuleKey, "the facade re-declares the kernel's value")
		})
	})

	t.Run("ModuleRootKey", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, meta.ModuleRootKey, core.ModuleRootKey, "the facade re-declares the kernel's value")
		})
	})

	t.Run("SampleKey", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, meta.SampleKey, core.SampleKey, "the facade re-declares the kernel's value")
		})
	})

	t.Run("AlternateKey", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, meta.AlternateKey, core.AlternateKey, "the facade re-declares the kernel's value")
		})
	})

	t.Run("WitnessKey", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, meta.WitnessKey, core.WitnessKey, "the facade re-declares the kernel's value")
		})
	})

	t.Run("KernelKeys", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[meta.KernelKeys](), reflect.TypeFor[core.KernelKeys](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Kernel", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(meta.Kernel), reflect.TypeOf(core.Kernel), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("KeyName", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[meta.KeyName](), reflect.TypeFor[core.KeyName](), "the facade aliases the kernel's type")
		})
	})

	t.Run("KeyID", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[meta.KeyID](), reflect.TypeFor[core.KeyID](), "the facade aliases the kernel's type")
		})
	})

	t.Run("GroupName", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[meta.GroupName](), reflect.TypeFor[core.GroupName](), "the facade aliases the kernel's type")
		})
	})

	t.Run("ClaimView", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[meta.ClaimView](), reflect.TypeFor[core.ClaimView](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Registry", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[meta.Registry](), reflect.TypeFor[core.Registry](), "the facade aliases the kernel's type")
		})
	})

	t.Run("NewRegistry", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(meta.NewRegistry), reflect.TypeOf(core.NewRegistry), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("KeySpec", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[meta.KeySpec](), reflect.TypeFor[core.KeySpec](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Completeness", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[meta.Completeness](), reflect.TypeFor[core.Completeness](), "the facade aliases the kernel's type")
		})
	})

	t.Run("BagSource", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[meta.BagSource](), reflect.TypeFor[core.BagSource](), "the facade aliases the kernel's type")
		})
	})

	t.Run("StoredClaim", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[meta.StoredClaim](), reflect.TypeFor[core.StoredClaim](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Restore", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(meta.Restore), reflect.TypeOf(core.Restore), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("RawStamp", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[meta.RawStamp](), reflect.TypeFor[core.RawStamp](), "the facade aliases the kernel's type")
		})
	})
}
