// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: MIT

// Code generated by internal/gen/facade. DO NOT EDIT.

// Package meta re-exports [go.dokimi.dev/eidos/core/meta]:
// one alias, constant or wrapper per exported symbol, so plugin
// code speaks the facade's paths while the kernel package stays
// the single home of every definition.
//
// # Dependency position
//
// sdk/meta imports core/meta and sdk/symbol.
package meta

import (
	core "go.dokimi.dev/eidos/core/meta"
	"go.dokimi.dev/eidos/sdk/symbol"
)

// Authority orders who a write speaks for. A human override at the
// source declaration beats any inference, whatever order the
// plugins ran in. Manual is reserved for consumer tooling; nothing
// in a normal run writes at it.
//
// The zero value is [AuthorityPlugin]: a claim that returned no
// authority speaks with the least.
type Authority = core.Authority

const (
	// AuthorityPlugin is an inference: a fact a plugin stamped.
	AuthorityPlugin = core.AuthorityPlugin
	// AuthorityDirective is a human's write at the source
	// declaration, a drop included.
	AuthorityDirective = core.AuthorityDirective
	// AuthorityManual is consumer tooling: a migration or a fix-it
	// script that outranks even the directives it rewrites.
	AuthorityManual = core.AuthorityManual
)

// Claim is one write's envelope: the rank that arbitrates it and
// the provenance that explains it.
type Claim = core.Claim

// Read is one recorded read: a declaration read when Key is empty,
// a fact read at (subject, key) otherwise.
type Read = core.Read

// Facts is the run's stamped facts: one bag per subject.
//
// Facts is safe for concurrent use and serializes writes per bag,
// so two annotators stamping two subjects do not contend, and
// readers of one bag share its lock. Rank decides every winner, so
// a parallel run returns what a serial one does, whatever order the
// writes arrived.
type Facts = core.Facts

// NewFacts returns an empty fact store reading specs from r.
// Registration completes before the first write; the store
// snapshots what it needs and never locks the registry.
func NewFacts(r *Registry) *Facts {
	return core.NewFacts(r)
}

// Stamp records one claim of v under k.
//
// It refuses a zero key, a subject kind the key does not admit, and
// a false boolean — absence is the negative, so false is never
// stamped and deletion stays load-bearing. A claim identical to one
// already held, same rank source and equal value, changes nothing.
// Values compare per vocabulary term; slices compare element-wise
// and are copied in.
func Stamp[T FactValue](f *Facts, k Key[T], v T, c Claim) error {
	return core.Stamp[T](f, k, v, c)
}

// Get returns the winning value, untracked, and false where the
// winner is a drop or nothing was stamped. Slice values are copied
// out, so a caller cannot reach into a bag.
func Get[T FactValue](f *Facts, id symbol.Identity, k Key[T]) (T, bool) {
	return core.Get[T](f, id, k)
}

// Fact returns what [Get] does and records the read at
// (subject, key) into rec. A miss records too: the reader asked, so
// it runs again when the fact appears. It is the read every plugin
// makes; Get is the kernel's own untracked path.
func Fact[T FactValue](f *Facts, rec Recorder, id symbol.Identity, k Key[T]) (T, bool) {
	return core.Fact[T](f, rec, id, k)
}

// Recorder records fact reads. The store's read set implements it,
// so one artifact's declaration reads and fact reads arrive in one
// set.
type Recorder = core.Recorder

// KeyName is a key's boundary spelling: dotted segments with the
// owning namespace first, as in "shape.role". It appears at the
// boundary — a directive parameter, an attribution argument — and
// resolves against the registry. Code holds the typed [Key].
type KeyName = core.KeyName

// KeyID is the dense form gate tuples and indexes hold. It is
// assigned at registration and belongs to one composition: nothing
// durable stores it, because codecs and the sealed state carry
// names. The zero KeyID names no key.
type KeyID = core.KeyID

// FactValue is the closed value vocabulary; nothing else registers.
// A fact that needs structure becomes flat keys under a fact group,
// and a fact that names a declaration carries an identity rather
// than a string.
type FactValue = core.FactValue

// Key is the typed handle registration returns. Reads, writes and
// gate predicates all go through it, so the value type is checked
// where the code compiles rather than where the run fails.
//
// The zero Key names nothing: every handle comes from [Register].
type Key[T FactValue] = core.Key[T]

// GroupName names a fact group: a bundle a writer declares, such as
// every key its classification stamps. The name is public API and
// the membership is the writer's to grow.
type GroupName = core.GroupName

// ClaimView is one claim as the record shows it.
type ClaimView = core.ClaimView

// Registry holds every registered namespace, key and group.
//
// A Registry is not safe for concurrent use. Registration happens
// while the workspace composes, which is single-threaded, and
// completes before the first fact is written; [Facts] reads it
// without locking on that contract.
type Registry = core.Registry

// NewRegistry returns a registry holding nothing.
func NewRegistry() *Registry {
	return core.NewRegistry()
}

// KeySpec is what a registration declares.
type KeySpec = core.KeySpec

// Completeness is a coverage promise: the key is stamped on every
// declaration of these kinds by the end of the named phase.
type Completeness = core.Completeness

// Register records a key and returns its typed handle.
//
// It refuses, with an error naming both claimants where two exist: a
// name without a claimed namespace or without a local part, a name
// registered twice, and a spec without documentation. It returns an
// error rather than panicking because composition collects every
// fault in one pass.
func Register[T FactValue](r *Registry, s KeySpec) (Key[T], error) {
	return core.Register[T](r, s)
}
