// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: MIT

// Code generated by internal/gen/model. DO NOT EDIT.

package emit

import (
	"go.dokimi.dev/eidos/core/symbol"
)

// Facts calls f for every stated fact s carries, its own and its
// members', parameters', type parameters' and variants', depth
// first in schema field order. Host is the declaration a fact's
// carrier sits in, nil at the top level, so a caller can judge a
// member's fact under its host. A fact is stated by shape: a bool
// set, a string filled, a shared vocabulary value chosen, a
// reference present, a list holding entries; a callable states
// the several-returns fact when its list holds more than one.
//
// A reference is not a carrier: a type reference states nothing,
// because its spelling belongs to the declaration that mentions
// it.
func Facts(
	s symbol.Symbol,
	f func(host symbol.Symbol, kind symbol.Kind, fact symbol.Fact),
) {
	statedFacts(nil, s, f)
}

// statedFacts carries the enclosing declaration through the
// descent.
func statedFacts(
	host symbol.Symbol,
	s symbol.Symbol,
	f func(host symbol.Symbol, kind symbol.Kind, fact symbol.Fact),
) {
	switch x := s.(type) {
	case *Function:
		if x.Visibility != 0 {
			f(host, symbol.KindFunction, symbol.FactVisibility)
		}
		if x.Async {
			f(host, symbol.KindFunction, symbol.FactAsync)
		}
		if len(x.TypeParams) > 0 {
			f(host, symbol.KindFunction, symbol.FactTypeParams)
		}
		if len(x.Returns) > 1 {
			f(host, symbol.KindFunction, symbol.FactMultiReturn)
		}
		if len(x.Throws) > 0 {
			f(host, symbol.KindFunction, symbol.FactThrows)
		}
		if len(x.Annotations) > 0 {
			f(host, symbol.KindFunction, symbol.FactAnnotations)
		}
		for _, child := range x.TypeParams {
			statedFacts(x, child, f)
		}
		for _, child := range x.Params {
			statedFacts(x, child, f)
		}
		for _, child := range x.Returns {
			statedFacts(x, child, f)
		}
	case *Method:
		if x.Visibility != 0 {
			f(host, symbol.KindMethod, symbol.FactVisibility)
		}
		if x.Level != 0 {
			f(host, symbol.KindMethod, symbol.FactLevel)
		}
		if x.Abstract {
			f(host, symbol.KindMethod, symbol.FactAbstract)
		}
		if x.Final {
			f(host, symbol.KindMethod, symbol.FactFinal)
		}
		if x.Override {
			f(host, symbol.KindMethod, symbol.FactOverride)
		}
		if x.HasDefault {
			f(host, symbol.KindMethod, symbol.FactDefaultBody)
		}
		if x.Async {
			f(host, symbol.KindMethod, symbol.FactAsync)
		}
		if len(x.TypeParams) > 0 {
			f(host, symbol.KindMethod, symbol.FactTypeParams)
		}
		if len(x.Returns) > 1 {
			f(host, symbol.KindMethod, symbol.FactMultiReturn)
		}
		if len(x.Throws) > 0 {
			f(host, symbol.KindMethod, symbol.FactThrows)
		}
		if len(x.Annotations) > 0 {
			f(host, symbol.KindMethod, symbol.FactAnnotations)
		}
		if x.Receiver != nil {
			statedFacts(x, x.Receiver, f)
		}
		for _, child := range x.TypeParams {
			statedFacts(x, child, f)
		}
		for _, child := range x.Params {
			statedFacts(x, child, f)
		}
		for _, child := range x.Returns {
			statedFacts(x, child, f)
		}
	case *Param:
		if x.Label != "" {
			f(host, symbol.KindParam, symbol.FactLabel)
		}
		if x.Default != "" {
			f(host, symbol.KindParam, symbol.FactParamDefault)
		}
		if x.Variadic != 0 {
			f(host, symbol.KindParam, symbol.FactVariadic)
		}
		if len(x.Annotations) > 0 {
			f(host, symbol.KindParam, symbol.FactAnnotations)
		}
	case *Return:
		if x.Name != "" {
			f(host, symbol.KindReturn, symbol.FactNamedReturn)
		}
	case *Enum:
		if x.Visibility != 0 {
			f(host, symbol.KindEnum, symbol.FactVisibility)
		}
		if x.Fields.Len() > 0 {
			f(host, symbol.KindEnum, symbol.FactFields)
		}
		if x.Methods.Len() > 0 {
			f(host, symbol.KindEnum, symbol.FactMethods)
		}
		if len(x.Annotations) > 0 {
			f(host, symbol.KindEnum, symbol.FactAnnotations)
		}
		for _, child := range x.Variants.Items() {
			statedFacts(x, child, f)
		}
		for _, child := range x.Fields.Items() {
			statedFacts(x, child, f)
		}
		for _, child := range x.Methods.Items() {
			statedFacts(x, child, f)
		}
	case *EnumVariant:
		if x.Value != "" {
			f(host, symbol.KindEnumVariant, symbol.FactValue)
		}
		if len(x.Annotations) > 0 {
			f(host, symbol.KindEnumVariant, symbol.FactAnnotations)
		}
	case *Sum:
		if x.Visibility != 0 {
			f(host, symbol.KindSum, symbol.FactVisibility)
		}
		if len(x.TypeParams) > 0 {
			f(host, symbol.KindSum, symbol.FactTypeParams)
		}
		if x.Methods.Len() > 0 {
			f(host, symbol.KindSum, symbol.FactMethods)
		}
		if len(x.Annotations) > 0 {
			f(host, symbol.KindSum, symbol.FactAnnotations)
		}
		for _, child := range x.TypeParams {
			statedFacts(x, child, f)
		}
		for _, child := range x.Variants.Items() {
			statedFacts(x, child, f)
		}
		for _, child := range x.Methods.Items() {
			statedFacts(x, child, f)
		}
	case *SumVariant:
		if len(x.Annotations) > 0 {
			f(host, symbol.KindSumVariant, symbol.FactAnnotations)
		}
		for _, child := range x.Fields.Items() {
			statedFacts(x, child, f)
		}
	case *Field:
		if x.Comment != "" {
			f(host, symbol.KindField, symbol.FactComment)
		}
		if x.Visibility != 0 {
			f(host, symbol.KindField, symbol.FactVisibility)
		}
		if x.Level != 0 {
			f(host, symbol.KindField, symbol.FactLevel)
		}
		if x.Mutability != 0 {
			f(host, symbol.KindField, symbol.FactMutability)
		}
		if x.Value != "" {
			f(host, symbol.KindField, symbol.FactValue)
		}
		if x.Tag != "" {
			f(host, symbol.KindField, symbol.FactTag)
		}
		if len(x.Annotations) > 0 {
			f(host, symbol.KindField, symbol.FactAnnotations)
		}
	case *Variable:
		if x.Comment != "" {
			f(host, symbol.KindVariable, symbol.FactComment)
		}
		if x.Visibility != 0 {
			f(host, symbol.KindVariable, symbol.FactVisibility)
		}
		if x.Mutability != 0 {
			f(host, symbol.KindVariable, symbol.FactMutability)
		}
		if x.Value != "" {
			f(host, symbol.KindVariable, symbol.FactValue)
		}
		if len(x.Annotations) > 0 {
			f(host, symbol.KindVariable, symbol.FactAnnotations)
		}
	case *Constant:
		if x.Comment != "" {
			f(host, symbol.KindConstant, symbol.FactComment)
		}
		if x.Visibility != 0 {
			f(host, symbol.KindConstant, symbol.FactVisibility)
		}
		if len(x.Annotations) > 0 {
			f(host, symbol.KindConstant, symbol.FactAnnotations)
		}
	case *Struct:
		if x.Visibility != 0 {
			f(host, symbol.KindStruct, symbol.FactVisibility)
		}
		if x.Level != 0 {
			f(host, symbol.KindStruct, symbol.FactLevel)
		}
		if x.Abstract {
			f(host, symbol.KindStruct, symbol.FactAbstract)
		}
		if x.Final {
			f(host, symbol.KindStruct, symbol.FactFinal)
		}
		if x.Sealed {
			f(host, symbol.KindStruct, symbol.FactSealed)
		}
		if len(x.TypeParams) > 0 {
			f(host, symbol.KindStruct, symbol.FactTypeParams)
		}
		if x.Types.Len() > 0 {
			f(host, symbol.KindStruct, symbol.FactTypes)
		}
		if len(x.Embeds) > 0 {
			f(host, symbol.KindStruct, symbol.FactEmbeds)
		}
		if len(x.Extends) > 0 {
			f(host, symbol.KindStruct, symbol.FactExtends)
		}
		if len(x.Implements) > 0 {
			f(host, symbol.KindStruct, symbol.FactImplements)
		}
		if len(x.Permits) > 0 {
			f(host, symbol.KindStruct, symbol.FactPermits)
		}
		if len(x.Annotations) > 0 {
			f(host, symbol.KindStruct, symbol.FactAnnotations)
		}
		for _, child := range x.TypeParams {
			statedFacts(x, child, f)
		}
		for _, child := range x.Fields.Items() {
			statedFacts(x, child, f)
		}
		for _, child := range x.Methods.Items() {
			statedFacts(x, child, f)
		}
		for _, child := range x.Types.Items() {
			statedFacts(x, child, f)
		}
	case *Interface:
		if x.Visibility != 0 {
			f(host, symbol.KindInterface, symbol.FactVisibility)
		}
		if x.Sealed {
			f(host, symbol.KindInterface, symbol.FactSealed)
		}
		if len(x.TypeParams) > 0 {
			f(host, symbol.KindInterface, symbol.FactTypeParams)
		}
		if x.Fields.Len() > 0 {
			f(host, symbol.KindInterface, symbol.FactProperties)
		}
		if x.Types.Len() > 0 {
			f(host, symbol.KindInterface, symbol.FactTypes)
		}
		if len(x.Embeds) > 0 {
			f(host, symbol.KindInterface, symbol.FactEmbeds)
		}
		if len(x.Extends) > 0 {
			f(host, symbol.KindInterface, symbol.FactExtends)
		}
		if len(x.Permits) > 0 {
			f(host, symbol.KindInterface, symbol.FactPermits)
		}
		if len(x.Annotations) > 0 {
			f(host, symbol.KindInterface, symbol.FactAnnotations)
		}
		for _, child := range x.TypeParams {
			statedFacts(x, child, f)
		}
		for _, child := range x.Fields.Items() {
			statedFacts(x, child, f)
		}
		for _, child := range x.Methods.Items() {
			statedFacts(x, child, f)
		}
		for _, child := range x.Types.Items() {
			statedFacts(x, child, f)
		}
	case *Alias:
		if x.Visibility != 0 {
			f(host, symbol.KindAlias, symbol.FactVisibility)
		}
		if x.Defined {
			f(host, symbol.KindAlias, symbol.FactDefined)
		}
		if len(x.TypeParams) > 0 {
			f(host, symbol.KindAlias, symbol.FactTypeParams)
		}
		if len(x.Annotations) > 0 {
			f(host, symbol.KindAlias, symbol.FactAnnotations)
		}
		for _, child := range x.TypeParams {
			statedFacts(x, child, f)
		}
	case *TypeParam:
		if x.Variance != 0 {
			f(host, symbol.KindTypeParam, symbol.FactVariance)
		}
		if x.Default != nil {
			f(host, symbol.KindTypeParam, symbol.FactTypeParamDefault)
		}
		if x.Const {
			f(host, symbol.KindTypeParam, symbol.FactConstParam)
		}
	}
}

// KindFacts returns the facts each emit kind states directly, in
// schema field order: the surface a coverage declaration is held
// total against, member kinds included. A kind absent from the map
// states no fact of its own.
func KindFacts() map[symbol.Kind][]symbol.Fact {
	return map[symbol.Kind][]symbol.Fact{
		symbol.KindFunction: {
			symbol.FactVisibility,
			symbol.FactAsync,
			symbol.FactTypeParams,
			symbol.FactMultiReturn,
			symbol.FactThrows,
			symbol.FactAnnotations,
		},
		symbol.KindMethod: {
			symbol.FactVisibility,
			symbol.FactLevel,
			symbol.FactAbstract,
			symbol.FactFinal,
			symbol.FactOverride,
			symbol.FactDefaultBody,
			symbol.FactAsync,
			symbol.FactTypeParams,
			symbol.FactMultiReturn,
			symbol.FactThrows,
			symbol.FactAnnotations,
		},
		symbol.KindParam: {
			symbol.FactLabel,
			symbol.FactParamDefault,
			symbol.FactVariadic,
			symbol.FactAnnotations,
		},
		symbol.KindReturn: {
			symbol.FactNamedReturn,
		},
		symbol.KindEnum: {
			symbol.FactVisibility,
			symbol.FactFields,
			symbol.FactMethods,
			symbol.FactAnnotations,
		},
		symbol.KindEnumVariant: {
			symbol.FactValue,
			symbol.FactAnnotations,
		},
		symbol.KindSum: {
			symbol.FactVisibility,
			symbol.FactTypeParams,
			symbol.FactMethods,
			symbol.FactAnnotations,
		},
		symbol.KindSumVariant: {
			symbol.FactAnnotations,
		},
		symbol.KindField: {
			symbol.FactComment,
			symbol.FactVisibility,
			symbol.FactLevel,
			symbol.FactMutability,
			symbol.FactValue,
			symbol.FactTag,
			symbol.FactAnnotations,
		},
		symbol.KindVariable: {
			symbol.FactComment,
			symbol.FactVisibility,
			symbol.FactMutability,
			symbol.FactValue,
			symbol.FactAnnotations,
		},
		symbol.KindConstant: {
			symbol.FactComment,
			symbol.FactVisibility,
			symbol.FactAnnotations,
		},
		symbol.KindStruct: {
			symbol.FactVisibility,
			symbol.FactLevel,
			symbol.FactAbstract,
			symbol.FactFinal,
			symbol.FactSealed,
			symbol.FactTypeParams,
			symbol.FactTypes,
			symbol.FactEmbeds,
			symbol.FactExtends,
			symbol.FactImplements,
			symbol.FactPermits,
			symbol.FactAnnotations,
		},
		symbol.KindInterface: {
			symbol.FactVisibility,
			symbol.FactSealed,
			symbol.FactTypeParams,
			symbol.FactProperties,
			symbol.FactTypes,
			symbol.FactEmbeds,
			symbol.FactExtends,
			symbol.FactPermits,
			symbol.FactAnnotations,
		},
		symbol.KindAlias: {
			symbol.FactVisibility,
			symbol.FactDefined,
			symbol.FactTypeParams,
			symbol.FactAnnotations,
		},
		symbol.KindTypeParam: {
			symbol.FactVariance,
			symbol.FactTypeParamDefault,
			symbol.FactConstParam,
		},
	}
}
