// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/model. DO NOT EDIT.

package emit

import (
	"go.dokimi.dev/eidos/core/symbol"
)

// RespellNames applies f to every declared name s carries, its
// own and its members', parameters', type parameters' and
// variants', depth first in schema field order, writing each
// result back. Host is the declaration a name's carrier sits in,
// nil at the top level, so a caller can group members by their
// host and read the host's kind for the respell hook; a carrier
// without visibility passes the zero value. An empty name is
// skipped, because there is nothing to respell, and the first
// error stops the traversal and returns.
//
// A reference is not a name: a type reference's spelling stays
// untouched, and so does a package's, whose spelling belongs to
// the routing key.
func RespellNames(
	s symbol.Symbol,
	f func(host symbol.Symbol, kind symbol.Kind, v symbol.Visibility, name string) (string, error),
) error {
	return respellNames(nil, s, f)
}

// respellNames carries the enclosing declaration through the
// descent.
func respellNames(
	host symbol.Symbol,
	s symbol.Symbol,
	f func(host symbol.Symbol, kind symbol.Kind, v symbol.Visibility, name string) (string, error),
) error {
	switch x := s.(type) {
	case *Function:
		if x.Name != "" {
			settled, err := f(host, symbol.KindFunction, x.Visibility, x.Name)
			if err != nil {
				return err
			}
			x.Name = settled
		}
		for _, child := range x.TypeParams {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
		for _, child := range x.Params {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
		for _, child := range x.Returns {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
	case *Method:
		if x.Name != "" {
			settled, err := f(host, symbol.KindMethod, x.Visibility, x.Name)
			if err != nil {
				return err
			}
			x.Name = settled
		}
		if x.Receiver != nil {
			if err := respellNames(x, x.Receiver, f); err != nil {
				return err
			}
		}
		for _, child := range x.TypeParams {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
		for _, child := range x.Params {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
		for _, child := range x.Returns {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
	case *Param:
		if x.Name != "" {
			settled, err := f(host, symbol.KindParam, 0, x.Name)
			if err != nil {
				return err
			}
			x.Name = settled
		}
	case *Return:
		if x.Name != "" {
			settled, err := f(host, symbol.KindReturn, 0, x.Name)
			if err != nil {
				return err
			}
			x.Name = settled
		}
	case *Enum:
		if x.Name != "" {
			settled, err := f(host, symbol.KindEnum, x.Visibility, x.Name)
			if err != nil {
				return err
			}
			x.Name = settled
		}
		for _, child := range x.Variants.Items() {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
		for _, child := range x.Fields.Items() {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
		for _, child := range x.Methods.Items() {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
	case *EnumVariant:
		if x.Name != "" {
			settled, err := f(host, symbol.KindEnumVariant, 0, x.Name)
			if err != nil {
				return err
			}
			x.Name = settled
		}
	case *Sum:
		if x.Name != "" {
			settled, err := f(host, symbol.KindSum, x.Visibility, x.Name)
			if err != nil {
				return err
			}
			x.Name = settled
		}
		for _, child := range x.TypeParams {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
		for _, child := range x.Variants.Items() {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
		for _, child := range x.Methods.Items() {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
	case *SumVariant:
		if x.Name != "" {
			settled, err := f(host, symbol.KindSumVariant, 0, x.Name)
			if err != nil {
				return err
			}
			x.Name = settled
		}
		for _, child := range x.Fields.Items() {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
	case *Field:
		if x.Name != "" {
			settled, err := f(host, symbol.KindField, x.Visibility, x.Name)
			if err != nil {
				return err
			}
			x.Name = settled
		}
	case *Variable:
		if x.Name != "" {
			settled, err := f(host, symbol.KindVariable, x.Visibility, x.Name)
			if err != nil {
				return err
			}
			x.Name = settled
		}
	case *Constant:
		if x.Name != "" {
			settled, err := f(host, symbol.KindConstant, x.Visibility, x.Name)
			if err != nil {
				return err
			}
			x.Name = settled
		}
	case *Struct:
		if x.Name != "" {
			settled, err := f(host, symbol.KindStruct, x.Visibility, x.Name)
			if err != nil {
				return err
			}
			x.Name = settled
		}
		for _, child := range x.TypeParams {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
		for _, child := range x.Fields.Items() {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
		for _, child := range x.Methods.Items() {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
		for _, child := range x.Types.Items() {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
	case *Interface:
		if x.Name != "" {
			settled, err := f(host, symbol.KindInterface, x.Visibility, x.Name)
			if err != nil {
				return err
			}
			x.Name = settled
		}
		for _, child := range x.TypeParams {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
		for _, child := range x.Fields.Items() {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
		for _, child := range x.Methods.Items() {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
		for _, child := range x.Types.Items() {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
	case *Alias:
		if x.Name != "" {
			settled, err := f(host, symbol.KindAlias, x.Visibility, x.Name)
			if err != nil {
				return err
			}
			x.Name = settled
		}
		for _, child := range x.TypeParams {
			if err := respellNames(x, child, f); err != nil {
				return err
			}
		}
	case *TypeParam:
		if x.Name != "" {
			settled, err := f(host, symbol.KindTypeParam, 0, x.Name)
			if err != nil {
				return err
			}
			x.Name = settled
		}
	}
	return nil
}
