// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: MIT

// Code generated by internal/gen/model. DO NOT EDIT.

package emit

import (
	"errors"
	"strings"
	"testing"

	"go.dokimi.dev/assert"

	"go.dokimi.dev/eidos/core/symbol"
)

// Every declared name respells through the traversal: each kind's
// own name under its host and visibility, and one name per
// descent field.
func TestRespellNames(t *testing.T) {
	t.Parallel()

	t.Run("Function", func(t *testing.T) {
		t.Parallel()

		subject := &Function{}
		subject.Name = "alpha"
		subject.Visibility = symbol.VisibilityInternal
		subject.TypeParams = append(subject.TypeParams, &TypeParam{Name: "beta"})
		subject.Params = append(subject.Params, &Param{Name: "beta"})
		subject.Returns = append(subject.Returns, &Return{Name: "beta"})
		var hosts []symbol.Kind
		var seen []symbol.Visibility
		err := RespellNames(subject,
			func(host, kind symbol.Kind, v symbol.Visibility, name string) (string, error) {
				hosts = append(hosts, host)
				seen = append(seen, v)
				return strings.ToUpper(name), nil
			})
		assert.NoError(t, err, "the traversal completes")
		assert.Equal(t, len(hosts), 4, "every declared name visits once")
		assert.Equal(t, subject.Name, "ALPHA", "the settled spelling writes back")
		assert.Equal(t, hosts[0], symbol.KindInvalid, "the top level has no host")
		assert.Equal(t, seen[0], symbol.VisibilityInternal,
			"the carrier's visibility reaches the hook")
		for i, h := range hosts {
			if i == 0 {
				continue
			}
			_ = i
			assert.Equal(t, h, symbol.KindFunction,
				"a member's host is its enclosing kind")
		}
		_ = seen
	})

	t.Run("Method", func(t *testing.T) {
		t.Parallel()

		subject := &Method{}
		subject.Name = "alpha"
		subject.Visibility = symbol.VisibilityInternal
		subject.Receiver = &Param{Name: "beta"}
		subject.TypeParams = append(subject.TypeParams, &TypeParam{Name: "beta"})
		subject.Params = append(subject.Params, &Param{Name: "beta"})
		subject.Returns = append(subject.Returns, &Return{Name: "beta"})
		var hosts []symbol.Kind
		var seen []symbol.Visibility
		err := RespellNames(subject,
			func(host, kind symbol.Kind, v symbol.Visibility, name string) (string, error) {
				hosts = append(hosts, host)
				seen = append(seen, v)
				return strings.ToUpper(name), nil
			})
		assert.NoError(t, err, "the traversal completes")
		assert.Equal(t, len(hosts), 5, "every declared name visits once")
		assert.Equal(t, subject.Name, "ALPHA", "the settled spelling writes back")
		assert.Equal(t, hosts[0], symbol.KindInvalid, "the top level has no host")
		assert.Equal(t, seen[0], symbol.VisibilityInternal,
			"the carrier's visibility reaches the hook")
		for i, h := range hosts {
			if i == 0 {
				continue
			}
			_ = i
			assert.Equal(t, h, symbol.KindMethod,
				"a member's host is its enclosing kind")
		}
		_ = seen
	})

	t.Run("Param", func(t *testing.T) {
		t.Parallel()

		subject := &Param{}
		subject.Name = "alpha"
		var hosts []symbol.Kind
		var seen []symbol.Visibility
		err := RespellNames(subject,
			func(host, kind symbol.Kind, v symbol.Visibility, name string) (string, error) {
				hosts = append(hosts, host)
				seen = append(seen, v)
				return strings.ToUpper(name), nil
			})
		assert.NoError(t, err, "the traversal completes")
		assert.Equal(t, len(hosts), 1, "every declared name visits once")
		assert.Equal(t, subject.Name, "ALPHA", "the settled spelling writes back")
		assert.Equal(t, hosts[0], symbol.KindInvalid, "the top level has no host")
		for i, h := range hosts {
			if i == 0 {
				continue
			}
			_ = i
			assert.Equal(t, h, symbol.KindParam,
				"a member's host is its enclosing kind")
		}
		_ = seen
	})

	t.Run("Return", func(t *testing.T) {
		t.Parallel()

		subject := &Return{}
		subject.Name = "alpha"
		var hosts []symbol.Kind
		var seen []symbol.Visibility
		err := RespellNames(subject,
			func(host, kind symbol.Kind, v symbol.Visibility, name string) (string, error) {
				hosts = append(hosts, host)
				seen = append(seen, v)
				return strings.ToUpper(name), nil
			})
		assert.NoError(t, err, "the traversal completes")
		assert.Equal(t, len(hosts), 1, "every declared name visits once")
		assert.Equal(t, subject.Name, "ALPHA", "the settled spelling writes back")
		assert.Equal(t, hosts[0], symbol.KindInvalid, "the top level has no host")
		for i, h := range hosts {
			if i == 0 {
				continue
			}
			_ = i
			assert.Equal(t, h, symbol.KindReturn,
				"a member's host is its enclosing kind")
		}
		_ = seen
	})

	t.Run("Enum", func(t *testing.T) {
		t.Parallel()

		subject := &Enum{}
		subject.Name = "alpha"
		subject.Visibility = symbol.VisibilityInternal
		subject.VariantsSlot().Append(&EnumVariant{Name: "beta"})
		subject.FieldsSlot().Append(&Field{Name: "beta"})
		subject.MethodsSlot().Append(&Method{Name: "beta"})
		var hosts []symbol.Kind
		var seen []symbol.Visibility
		err := RespellNames(subject,
			func(host, kind symbol.Kind, v symbol.Visibility, name string) (string, error) {
				hosts = append(hosts, host)
				seen = append(seen, v)
				return strings.ToUpper(name), nil
			})
		assert.NoError(t, err, "the traversal completes")
		assert.Equal(t, len(hosts), 4, "every declared name visits once")
		assert.Equal(t, subject.Name, "ALPHA", "the settled spelling writes back")
		assert.Equal(t, hosts[0], symbol.KindInvalid, "the top level has no host")
		assert.Equal(t, seen[0], symbol.VisibilityInternal,
			"the carrier's visibility reaches the hook")
		for i, h := range hosts {
			if i == 0 {
				continue
			}
			_ = i
			assert.Equal(t, h, symbol.KindEnum,
				"a member's host is its enclosing kind")
		}
		_ = seen
	})

	t.Run("EnumVariant", func(t *testing.T) {
		t.Parallel()

		subject := &EnumVariant{}
		subject.Name = "alpha"
		var hosts []symbol.Kind
		var seen []symbol.Visibility
		err := RespellNames(subject,
			func(host, kind symbol.Kind, v symbol.Visibility, name string) (string, error) {
				hosts = append(hosts, host)
				seen = append(seen, v)
				return strings.ToUpper(name), nil
			})
		assert.NoError(t, err, "the traversal completes")
		assert.Equal(t, len(hosts), 1, "every declared name visits once")
		assert.Equal(t, subject.Name, "ALPHA", "the settled spelling writes back")
		assert.Equal(t, hosts[0], symbol.KindInvalid, "the top level has no host")
		for i, h := range hosts {
			if i == 0 {
				continue
			}
			_ = i
			assert.Equal(t, h, symbol.KindEnumVariant,
				"a member's host is its enclosing kind")
		}
		_ = seen
	})

	t.Run("Sum", func(t *testing.T) {
		t.Parallel()

		subject := &Sum{}
		subject.Name = "alpha"
		subject.Visibility = symbol.VisibilityInternal
		subject.TypeParams = append(subject.TypeParams, &TypeParam{Name: "beta"})
		subject.VariantsSlot().Append(&SumVariant{Name: "beta"})
		subject.MethodsSlot().Append(&Method{Name: "beta"})
		var hosts []symbol.Kind
		var seen []symbol.Visibility
		err := RespellNames(subject,
			func(host, kind symbol.Kind, v symbol.Visibility, name string) (string, error) {
				hosts = append(hosts, host)
				seen = append(seen, v)
				return strings.ToUpper(name), nil
			})
		assert.NoError(t, err, "the traversal completes")
		assert.Equal(t, len(hosts), 4, "every declared name visits once")
		assert.Equal(t, subject.Name, "ALPHA", "the settled spelling writes back")
		assert.Equal(t, hosts[0], symbol.KindInvalid, "the top level has no host")
		assert.Equal(t, seen[0], symbol.VisibilityInternal,
			"the carrier's visibility reaches the hook")
		for i, h := range hosts {
			if i == 0 {
				continue
			}
			_ = i
			assert.Equal(t, h, symbol.KindSum,
				"a member's host is its enclosing kind")
		}
		_ = seen
	})

	t.Run("SumVariant", func(t *testing.T) {
		t.Parallel()

		subject := &SumVariant{}
		subject.Name = "alpha"
		subject.FieldsSlot().Append(&Field{Name: "beta"})
		var hosts []symbol.Kind
		var seen []symbol.Visibility
		err := RespellNames(subject,
			func(host, kind symbol.Kind, v symbol.Visibility, name string) (string, error) {
				hosts = append(hosts, host)
				seen = append(seen, v)
				return strings.ToUpper(name), nil
			})
		assert.NoError(t, err, "the traversal completes")
		assert.Equal(t, len(hosts), 2, "every declared name visits once")
		assert.Equal(t, subject.Name, "ALPHA", "the settled spelling writes back")
		assert.Equal(t, hosts[0], symbol.KindInvalid, "the top level has no host")
		for i, h := range hosts {
			if i == 0 {
				continue
			}
			_ = i
			assert.Equal(t, h, symbol.KindSumVariant,
				"a member's host is its enclosing kind")
		}
		_ = seen
	})

	t.Run("Field", func(t *testing.T) {
		t.Parallel()

		subject := &Field{}
		subject.Name = "alpha"
		subject.Visibility = symbol.VisibilityInternal
		var hosts []symbol.Kind
		var seen []symbol.Visibility
		err := RespellNames(subject,
			func(host, kind symbol.Kind, v symbol.Visibility, name string) (string, error) {
				hosts = append(hosts, host)
				seen = append(seen, v)
				return strings.ToUpper(name), nil
			})
		assert.NoError(t, err, "the traversal completes")
		assert.Equal(t, len(hosts), 1, "every declared name visits once")
		assert.Equal(t, subject.Name, "ALPHA", "the settled spelling writes back")
		assert.Equal(t, hosts[0], symbol.KindInvalid, "the top level has no host")
		assert.Equal(t, seen[0], symbol.VisibilityInternal,
			"the carrier's visibility reaches the hook")
		for i, h := range hosts {
			if i == 0 {
				continue
			}
			_ = i
			assert.Equal(t, h, symbol.KindField,
				"a member's host is its enclosing kind")
		}
		_ = seen
	})

	t.Run("Variable", func(t *testing.T) {
		t.Parallel()

		subject := &Variable{}
		subject.Name = "alpha"
		subject.Visibility = symbol.VisibilityInternal
		var hosts []symbol.Kind
		var seen []symbol.Visibility
		err := RespellNames(subject,
			func(host, kind symbol.Kind, v symbol.Visibility, name string) (string, error) {
				hosts = append(hosts, host)
				seen = append(seen, v)
				return strings.ToUpper(name), nil
			})
		assert.NoError(t, err, "the traversal completes")
		assert.Equal(t, len(hosts), 1, "every declared name visits once")
		assert.Equal(t, subject.Name, "ALPHA", "the settled spelling writes back")
		assert.Equal(t, hosts[0], symbol.KindInvalid, "the top level has no host")
		assert.Equal(t, seen[0], symbol.VisibilityInternal,
			"the carrier's visibility reaches the hook")
		for i, h := range hosts {
			if i == 0 {
				continue
			}
			_ = i
			assert.Equal(t, h, symbol.KindVariable,
				"a member's host is its enclosing kind")
		}
		_ = seen
	})

	t.Run("Constant", func(t *testing.T) {
		t.Parallel()

		subject := &Constant{}
		subject.Name = "alpha"
		subject.Visibility = symbol.VisibilityInternal
		var hosts []symbol.Kind
		var seen []symbol.Visibility
		err := RespellNames(subject,
			func(host, kind symbol.Kind, v symbol.Visibility, name string) (string, error) {
				hosts = append(hosts, host)
				seen = append(seen, v)
				return strings.ToUpper(name), nil
			})
		assert.NoError(t, err, "the traversal completes")
		assert.Equal(t, len(hosts), 1, "every declared name visits once")
		assert.Equal(t, subject.Name, "ALPHA", "the settled spelling writes back")
		assert.Equal(t, hosts[0], symbol.KindInvalid, "the top level has no host")
		assert.Equal(t, seen[0], symbol.VisibilityInternal,
			"the carrier's visibility reaches the hook")
		for i, h := range hosts {
			if i == 0 {
				continue
			}
			_ = i
			assert.Equal(t, h, symbol.KindConstant,
				"a member's host is its enclosing kind")
		}
		_ = seen
	})

	t.Run("Struct", func(t *testing.T) {
		t.Parallel()

		subject := &Struct{}
		subject.Name = "alpha"
		subject.Visibility = symbol.VisibilityInternal
		subject.TypeParams = append(subject.TypeParams, &TypeParam{Name: "beta"})
		subject.FieldsSlot().Append(&Field{Name: "beta"})
		subject.MethodsSlot().Append(&Method{Name: "beta"})
		subject.TypesSlot().Append(&Struct{Name: "beta"})
		var hosts []symbol.Kind
		var seen []symbol.Visibility
		err := RespellNames(subject,
			func(host, kind symbol.Kind, v symbol.Visibility, name string) (string, error) {
				hosts = append(hosts, host)
				seen = append(seen, v)
				return strings.ToUpper(name), nil
			})
		assert.NoError(t, err, "the traversal completes")
		assert.Equal(t, len(hosts), 5, "every declared name visits once")
		assert.Equal(t, subject.Name, "ALPHA", "the settled spelling writes back")
		assert.Equal(t, hosts[0], symbol.KindInvalid, "the top level has no host")
		assert.Equal(t, seen[0], symbol.VisibilityInternal,
			"the carrier's visibility reaches the hook")
		for i, h := range hosts {
			if i == 0 {
				continue
			}
			_ = i
			assert.Equal(t, h, symbol.KindStruct,
				"a member's host is its enclosing kind")
		}
		_ = seen
	})

	t.Run("Interface", func(t *testing.T) {
		t.Parallel()

		subject := &Interface{}
		subject.Name = "alpha"
		subject.Visibility = symbol.VisibilityInternal
		subject.TypeParams = append(subject.TypeParams, &TypeParam{Name: "beta"})
		subject.FieldsSlot().Append(&Field{Name: "beta"})
		subject.MethodsSlot().Append(&Method{Name: "beta"})
		subject.TypesSlot().Append(&Interface{Name: "beta"})
		var hosts []symbol.Kind
		var seen []symbol.Visibility
		err := RespellNames(subject,
			func(host, kind symbol.Kind, v symbol.Visibility, name string) (string, error) {
				hosts = append(hosts, host)
				seen = append(seen, v)
				return strings.ToUpper(name), nil
			})
		assert.NoError(t, err, "the traversal completes")
		assert.Equal(t, len(hosts), 5, "every declared name visits once")
		assert.Equal(t, subject.Name, "ALPHA", "the settled spelling writes back")
		assert.Equal(t, hosts[0], symbol.KindInvalid, "the top level has no host")
		assert.Equal(t, seen[0], symbol.VisibilityInternal,
			"the carrier's visibility reaches the hook")
		for i, h := range hosts {
			if i == 0 {
				continue
			}
			_ = i
			assert.Equal(t, h, symbol.KindInterface,
				"a member's host is its enclosing kind")
		}
		_ = seen
	})

	t.Run("Alias", func(t *testing.T) {
		t.Parallel()

		subject := &Alias{}
		subject.Name = "alpha"
		subject.Visibility = symbol.VisibilityInternal
		subject.TypeParams = append(subject.TypeParams, &TypeParam{Name: "beta"})
		var hosts []symbol.Kind
		var seen []symbol.Visibility
		err := RespellNames(subject,
			func(host, kind symbol.Kind, v symbol.Visibility, name string) (string, error) {
				hosts = append(hosts, host)
				seen = append(seen, v)
				return strings.ToUpper(name), nil
			})
		assert.NoError(t, err, "the traversal completes")
		assert.Equal(t, len(hosts), 2, "every declared name visits once")
		assert.Equal(t, subject.Name, "ALPHA", "the settled spelling writes back")
		assert.Equal(t, hosts[0], symbol.KindInvalid, "the top level has no host")
		assert.Equal(t, seen[0], symbol.VisibilityInternal,
			"the carrier's visibility reaches the hook")
		for i, h := range hosts {
			if i == 0 {
				continue
			}
			_ = i
			assert.Equal(t, h, symbol.KindAlias,
				"a member's host is its enclosing kind")
		}
		_ = seen
	})

	t.Run("TypeParam", func(t *testing.T) {
		t.Parallel()

		subject := &TypeParam{}
		subject.Name = "alpha"
		var hosts []symbol.Kind
		var seen []symbol.Visibility
		err := RespellNames(subject,
			func(host, kind symbol.Kind, v symbol.Visibility, name string) (string, error) {
				hosts = append(hosts, host)
				seen = append(seen, v)
				return strings.ToUpper(name), nil
			})
		assert.NoError(t, err, "the traversal completes")
		assert.Equal(t, len(hosts), 1, "every declared name visits once")
		assert.Equal(t, subject.Name, "ALPHA", "the settled spelling writes back")
		assert.Equal(t, hosts[0], symbol.KindInvalid, "the top level has no host")
		for i, h := range hosts {
			if i == 0 {
				continue
			}
			_ = i
			assert.Equal(t, h, symbol.KindTypeParam,
				"a member's host is its enclosing kind")
		}
		_ = seen
	})

	t.Run("propagates the hook's error", func(t *testing.T) {
		t.Parallel()

		subject := &Function{Name: "alpha"}
		boom := errors.New("boom")
		err := RespellNames(subject,
			func(host, kind symbol.Kind, v symbol.Visibility, name string) (string, error) {
				return "", boom
			})
		assert.True(t, errors.Is(err, boom), "the first error returns")
		assert.Equal(t, subject.Name, "alpha", "and the name stands")
	})

	t.Run("skips an empty name", func(t *testing.T) {
		t.Parallel()

		calls := 0
		err := RespellNames(&Function{},
			func(host, kind symbol.Kind, v symbol.Visibility, name string) (string, error) {
				calls++
				return name, nil
			})
		assert.NoError(t, err, "an unnamed carrier walks clean")
		assert.Equal(t, calls, 0, "and offers nothing to respell")
	})

	t.Run("a nil symbol walks nothing", func(t *testing.T) {
		t.Parallel()

		err := RespellNames(nil,
			func(host, kind symbol.Kind, v symbol.Visibility, name string) (string, error) {
				return name, nil
			})
		assert.NoError(t, err, "nothing to walk is not a fault")
	})
}
