// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/model. DO NOT EDIT.

package emit_test

import (
	"testing"

	"go.dokimi.dev/assert"
	"go.dokimi.dev/assert/bench"
	. "go.dokimi.dev/eidos/core/emit"
	"go.dokimi.dev/eidos/core/symbol"
)

// slotsCase is one measured call of a slot accessor: the
// sub-benchmark's name, the call, and the check on what the last call
// returned. An accessor allocates nothing.
type slotsCase struct {
	name  string
	call  func()
	check func(testing.TB)
}

// A slot accessor is the composition seam between plugins, so what
// it hands back is contract: the value's own storage, never a copy
// and never nil.
func TestSlots(t *testing.T) {
	t.Parallel()

	t.Run("Enum.VariantsSlot", func(t *testing.T) {
		t.Parallel()

		t.Run("returns the value's own storage", func(t *testing.T) {
			t.Parallel()

			subject := &Enum{}
			slot := subject.VariantsSlot()
			assert.NotNil(t, slot,
				"the slot is part of the value, so the accessor never returns nil")
			assert.Equal(t, slot.Len(), 0, "and an untouched slot holds nothing")

			slot.Append(&EnumVariant{})
			assert.Equal(t, subject.Variants.Len(), 1,
				"what a plugin appends through the accessor is what the value holds")
			assert.True(t, slot == subject.VariantsSlot(),
				"and a second call addresses the same storage, so two plugins "+
					"appending through it append into one list")
		})
	})

	t.Run("Enum.FieldsSlot", func(t *testing.T) {
		t.Parallel()

		t.Run("returns the value's own storage", func(t *testing.T) {
			t.Parallel()

			subject := &Enum{}
			slot := subject.FieldsSlot()
			assert.NotNil(t, slot,
				"the slot is part of the value, so the accessor never returns nil")
			assert.Equal(t, slot.Len(), 0, "and an untouched slot holds nothing")

			slot.Append(&Field{})
			assert.Equal(t, subject.Fields.Len(), 1,
				"what a plugin appends through the accessor is what the value holds")
			assert.True(t, slot == subject.FieldsSlot(),
				"and a second call addresses the same storage, so two plugins "+
					"appending through it append into one list")
		})
	})

	t.Run("Enum.MethodsSlot", func(t *testing.T) {
		t.Parallel()

		t.Run("returns the value's own storage", func(t *testing.T) {
			t.Parallel()

			subject := &Enum{}
			slot := subject.MethodsSlot()
			assert.NotNil(t, slot,
				"the slot is part of the value, so the accessor never returns nil")
			assert.Equal(t, slot.Len(), 0, "and an untouched slot holds nothing")

			slot.Append(&Method{})
			assert.Equal(t, subject.Methods.Len(), 1,
				"what a plugin appends through the accessor is what the value holds")
			assert.True(t, slot == subject.MethodsSlot(),
				"and a second call addresses the same storage, so two plugins "+
					"appending through it append into one list")
		})
	})

	t.Run("Sum.VariantsSlot", func(t *testing.T) {
		t.Parallel()

		t.Run("returns the value's own storage", func(t *testing.T) {
			t.Parallel()

			subject := &Sum{}
			slot := subject.VariantsSlot()
			assert.NotNil(t, slot,
				"the slot is part of the value, so the accessor never returns nil")
			assert.Equal(t, slot.Len(), 0, "and an untouched slot holds nothing")

			slot.Append(&SumVariant{})
			assert.Equal(t, subject.Variants.Len(), 1,
				"what a plugin appends through the accessor is what the value holds")
			assert.True(t, slot == subject.VariantsSlot(),
				"and a second call addresses the same storage, so two plugins "+
					"appending through it append into one list")
		})
	})

	t.Run("Sum.MethodsSlot", func(t *testing.T) {
		t.Parallel()

		t.Run("returns the value's own storage", func(t *testing.T) {
			t.Parallel()

			subject := &Sum{}
			slot := subject.MethodsSlot()
			assert.NotNil(t, slot,
				"the slot is part of the value, so the accessor never returns nil")
			assert.Equal(t, slot.Len(), 0, "and an untouched slot holds nothing")

			slot.Append(&Method{})
			assert.Equal(t, subject.Methods.Len(), 1,
				"what a plugin appends through the accessor is what the value holds")
			assert.True(t, slot == subject.MethodsSlot(),
				"and a second call addresses the same storage, so two plugins "+
					"appending through it append into one list")
		})
	})

	t.Run("SumVariant.FieldsSlot", func(t *testing.T) {
		t.Parallel()

		t.Run("returns the value's own storage", func(t *testing.T) {
			t.Parallel()

			subject := &SumVariant{}
			slot := subject.FieldsSlot()
			assert.NotNil(t, slot,
				"the slot is part of the value, so the accessor never returns nil")
			assert.Equal(t, slot.Len(), 0, "and an untouched slot holds nothing")

			slot.Append(&Field{})
			assert.Equal(t, subject.Fields.Len(), 1,
				"what a plugin appends through the accessor is what the value holds")
			assert.True(t, slot == subject.FieldsSlot(),
				"and a second call addresses the same storage, so two plugins "+
					"appending through it append into one list")
		})
	})

	t.Run("Struct.FieldsSlot", func(t *testing.T) {
		t.Parallel()

		t.Run("returns the value's own storage", func(t *testing.T) {
			t.Parallel()

			subject := &Struct{}
			slot := subject.FieldsSlot()
			assert.NotNil(t, slot,
				"the slot is part of the value, so the accessor never returns nil")
			assert.Equal(t, slot.Len(), 0, "and an untouched slot holds nothing")

			slot.Append(&Field{})
			assert.Equal(t, subject.Fields.Len(), 1,
				"what a plugin appends through the accessor is what the value holds")
			assert.True(t, slot == subject.FieldsSlot(),
				"and a second call addresses the same storage, so two plugins "+
					"appending through it append into one list")
		})
	})

	t.Run("Struct.MethodsSlot", func(t *testing.T) {
		t.Parallel()

		t.Run("returns the value's own storage", func(t *testing.T) {
			t.Parallel()

			subject := &Struct{}
			slot := subject.MethodsSlot()
			assert.NotNil(t, slot,
				"the slot is part of the value, so the accessor never returns nil")
			assert.Equal(t, slot.Len(), 0, "and an untouched slot holds nothing")

			slot.Append(&Method{})
			assert.Equal(t, subject.Methods.Len(), 1,
				"what a plugin appends through the accessor is what the value holds")
			assert.True(t, slot == subject.MethodsSlot(),
				"and a second call addresses the same storage, so two plugins "+
					"appending through it append into one list")
		})
	})

	t.Run("Struct.TypesSlot", func(t *testing.T) {
		t.Parallel()

		t.Run("returns the value's own storage", func(t *testing.T) {
			t.Parallel()

			subject := &Struct{}
			slot := subject.TypesSlot()
			assert.NotNil(t, slot,
				"the slot is part of the value, so the accessor never returns nil")
			assert.Equal(t, slot.Len(), 0, "and an untouched slot holds nothing")

			slot.Append(&Struct{})
			assert.Equal(t, subject.Types.Len(), 1,
				"what a plugin appends through the accessor is what the value holds")
			assert.True(t, slot == subject.TypesSlot(),
				"and a second call addresses the same storage, so two plugins "+
					"appending through it append into one list")
		})
	})

	t.Run("Interface.FieldsSlot", func(t *testing.T) {
		t.Parallel()

		t.Run("returns the value's own storage", func(t *testing.T) {
			t.Parallel()

			subject := &Interface{}
			slot := subject.FieldsSlot()
			assert.NotNil(t, slot,
				"the slot is part of the value, so the accessor never returns nil")
			assert.Equal(t, slot.Len(), 0, "and an untouched slot holds nothing")

			slot.Append(&Field{})
			assert.Equal(t, subject.Fields.Len(), 1,
				"what a plugin appends through the accessor is what the value holds")
			assert.True(t, slot == subject.FieldsSlot(),
				"and a second call addresses the same storage, so two plugins "+
					"appending through it append into one list")
		})
	})

	t.Run("Interface.MethodsSlot", func(t *testing.T) {
		t.Parallel()

		t.Run("returns the value's own storage", func(t *testing.T) {
			t.Parallel()

			subject := &Interface{}
			slot := subject.MethodsSlot()
			assert.NotNil(t, slot,
				"the slot is part of the value, so the accessor never returns nil")
			assert.Equal(t, slot.Len(), 0, "and an untouched slot holds nothing")

			slot.Append(&Method{})
			assert.Equal(t, subject.Methods.Len(), 1,
				"what a plugin appends through the accessor is what the value holds")
			assert.True(t, slot == subject.MethodsSlot(),
				"and a second call addresses the same storage, so two plugins "+
					"appending through it append into one list")
		})
	})

	t.Run("Interface.TypesSlot", func(t *testing.T) {
		t.Parallel()

		t.Run("returns the value's own storage", func(t *testing.T) {
			t.Parallel()

			subject := &Interface{}
			slot := subject.TypesSlot()
			assert.NotNil(t, slot,
				"the slot is part of the value, so the accessor never returns nil")
			assert.Equal(t, slot.Len(), 0, "and an untouched slot holds nothing")

			slot.Append(&Interface{})
			assert.Equal(t, subject.Types.Len(), 1,
				"what a plugin appends through the accessor is what the value holds")
			assert.True(t, slot == subject.TypesSlot(),
				"and a second call addresses the same storage, so two plugins "+
					"appending through it append into one list")
		})
	})
}

// The accessors allocate nothing in the ordinary run, which runs no
// benchmark.
func TestSlotsZeroAlloc(t *testing.T) {
	for _, tt := range slotsCases() {
		assert.MaxAllocs(t, tt.call, 0, tt.name+" allocates nothing")
		tt.check(t)
	}
}

// BenchmarkSlots measures every slot accessor.
func BenchmarkSlots(b *testing.B) {
	for _, tt := range slotsCases() {
		b.Run(tt.name, func(b *testing.B) {
			c := bench.Start(b).MaxAllocs(0)
			defer c.End()
			for c.Loop() {
				tt.call()
			}
			tt.check(b)
		})
	}
}

// slotsCases returns one case for every slot accessor of every kind.
func slotsCases() []slotsCase {
	var cases []slotsCase
	{
		subject := &Enum{}
		var slot *Slot[*EnumVariant]
		cases = append(cases, slotsCase{
			name: "Enum.VariantsSlot",
			call: func() { slot = subject.VariantsSlot() },
			check: func(tb testing.TB) {
				assert.True(tb, slot == &subject.Variants, "VariantsSlot returns the value's own storage")
			},
		})
	}
	{
		subject := &Enum{}
		var slot *Slot[*Field]
		cases = append(cases, slotsCase{
			name: "Enum.FieldsSlot",
			call: func() { slot = subject.FieldsSlot() },
			check: func(tb testing.TB) {
				assert.True(tb, slot == &subject.Fields, "FieldsSlot returns the value's own storage")
			},
		})
	}
	{
		subject := &Enum{}
		var slot *Slot[*Method]
		cases = append(cases, slotsCase{
			name: "Enum.MethodsSlot",
			call: func() { slot = subject.MethodsSlot() },
			check: func(tb testing.TB) {
				assert.True(tb, slot == &subject.Methods, "MethodsSlot returns the value's own storage")
			},
		})
	}
	{
		subject := &Sum{}
		var slot *Slot[*SumVariant]
		cases = append(cases, slotsCase{
			name: "Sum.VariantsSlot",
			call: func() { slot = subject.VariantsSlot() },
			check: func(tb testing.TB) {
				assert.True(tb, slot == &subject.Variants, "VariantsSlot returns the value's own storage")
			},
		})
	}
	{
		subject := &Sum{}
		var slot *Slot[*Method]
		cases = append(cases, slotsCase{
			name: "Sum.MethodsSlot",
			call: func() { slot = subject.MethodsSlot() },
			check: func(tb testing.TB) {
				assert.True(tb, slot == &subject.Methods, "MethodsSlot returns the value's own storage")
			},
		})
	}
	{
		subject := &SumVariant{}
		var slot *Slot[*Field]
		cases = append(cases, slotsCase{
			name: "SumVariant.FieldsSlot",
			call: func() { slot = subject.FieldsSlot() },
			check: func(tb testing.TB) {
				assert.True(tb, slot == &subject.Fields, "FieldsSlot returns the value's own storage")
			},
		})
	}
	{
		subject := &Struct{}
		var slot *Slot[*Field]
		cases = append(cases, slotsCase{
			name: "Struct.FieldsSlot",
			call: func() { slot = subject.FieldsSlot() },
			check: func(tb testing.TB) {
				assert.True(tb, slot == &subject.Fields, "FieldsSlot returns the value's own storage")
			},
		})
	}
	{
		subject := &Struct{}
		var slot *Slot[*Method]
		cases = append(cases, slotsCase{
			name: "Struct.MethodsSlot",
			call: func() { slot = subject.MethodsSlot() },
			check: func(tb testing.TB) {
				assert.True(tb, slot == &subject.Methods, "MethodsSlot returns the value's own storage")
			},
		})
	}
	{
		subject := &Struct{}
		var slot *Slot[symbol.Symbol]
		cases = append(cases, slotsCase{
			name: "Struct.TypesSlot",
			call: func() { slot = subject.TypesSlot() },
			check: func(tb testing.TB) {
				assert.True(tb, slot == &subject.Types, "TypesSlot returns the value's own storage")
			},
		})
	}
	{
		subject := &Interface{}
		var slot *Slot[*Field]
		cases = append(cases, slotsCase{
			name: "Interface.FieldsSlot",
			call: func() { slot = subject.FieldsSlot() },
			check: func(tb testing.TB) {
				assert.True(tb, slot == &subject.Fields, "FieldsSlot returns the value's own storage")
			},
		})
	}
	{
		subject := &Interface{}
		var slot *Slot[*Method]
		cases = append(cases, slotsCase{
			name: "Interface.MethodsSlot",
			call: func() { slot = subject.MethodsSlot() },
			check: func(tb testing.TB) {
				assert.True(tb, slot == &subject.Methods, "MethodsSlot returns the value's own storage")
			},
		})
	}
	{
		subject := &Interface{}
		var slot *Slot[symbol.Symbol]
		cases = append(cases, slotsCase{
			name: "Interface.TypesSlot",
			call: func() { slot = subject.TypesSlot() },
			check: func(tb testing.TB) {
				assert.True(tb, slot == &subject.Types, "TypesSlot returns the value's own storage")
			},
		})
	}
	return cases
}
