// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: MIT

// Code generated by internal/gen/model. DO NOT EDIT.

package emit

import "go.dokimi.dev/eidos/core/symbol"

// VariantsSlot answers the Variants slot of a Enum, which
// plugins append into. The slot is part of the value, so the
// accessor never answers nil.
func (x *Enum) VariantsSlot() *Slot[*EnumVariant] { return &x.variants }

// FieldsSlot answers the Fields slot of a Enum, which
// plugins append into. The slot is part of the value, so the
// accessor never answers nil.
func (x *Enum) FieldsSlot() *Slot[*Field] { return &x.fields }

// MethodsSlot answers the Methods slot of a Enum, which
// plugins append into. The slot is part of the value, so the
// accessor never answers nil.
func (x *Enum) MethodsSlot() *Slot[*Method] { return &x.methods }

// VariantsSlot answers the Variants slot of a Sum, which
// plugins append into. The slot is part of the value, so the
// accessor never answers nil.
func (x *Sum) VariantsSlot() *Slot[*SumVariant] { return &x.variants }

// MethodsSlot answers the Methods slot of a Sum, which
// plugins append into. The slot is part of the value, so the
// accessor never answers nil.
func (x *Sum) MethodsSlot() *Slot[*Method] { return &x.methods }

// FieldsSlot answers the Fields slot of a SumVariant, which
// plugins append into. The slot is part of the value, so the
// accessor never answers nil.
func (x *SumVariant) FieldsSlot() *Slot[*Field] { return &x.fields }

// FieldsSlot answers the Fields slot of a Struct, which
// plugins append into. The slot is part of the value, so the
// accessor never answers nil.
func (x *Struct) FieldsSlot() *Slot[*Field] { return &x.fields }

// MethodsSlot answers the Methods slot of a Struct, which
// plugins append into. The slot is part of the value, so the
// accessor never answers nil.
func (x *Struct) MethodsSlot() *Slot[*Method] { return &x.methods }

// TypesSlot answers the Types slot of a Struct, which
// plugins append into. The slot is part of the value, so the
// accessor never answers nil.
func (x *Struct) TypesSlot() *Slot[symbol.Symbol] { return &x.types }

// FieldsSlot answers the Fields slot of a Interface, which
// plugins append into. The slot is part of the value, so the
// accessor never answers nil.
func (x *Interface) FieldsSlot() *Slot[*Field] { return &x.fields }

// MethodsSlot answers the Methods slot of a Interface, which
// plugins append into. The slot is part of the value, so the
// accessor never answers nil.
func (x *Interface) MethodsSlot() *Slot[*Method] { return &x.methods }

// TypesSlot answers the Types slot of a Interface, which
// plugins append into. The slot is part of the value, so the
// accessor never answers nil.
func (x *Interface) TypesSlot() *Slot[symbol.Symbol] { return &x.types }
