// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/model. DO NOT EDIT.

package emit

import (
	"bytes"
	"encoding/json"
	"fmt"

	"go.dokimi.dev/eidos/core/symbol"
)

// kindKey names the discriminator in an encoded declaration whose
// concrete kind the field's type does not determine. kindPrefix
// opens every encoding [EncodeJSON] writes, so a decoder reads the
// kind from the first bytes.
const (
	kindKey    = "kind"
	kindPrefix = `{"` + kindKey + `":"`
)

// jsonNull is the encoding of a nil declaration and of a nil list.
const jsonNull = "null"

// newByKind allocates a declaration of a kind.
//
// The table is indexed by the kind, because the vocabulary already
// parses a name into a kind. Only a decoder that cannot learn the
// concrete type from context uses it. A field typed `[]*Field`
// decodes through the struct tags alone.
var newByKind = [...]func() symbol.Symbol{
	symbol.KindFunction:    func() symbol.Symbol { return new(Function) },
	symbol.KindMethod:      func() symbol.Symbol { return new(Method) },
	symbol.KindParam:       func() symbol.Symbol { return new(Param) },
	symbol.KindReturn:      func() symbol.Symbol { return new(Return) },
	symbol.KindPackage:     func() symbol.Symbol { return new(Package) },
	symbol.KindFile:        func() symbol.Symbol { return new(File) },
	symbol.KindImport:      func() symbol.Symbol { return new(Import) },
	symbol.KindExport:      func() symbol.Symbol { return new(Export) },
	symbol.KindBinding:     func() symbol.Symbol { return new(Binding) },
	symbol.KindEnum:        func() symbol.Symbol { return new(Enum) },
	symbol.KindEnumVariant: func() symbol.Symbol { return new(EnumVariant) },
	symbol.KindSum:         func() symbol.Symbol { return new(Sum) },
	symbol.KindSumVariant:  func() symbol.Symbol { return new(SumVariant) },
	symbol.KindField:       func() symbol.Symbol { return new(Field) },
	symbol.KindVariable:    func() symbol.Symbol { return new(Variable) },
	symbol.KindConstant:    func() symbol.Symbol { return new(Constant) },
	symbol.KindStruct:      func() symbol.Symbol { return new(Struct) },
	symbol.KindInterface:   func() symbol.Symbol { return new(Interface) },
	symbol.KindAlias:       func() symbol.Symbol { return new(Alias) },
	symbol.KindTypeRef:     func() symbol.Symbol { return new(TypeRef) },
	symbol.KindTypeParam:   func() symbol.Symbol { return new(TypeParam) },
	symbol.KindEmbed:       func() symbol.Symbol { return new(Embed) },
}

// Symbols is the type of a field that admits declarations of any
// kind, such as a file's declaration list.
//
// Decoding a plain `[]symbol.Symbol` fails, because nothing tells
// the decoder which kind to allocate for an element. Every other
// field is typed concretely and decodes through the struct tags on
// the models.
type Symbols []symbol.Symbol

// MarshalJSON encodes each element with its kind in front of the
// fields the element's own tags produce, joined into one array. A
// nil list encodes as JSON null, which [Symbols.UnmarshalJSON]
// decodes back to nil.
func (s Symbols) MarshalJSON() ([]byte, error) {
	if s == nil {
		return []byte(jsonNull), nil
	}
	bodies := make([][]byte, len(s))
	size := len("[]") + max(len(s)-1, 0)
	for i, one := range s {
		body, err := EncodeJSON(one)
		if err != nil {
			return nil, err
		}
		bodies[i] = body
		size += len(body)
	}
	encoded := make([]byte, 0, size)
	encoded = append(encoded, '[')
	for i, body := range bodies {
		if i > 0 {
			encoded = append(encoded, ',')
		}
		encoded = append(encoded, body...)
	}
	return append(encoded, ']'), nil
}

// UnmarshalJSON decodes each element through its own kind.
//
// A JSON null decodes to a nil Symbols, so a nil list re-encodes as
// null.
func (s *Symbols) UnmarshalJSON(data []byte) error {
	var encoded []json.RawMessage
	if err := json.Unmarshal(data, &encoded); err != nil {
		return fmt.Errorf("emit: decode a declaration list: %w", err)
	}
	if encoded == nil {
		*s = nil
		return nil
	}

	decoded := make(Symbols, 0, len(encoded))
	for _, one := range encoded {
		child, err := DecodeJSON(one)
		if err != nil {
			return err
		}
		decoded = append(decoded, child)
	}
	*s = decoded
	return nil
}

// EncodeJSON encodes a declaration with its kind, so a decoder can
// allocate the right kind.
//
// The fields come from the declaration's own struct tags, and
// EncodeJSON writes the kind in front of them. A nil declaration
// encodes as JSON null, which [DecodeJSON] reads back as nil. A
// declaration whose own encoding is not an object is refused,
// because the kind can only be spliced into an object.
func EncodeJSON(s symbol.Symbol) ([]byte, error) {
	if s == nil {
		return []byte(jsonNull), nil
	}
	body, err := json.Marshal(s)
	if err != nil {
		return nil, fmt.Errorf("emit: encode %v: %w", s.Kind(), err)
	}
	if len(body) < 2 || body[0] != '{' || body[len(body)-1] != '}' {
		// The splice below opens the encoded object to put the kind
		// in front of its fields, so it requires an object. Only a
		// declaration from outside the models, with its own
		// MarshalJSON, fails this check.
		return nil, fmt.Errorf(
			"emit: encode %v: the declaration encodes as %s rather than an object",
			s.Kind(), body,
		)
	}

	// A kind's name is a Go type name, so it needs no escaping and
	// no second pass through the encoder.
	name := s.Kind().String()
	encoded := make([]byte, 0, len(body)+len(name)+len(kindPrefix)+2)
	encoded = append(encoded, kindPrefix...)
	encoded = append(encoded, name...)
	encoded = append(encoded, '"')
	if len(body) > 2 {
		encoded = append(encoded, ',')
		encoded = append(encoded, body[1:len(body)-1]...)
	}
	return append(encoded, '}'), nil
}

// DecodeJSON decodes a declaration encoded by [EncodeJSON].
//
// It reads the kind, allocates a declaration of that kind and
// decodes the fields through its struct tags. JSON null decodes to
// a nil declaration, and an unknown or absent kind is an error
// naming what it read.
func DecodeJSON(data []byte) (symbol.Symbol, error) {
	trimmed := bytes.TrimSpace(data)
	if string(trimmed) == jsonNull {
		return nil, nil
	}
	name, err := kindOf(trimmed)
	if err != nil {
		return nil, err
	}
	kind, known := symbol.ParseKind(name)
	if !known || int(kind) >= len(newByKind) || newByKind[kind] == nil {
		return nil, fmt.Errorf("emit: unknown %s %q", kindKey, name)
	}

	into := newByKind[kind]()
	if err := json.Unmarshal(data, into); err != nil {
		return nil, fmt.Errorf("emit: decode %s: %w", name, err)
	}
	return into, nil
}

// kindOf returns the kind an encoded declaration names.
//
// [EncodeJSON] writes the kind first, so a prefix read returns the
// kind of every encoding EncodeJSON wrote. Leading whitespace, a
// later kind key or an escaped kind name takes one probing decode.
func kindOf(data []byte) (string, error) {
	if rest, opens := bytes.CutPrefix(data, []byte(kindPrefix)); opens {
		if end := bytes.IndexByte(rest, '"'); end > 0 && bytes.IndexByte(rest[:end], '\\') < 0 {
			return string(rest[:end]), nil
		}
	}
	var probe struct {
		Kind string `json:"kind"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return "", fmt.Errorf("emit: read the %s: %w", kindKey, err)
	}
	if probe.Kind == "" {
		return "", fmt.Errorf("emit: no %s in the encoded declaration", kindKey)
	}
	return probe.Kind, nil
}
