// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/model. DO NOT EDIT.

package emit

import (
	"bytes"
	"encoding/json"
	"testing"

	"go.dokimi.dev/assert"
	"go.dokimi.dev/eidos/core/symbol"
)

func TestSymbols(t *testing.T) {
	t.Parallel()

	t.Run("EncodeJSON", func(t *testing.T) {
		t.Parallel()

		t.Run("encodes a nil declaration as null", func(t *testing.T) {
			t.Parallel()

			got, err := EncodeJSON(nil)
			assert.NoError(t, err, "a nil declaration encodes")
			assert.Equal(t, string(got), "null", "as JSON null")
		})

		t.Run("carries the kind on every declaration", func(t *testing.T) {
			t.Parallel()

			{
				encoded, err := EncodeJSON(&Function{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"Function"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&Method{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"Method"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&Param{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"Param"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&Return{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"Return"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&Package{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"Package"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&File{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"File"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&Import{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"Import"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&Export{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"Export"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&Binding{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"Binding"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&Enum{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"Enum"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&EnumVariant{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"EnumVariant"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&Sum{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"Sum"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&SumVariant{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"SumVariant"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&Field{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"Field"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&Variable{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"Variable"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&Constant{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"Constant"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&Struct{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"Struct"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&Interface{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"Interface"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&Alias{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"Alias"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&TypeRef{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"TypeRef"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&TypeParam{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"TypeParam"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&Constraint{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"Constraint"`,
					"carrying its kind so a decoder can place it")
			}

			{
				encoded, err := EncodeJSON(&Embed{})
				assert.NoError(t, err, "every kind encodes")
				assert.Contains(t, string(encoded), `"kind":"Embed"`,
					"carrying its kind so a decoder can place it")
			}
		})

		t.Run("a concrete field needs no kind", func(t *testing.T) {
			t.Parallel()

			// Struct tags carry a concretely typed field on their own,
			// which is why only Symbols reaches for a discriminator.
			encoded, err := json.Marshal(&Function{})
			assert.NoError(t, err, "a concrete field marshals through its tags")
			assert.NotContains(t, string(encoded), `"kind"`,
				"and needs no discriminator")
		})
	})

	t.Run("DecodeJSON", func(t *testing.T) {
		t.Parallel()

		t.Run("round-trips every kind", func(t *testing.T) {
			t.Parallel()

			subjects := []symbol.Symbol{
				&Function{},
				&Method{},
				&Param{},
				&Return{},
				&Package{},
				&File{},
				&Import{},
				&Export{},
				&Binding{},
				&Enum{},
				&EnumVariant{},
				&Sum{},
				&SumVariant{},
				&Field{},
				&Variable{},
				&Constant{},
				&Struct{},
				&Interface{},
				&Alias{},
				&TypeRef{},
				&TypeParam{},
				&Constraint{},
				&Embed{},
			}
			for _, subject := range subjects {
				t.Run(subject.Kind().String(), func(t *testing.T) {
					t.Parallel()

					encoded, err := EncodeJSON(subject)
					assert.NoError(t, err, "the kind encodes")
					decoded, err := DecodeJSON(encoded)
					assert.NoError(t, err, "its encoding decodes")
					assert.Equal(t, decoded.Kind(), subject.Kind(),
						"to the kind that produced it")
					again, err := EncodeJSON(decoded)
					assert.NoError(t, err, "and encodes again")
					assert.Equal(t, string(again), string(encoded),
						"to the same bytes: the round trip is a fixed point")
				})
			}
		})

		t.Run("round-trips a populated declaration and its children", func(t *testing.T) {
			t.Parallel()

			{
				subject := &Function{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Params = append(subject.Params, &Param{})
				subject.Returns = append(subject.Returns, &Return{})
				subject.Throws = append(subject.Throws, &TypeRef{})
				encoded, err := EncodeJSON(subject)
				assert.NoError(t, err, "a populated declaration encodes")
				decoded, err := DecodeJSON(encoded)
				assert.NoError(t, err, "and decodes")

				var walked int
				Walk(decoded, func(symbol.Symbol) bool {
					walked++
					return true
				})
				assert.Equal(t, walked, 5,
					"with every child the original held")
			}

			{
				subject := &Method{}
				subject.Receiver = &Param{}
				subject.Receives = &TypeRef{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Params = append(subject.Params, &Param{})
				subject.Returns = append(subject.Returns, &Return{})
				subject.Throws = append(subject.Throws, &TypeRef{})
				encoded, err := EncodeJSON(subject)
				assert.NoError(t, err, "a populated declaration encodes")
				decoded, err := DecodeJSON(encoded)
				assert.NoError(t, err, "and decodes")

				var walked int
				Walk(decoded, func(symbol.Symbol) bool {
					walked++
					return true
				})
				assert.Equal(t, walked, 7,
					"with every child the original held")
			}

			{
				subject := &Param{}
				subject.Type = &TypeRef{}
				encoded, err := EncodeJSON(subject)
				assert.NoError(t, err, "a populated declaration encodes")
				decoded, err := DecodeJSON(encoded)
				assert.NoError(t, err, "and decodes")

				var walked int
				Walk(decoded, func(symbol.Symbol) bool {
					walked++
					return true
				})
				assert.Equal(t, walked, 2,
					"with every child the original held")
			}

			{
				subject := &Return{}
				subject.Type = &TypeRef{}
				encoded, err := EncodeJSON(subject)
				assert.NoError(t, err, "a populated declaration encodes")
				decoded, err := DecodeJSON(encoded)
				assert.NoError(t, err, "and decodes")

				var walked int
				Walk(decoded, func(symbol.Symbol) bool {
					walked++
					return true
				})
				assert.Equal(t, walked, 2,
					"with every child the original held")
			}

			{
				subject := &Enum{}
				subject.VariantsSlot().Append(&EnumVariant{})
				subject.FieldsSlot().Append(&Field{})
				subject.MethodsSlot().Append(&Method{})
				encoded, err := EncodeJSON(subject)
				assert.NoError(t, err, "a populated declaration encodes")
				decoded, err := DecodeJSON(encoded)
				assert.NoError(t, err, "and decodes")

				var walked int
				Walk(decoded, func(symbol.Symbol) bool {
					walked++
					return true
				})
				assert.Equal(t, walked, 4,
					"with every child the original held")
			}

			{
				subject := &Sum{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.VariantsSlot().Append(&SumVariant{})
				subject.MethodsSlot().Append(&Method{})
				encoded, err := EncodeJSON(subject)
				assert.NoError(t, err, "a populated declaration encodes")
				decoded, err := DecodeJSON(encoded)
				assert.NoError(t, err, "and decodes")

				var walked int
				Walk(decoded, func(symbol.Symbol) bool {
					walked++
					return true
				})
				assert.Equal(t, walked, 4,
					"with every child the original held")
			}

			{
				subject := &SumVariant{}
				subject.FieldsSlot().Append(&Field{})
				encoded, err := EncodeJSON(subject)
				assert.NoError(t, err, "a populated declaration encodes")
				decoded, err := DecodeJSON(encoded)
				assert.NoError(t, err, "and decodes")

				var walked int
				Walk(decoded, func(symbol.Symbol) bool {
					walked++
					return true
				})
				assert.Equal(t, walked, 2,
					"with every child the original held")
			}

			{
				subject := &Field{}
				subject.Type = &TypeRef{}
				encoded, err := EncodeJSON(subject)
				assert.NoError(t, err, "a populated declaration encodes")
				decoded, err := DecodeJSON(encoded)
				assert.NoError(t, err, "and decodes")

				var walked int
				Walk(decoded, func(symbol.Symbol) bool {
					walked++
					return true
				})
				assert.Equal(t, walked, 2,
					"with every child the original held")
			}

			{
				subject := &Variable{}
				subject.Type = &TypeRef{}
				encoded, err := EncodeJSON(subject)
				assert.NoError(t, err, "a populated declaration encodes")
				decoded, err := DecodeJSON(encoded)
				assert.NoError(t, err, "and decodes")

				var walked int
				Walk(decoded, func(symbol.Symbol) bool {
					walked++
					return true
				})
				assert.Equal(t, walked, 2,
					"with every child the original held")
			}

			{
				subject := &Constant{}
				subject.Type = &TypeRef{}
				encoded, err := EncodeJSON(subject)
				assert.NoError(t, err, "a populated declaration encodes")
				decoded, err := DecodeJSON(encoded)
				assert.NoError(t, err, "and decodes")

				var walked int
				Walk(decoded, func(symbol.Symbol) bool {
					walked++
					return true
				})
				assert.Equal(t, walked, 2,
					"with every child the original held")
			}

			{
				subject := &Struct{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.FieldsSlot().Append(&Field{})
				subject.MethodsSlot().Append(&Method{})
				subject.TypesSlot().Append(&Struct{})
				subject.Embeds = append(subject.Embeds, &Embed{})
				subject.Extends = append(subject.Extends, &TypeRef{})
				subject.Implements = append(subject.Implements, &TypeRef{})
				subject.Permits = append(subject.Permits, &TypeRef{})
				encoded, err := EncodeJSON(subject)
				assert.NoError(t, err, "a populated declaration encodes")
				decoded, err := DecodeJSON(encoded)
				assert.NoError(t, err, "and decodes")

				var walked int
				Walk(decoded, func(symbol.Symbol) bool {
					walked++
					return true
				})
				assert.Equal(t, walked, 9,
					"with every child the original held")
			}

			{
				subject := &Interface{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.FieldsSlot().Append(&Field{})
				subject.MethodsSlot().Append(&Method{})
				subject.TypesSlot().Append(&Interface{})
				subject.Embeds = append(subject.Embeds, &Embed{})
				subject.Extends = append(subject.Extends, &TypeRef{})
				subject.Permits = append(subject.Permits, &TypeRef{})
				encoded, err := EncodeJSON(subject)
				assert.NoError(t, err, "a populated declaration encodes")
				decoded, err := DecodeJSON(encoded)
				assert.NoError(t, err, "and decodes")

				var walked int
				Walk(decoded, func(symbol.Symbol) bool {
					walked++
					return true
				})
				assert.Equal(t, walked, 8,
					"with every child the original held")
			}

			{
				subject := &Alias{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Target = &TypeRef{}
				encoded, err := EncodeJSON(subject)
				assert.NoError(t, err, "a populated declaration encodes")
				decoded, err := DecodeJSON(encoded)
				assert.NoError(t, err, "and decodes")

				var walked int
				Walk(decoded, func(symbol.Symbol) bool {
					walked++
					return true
				})
				assert.Equal(t, walked, 3,
					"with every child the original held")
			}

			{
				subject := &TypeRef{}
				subject.Args = append(subject.Args, &TypeRef{})
				encoded, err := EncodeJSON(subject)
				assert.NoError(t, err, "a populated declaration encodes")
				decoded, err := DecodeJSON(encoded)
				assert.NoError(t, err, "and decodes")

				var walked int
				Walk(decoded, func(symbol.Symbol) bool {
					walked++
					return true
				})
				assert.Equal(t, walked, 2,
					"with every child the original held")
			}

			{
				subject := &TypeParam{}
				subject.Bounds = append(subject.Bounds, &TypeRef{})
				subject.Default = &TypeRef{}
				subject.Type = &TypeRef{}
				encoded, err := EncodeJSON(subject)
				assert.NoError(t, err, "a populated declaration encodes")
				decoded, err := DecodeJSON(encoded)
				assert.NoError(t, err, "and decodes")

				var walked int
				Walk(decoded, func(symbol.Symbol) bool {
					walked++
					return true
				})
				assert.Equal(t, walked, 4,
					"with every child the original held")
			}

			{
				subject := &Constraint{}
				subject.Terms = append(subject.Terms, &TypeRef{})
				encoded, err := EncodeJSON(subject)
				assert.NoError(t, err, "a populated declaration encodes")
				decoded, err := DecodeJSON(encoded)
				assert.NoError(t, err, "and decodes")

				var walked int
				Walk(decoded, func(symbol.Symbol) bool {
					walked++
					return true
				})
				assert.Equal(t, walked, 2,
					"with every child the original held")
			}

			{
				subject := &Embed{}
				subject.Ref = &TypeRef{}
				encoded, err := EncodeJSON(subject)
				assert.NoError(t, err, "a populated declaration encodes")
				decoded, err := DecodeJSON(encoded)
				assert.NoError(t, err, "and decodes")

				var walked int
				Walk(decoded, func(symbol.Symbol) bool {
					walked++
					return true
				})
				assert.Equal(t, walked, 2,
					"with every child the original held")
			}
		})

		t.Run("refuses an encoding it cannot place", func(t *testing.T) {
			t.Parallel()

			tests := []struct {
				name string
				data string
			}{
				{name: "no kind", data: `{"name":"Store"}`},
				{name: "unknown kind", data: `{"kind":"Nonexistent"}`},
				{name: "not an object", data: `[]`},
				{name: "a Function body it cannot read", data: `{"kind":"Function","origin":"nope"}`},
				{name: "a Method body it cannot read", data: `{"kind":"Method","origin":"nope"}`},
				{name: "a Param body it cannot read", data: `{"kind":"Param","name":[]}`},
				{name: "a Return body it cannot read", data: `{"kind":"Return","name":[]}`},
				{name: "a Package body it cannot read", data: `{"kind":"Package","doc":"nope"}`},
				{name: "a File body it cannot read", data: `{"kind":"File","doc":"nope"}`},
				{name: "a Enum body it cannot read", data: `{"kind":"Enum","origin":"nope"}`},
				{name: "a EnumVariant body it cannot read", data: `{"kind":"EnumVariant","origin":"nope"}`},
				{name: "a Sum body it cannot read", data: `{"kind":"Sum","origin":"nope"}`},
				{name: "a SumVariant body it cannot read", data: `{"kind":"SumVariant","origin":"nope"}`},
				{name: "a Field body it cannot read", data: `{"kind":"Field","origin":"nope"}`},
				{name: "a Variable body it cannot read", data: `{"kind":"Variable","origin":"nope"}`},
				{name: "a Constant body it cannot read", data: `{"kind":"Constant","origin":"nope"}`},
				{name: "a Struct body it cannot read", data: `{"kind":"Struct","origin":"nope"}`},
				{name: "a Interface body it cannot read", data: `{"kind":"Interface","origin":"nope"}`},
				{name: "a Alias body it cannot read", data: `{"kind":"Alias","origin":"nope"}`},
				{name: "a TypeRef body it cannot read", data: `{"kind":"TypeRef","spelling":[]}`},
				{name: "a TypeParam body it cannot read", data: `{"kind":"TypeParam","name":[]}`},
				{name: "a Constraint body it cannot read", data: `{"kind":"Constraint","terms":"nope"}`},
				{name: "a Embed body it cannot read", data: `{"kind":"Embed","ref":"nope"}`},
			}
			for _, tt := range tests {
				t.Run(tt.name, func(t *testing.T) {
					t.Parallel()

					_, err := DecodeJSON([]byte(tt.data))
					assert.HasError(t, err, "an encoding it cannot place is refused")
				})
			}
		})
	})

	t.Run("UnmarshalJSON", func(t *testing.T) {
		t.Parallel()

		t.Run("decodes each element through its kind", func(t *testing.T) {
			t.Parallel()

			subjects := Symbols{
				&Function{},
				&Method{},
				&Param{},
				&Return{},
				&Package{},
				&File{},
				&Import{},
				&Export{},
				&Binding{},
				&Enum{},
				&EnumVariant{},
				&Sum{},
				&SumVariant{},
				&Field{},
				&Variable{},
				&Constant{},
				&Struct{},
				&Interface{},
				&Alias{},
				&TypeRef{},
				&TypeParam{},
				&Constraint{},
				&Embed{},
			}
			encoded, err := json.Marshal(subjects)
			assert.NoError(t, err, "the list marshals")

			var decoded Symbols
			assert.NoError(t, json.Unmarshal(encoded, &decoded), "and unmarshals")
			assert.Length(t, decoded, len(subjects), "whole")
			for i, want := range subjects {
				assert.Equal(t, decoded[i].Kind(), want.Kind(),
					"each element through its own kind")
			}
		})

		t.Run("a plain interface slice cannot decode the same bytes", func(t *testing.T) {
			t.Parallel()

			encoded, err := json.Marshal(Symbols{&Function{}})
			assert.NoError(t, err, "the list marshals")
			var plain []symbol.Symbol
			assert.HasError(t, json.Unmarshal(encoded, &plain),
				"a plain interface slice cannot decode the same bytes, "+
					"which is why Symbols exists")
		})

		t.Run("null decodes to nothing", func(t *testing.T) {
			t.Parallel()

			decoded := Symbols{&Function{}}
			assert.NoError(t, json.Unmarshal([]byte("null"), &decoded),
				"null unmarshals")
			assert.Nil(t, decoded, "to nothing, so a value re-encodes as it arrived")
		})

		t.Run("refuses an element it cannot place", func(t *testing.T) {
			t.Parallel()

			var decoded Symbols
			assert.HasError(t, json.Unmarshal([]byte(`[{"kind":"Nonexistent"}]`), &decoded),
				"an element it cannot place is refused")
			assert.HasError(t, json.Unmarshal([]byte(`{}`), &decoded),
				"and so is an encoding that is not a list")
		})
	})
}

// FuzzDecodeJSON drives the decoder with bytes nothing in this
// repository produced.
//
// The encoding is a boundary: a sealed state and a carried
// declaration both arrive as bytes a previous release, another tool
// or a corrupted file wrote. Two properties hold whatever those
// bytes are. Decoding returns an error rather than panicking, and a
// value that decoded re-encodes to bytes that decode to the same
// encoding, so one trip through the boundary is a fixed point.
func FuzzDecodeJSON(f *testing.F) {
	f.Add([]byte(`{"kind":"Function"}`))
	f.Add([]byte(`{"kind":"Method"}`))
	f.Add([]byte(`{"kind":"Param"}`))
	f.Add([]byte(`{"kind":"Return"}`))
	f.Add([]byte(`{"kind":"Package"}`))
	f.Add([]byte(`{"kind":"File"}`))
	f.Add([]byte(`{"kind":"Import"}`))
	f.Add([]byte(`{"kind":"Export"}`))
	f.Add([]byte(`{"kind":"Binding"}`))
	f.Add([]byte(`{"kind":"Enum"}`))
	f.Add([]byte(`{"kind":"EnumVariant"}`))
	f.Add([]byte(`{"kind":"Sum"}`))
	f.Add([]byte(`{"kind":"SumVariant"}`))
	f.Add([]byte(`{"kind":"Field"}`))
	f.Add([]byte(`{"kind":"Variable"}`))
	f.Add([]byte(`{"kind":"Constant"}`))
	f.Add([]byte(`{"kind":"Struct"}`))
	f.Add([]byte(`{"kind":"Interface"}`))
	f.Add([]byte(`{"kind":"Alias"}`))
	f.Add([]byte(`{"kind":"TypeRef"}`))
	f.Add([]byte(`{"kind":"TypeParam"}`))
	f.Add([]byte(`{"kind":"Constraint"}`))
	f.Add([]byte(`{"kind":"Embed"}`))
	for _, seed := range []string{`null`, `{}`, `[]`, `{"kind":"Nonexistent"}`} {
		f.Add([]byte(seed))
	}

	f.Fuzz(func(t *testing.T, in []byte) {
		decoded, err := DecodeJSON(in)
		if err != nil {
			return
		}
		encoded, err := EncodeJSON(decoded)
		if err != nil {
			t.Fatalf("DecodeJSON(%s) answered a value EncodeJSON refuses: %v", in, err)
		}
		again, err := DecodeJSON(encoded)
		if err != nil {
			t.Fatalf("DecodeJSON refuses its own encoding %s: %v", encoded, err)
		}
		twice, err := EncodeJSON(again)
		if err != nil {
			t.Fatalf("EncodeJSON: unexpected error: %v", err)
		}
		if !bytes.Equal(encoded, twice) {
			t.Fatalf("a second trip encoded as %s, want %s", twice, encoded)
		}
	})
}
