// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/model. DO NOT EDIT.

package node

import (
	"fmt"

	"go.dokimi.dev/eidos/core/internal/wire"
	"go.dokimi.dev/eidos/core/symbol"
)

// AppendBinary appends the binary encoding of s to dst and returns the
// extended buffer, numbering every string s spells in t.
//
// The encoding is the symbol's kind as one byte, then each of the kind's
// fields in schema order, each child written the same way, so it covers
// the symbol's whole subtree. A nil symbol is one zero byte. Where t is
// nil, each string is its length and its bytes, so two equal subtrees
// encode to equal bytes whatever table either region numbers its strings
// in: the form a comparison of two declarations reads.
//
// Error modes: an error for a symbol anywhere in the subtree whose type
// the model does not declare. dst comes back unchanged with it, and t
// may have numbered strings of the part written before it.
//
// # Allocation contract
//
// AppendBinary allocates only to grow dst and t.
func AppendBinary(dst []byte, s symbol.Symbol, t *StringTable) ([]byte, error) {
	w := binaryWriter{buf: dst, t: t}
	if err := w.symbol(s); err != nil {
		return dst, err
	}
	return w.buf, nil
}

// DecodeBinary decodes one symbol [AppendBinary] wrote at the start of b
// against t, and returns it with the number of bytes it read. A zero
// byte decodes to a nil symbol. t is the table the encoding numbered
// its strings in, and nil for an encoding written without one.
//
// Error modes: an error wrapping [ErrMalformed] where b ends inside
// the encoding, names a kind the model does not declare, places a kind
// in a field that admits another, states a bool other than zero or one,
// names a string t does not contain, or states a list longer than the
// bytes left. Nothing else comes back with the error.
//
// # Allocation contract
//
// DecodeBinary allocates each declaration and each non-empty list of
// the subtree once. A string decoded against a table is a string of the
// table and allocates nothing, and one decoded without a table
// allocates once.
func DecodeBinary(b []byte, t *StringTable) (symbol.Symbol, int, error) {
	r := binaryReader{Decoder: wire.NewDecoder(b), t: t}
	s := r.symbol()
	if err := r.Err(); err != nil {
		return nil, 0, err
	}
	return s, r.Read(), nil
}

// symbol writes any symbol behind its kind, and a zero byte for nil.
func (w *binaryWriter) symbol(s symbol.Symbol) error {
	switch x := s.(type) {
	case nil:
		w.kind(symbol.KindInvalid)
		return nil
	case *Function:
		w.encodeFunction(x)
		return nil
	case *Method:
		w.encodeMethod(x)
		return nil
	case *Param:
		w.encodeParam(x)
		return nil
	case *Return:
		w.encodeReturn(x)
		return nil
	case *Package:
		return w.encodePackage(x)
	case *File:
		return w.encodeFile(x)
	case *Import:
		w.encodeImport(x)
		return nil
	case *Export:
		w.encodeExport(x)
		return nil
	case *Binding:
		w.encodeBinding(x)
		return nil
	case *Enum:
		w.encodeEnum(x)
		return nil
	case *EnumVariant:
		w.encodeEnumVariant(x)
		return nil
	case *Sum:
		w.encodeSum(x)
		return nil
	case *SumVariant:
		w.encodeSumVariant(x)
		return nil
	case *Field:
		w.encodeField(x)
		return nil
	case *Variable:
		w.encodeVariable(x)
		return nil
	case *Constant:
		w.encodeConstant(x)
		return nil
	case *Struct:
		return w.encodeStruct(x)
	case *Interface:
		return w.encodeInterface(x)
	case *Alias:
		w.encodeAlias(x)
		return nil
	case *TypeRef:
		w.encodeTypeRef(x)
		return nil
	case *TypeParam:
		w.encodeTypeParam(x)
		return nil
	case *Embed:
		w.encodeEmbed(x)
		return nil
	default:
		return fmt.Errorf("node: encode %v: %T is not a kind of the model", s.Kind(), s)
	}
}

// symbol reads any symbol by the kind in front of it.
func (r *binaryReader) symbol() symbol.Symbol {
	switch k := r.kind(); k {
	case symbol.KindInvalid:
		return nil
	case symbol.KindFunction:
		return r.decodeFunction()
	case symbol.KindMethod:
		return r.decodeMethod()
	case symbol.KindParam:
		return r.decodeParam()
	case symbol.KindReturn:
		return r.decodeReturn()
	case symbol.KindPackage:
		return r.decodePackage()
	case symbol.KindFile:
		return r.decodeFile()
	case symbol.KindImport:
		return r.decodeImport()
	case symbol.KindExport:
		return r.decodeExport()
	case symbol.KindBinding:
		return r.decodeBinding()
	case symbol.KindEnum:
		return r.decodeEnum()
	case symbol.KindEnumVariant:
		return r.decodeEnumVariant()
	case symbol.KindSum:
		return r.decodeSum()
	case symbol.KindSumVariant:
		return r.decodeSumVariant()
	case symbol.KindField:
		return r.decodeField()
	case symbol.KindVariable:
		return r.decodeVariable()
	case symbol.KindConstant:
		return r.decodeConstant()
	case symbol.KindStruct:
		return r.decodeStruct()
	case symbol.KindInterface:
		return r.decodeInterface()
	case symbol.KindAlias:
		return r.decodeAlias()
	case symbol.KindTypeRef:
		return r.decodeTypeRef()
	case symbol.KindTypeParam:
		return r.decodeTypeParam()
	case symbol.KindEmbed:
		return r.decodeEmbed()
	default:
		r.Fail(fmt.Errorf("node: decode: %w: kind %d at byte %d is not a kind of the model",
			ErrMalformed, k, r.Read()-1))
		return nil
	}
}

// ref reads a symbol into a field that admits one kind: the zero value
// for a nil symbol, and a failure for a symbol of another kind.
func ref[T symbol.Symbol](r *binaryReader) T {
	var zero T
	s := r.symbol()
	if s == nil {
		return zero
	}
	typed, admitted := s.(T)
	if !admitted {
		r.Fail(fmt.Errorf("node: decode: %w: a %v ends at byte %d in a field that admits %T",
			ErrMalformed, s.Kind(), r.Read(), zero))
	}
	return typed
}

// encodeFunction writes one Function behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeFunction(x *Function) {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return
	}
	w.kind(symbol.KindFunction)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.strs(x.Doc)
	w.str(x.Comment)
	w.str(x.Name)
	w.unsigned(uint64(x.Visibility))
	w.boolean(x.Async)
	w.unsigned(uint64(len(x.TypeParams)))
	for _, child := range x.TypeParams {
		w.encodeTypeParam(child)
	}
	w.unsigned(uint64(len(x.Params)))
	for _, child := range x.Params {
		w.encodeParam(child)
	}
	w.unsigned(uint64(len(x.Returns)))
	for _, child := range x.Returns {
		w.encodeReturn(child)
	}
	w.unsigned(uint64(len(x.Throws)))
	for _, child := range x.Throws {
		w.encodeTypeRef(child)
	}
	w.annotations(x.Annotations)
}

// decodeFunction reads the fields of one Function, the kind in front
// of them already read.
func (r *binaryReader) decodeFunction() *Function {
	x := &Function{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Doc = r.strs()
	x.Comment = r.str()
	x.Name = r.str()
	x.Visibility = symbol.Visibility(r.unsigned())
	x.Async = r.boolean()
	if n := r.count(); n > 0 {
		x.TypeParams = make([]*TypeParam, n)
		for i := range x.TypeParams {
			x.TypeParams[i] = ref[*TypeParam](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Params = make([]*Param, n)
		for i := range x.Params {
			x.Params[i] = ref[*Param](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Returns = make([]*Return, n)
		for i := range x.Returns {
			x.Returns[i] = ref[*Return](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Throws = make([]*TypeRef, n)
		for i := range x.Throws {
			x.Throws[i] = ref[*TypeRef](r)
		}
	}
	x.Annotations = r.annotations()
	return x
}

// encodeMethod writes one Method behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeMethod(x *Method) {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return
	}
	w.kind(symbol.KindMethod)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.strs(x.Doc)
	w.str(x.Comment)
	w.str(x.Name)
	w.unsigned(uint64(x.Visibility))
	w.unsigned(uint64(x.Level))
	w.boolean(x.Abstract)
	w.boolean(x.Final)
	w.boolean(x.Override)
	w.boolean(x.HasDefault)
	w.boolean(x.Async)
	w.unsigned(uint64(x.Accessor))
	w.boolean(x.Indexer)
	w.boolean(x.Constructs)
	w.boolean(x.Hard)
	w.encodeParam(x.Receiver)
	w.encodeTypeRef(x.Receives)
	w.unsigned(uint64(len(x.TypeParams)))
	for _, child := range x.TypeParams {
		w.encodeTypeParam(child)
	}
	w.unsigned(uint64(len(x.Params)))
	for _, child := range x.Params {
		w.encodeParam(child)
	}
	w.unsigned(uint64(len(x.Returns)))
	for _, child := range x.Returns {
		w.encodeReturn(child)
	}
	w.unsigned(uint64(len(x.Throws)))
	for _, child := range x.Throws {
		w.encodeTypeRef(child)
	}
	w.annotations(x.Annotations)
	w.identity(x.Host)
}

// decodeMethod reads the fields of one Method, the kind in front
// of them already read.
func (r *binaryReader) decodeMethod() *Method {
	x := &Method{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Doc = r.strs()
	x.Comment = r.str()
	x.Name = r.str()
	x.Visibility = symbol.Visibility(r.unsigned())
	x.Level = symbol.Level(r.unsigned())
	x.Abstract = r.boolean()
	x.Final = r.boolean()
	x.Override = r.boolean()
	x.HasDefault = r.boolean()
	x.Async = r.boolean()
	x.Accessor = symbol.Accessor(r.unsigned())
	x.Indexer = r.boolean()
	x.Constructs = r.boolean()
	x.Hard = r.boolean()
	x.Receiver = ref[*Param](r)
	x.Receives = ref[*TypeRef](r)
	if n := r.count(); n > 0 {
		x.TypeParams = make([]*TypeParam, n)
		for i := range x.TypeParams {
			x.TypeParams[i] = ref[*TypeParam](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Params = make([]*Param, n)
		for i := range x.Params {
			x.Params[i] = ref[*Param](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Returns = make([]*Return, n)
		for i := range x.Returns {
			x.Returns[i] = ref[*Return](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Throws = make([]*TypeRef, n)
		for i := range x.Throws {
			x.Throws[i] = ref[*TypeRef](r)
		}
	}
	x.Annotations = r.annotations()
	x.Host = r.identity()
	return x
}

// encodeParam writes one Param behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeParam(x *Param) {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return
	}
	w.kind(symbol.KindParam)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.str(x.Comment)
	w.str(x.Name)
	w.str(x.Label)
	w.encodeTypeRef(x.Type)
	w.str(x.Default)
	w.boolean(x.Optional)
	w.unsigned(uint64(x.Variadic))
	w.annotations(x.Annotations)
}

// decodeParam reads the fields of one Param, the kind in front
// of them already read.
func (r *binaryReader) decodeParam() *Param {
	x := &Param{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Comment = r.str()
	x.Name = r.str()
	x.Label = r.str()
	x.Type = ref[*TypeRef](r)
	x.Default = r.str()
	x.Optional = r.boolean()
	x.Variadic = symbol.Variadic(r.unsigned())
	x.Annotations = r.annotations()
	return x
}

// encodeReturn writes one Return behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeReturn(x *Return) {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return
	}
	w.kind(symbol.KindReturn)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.str(x.Comment)
	w.str(x.Name)
	w.encodeTypeRef(x.Type)
}

// decodeReturn reads the fields of one Return, the kind in front
// of them already read.
func (r *binaryReader) decodeReturn() *Return {
	x := &Return{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Comment = r.str()
	x.Name = r.str()
	x.Type = ref[*TypeRef](r)
	return x
}

// encodePackage writes one Package behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodePackage(x *Package) error {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return nil
	}
	w.kind(symbol.KindPackage)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.strs(x.Doc)
	w.strs(x.Path)
	w.str(x.Name)
	w.unsigned(uint64(len(x.Files)))
	for _, child := range x.Files {
		if err := w.encodeFile(child); err != nil {
			return err
		}
	}
	return nil
}

// decodePackage reads the fields of one Package, the kind in front
// of them already read.
func (r *binaryReader) decodePackage() *Package {
	x := &Package{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Doc = r.strs()
	x.Path = r.strs()
	x.Name = r.str()
	if n := r.count(); n > 0 {
		x.Files = make([]*File, n)
		for i := range x.Files {
			x.Files[i] = ref[*File](r)
		}
	}
	return x
}

// encodeFile writes one File behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeFile(x *File) error {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return nil
	}
	w.kind(symbol.KindFile)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.strs(x.Doc)
	w.str(x.Path)
	w.annotations(x.Annotations)
	w.unsigned(uint64(len(x.Imports)))
	for _, child := range x.Imports {
		w.encodeImport(child)
	}
	w.unsigned(uint64(len(x.Exports)))
	for _, child := range x.Exports {
		w.encodeExport(child)
	}
	w.unsigned(uint64(len(x.Decls)))
	for _, child := range x.Decls {
		if err := w.symbol(child); err != nil {
			return err
		}
	}
	return nil
}

// decodeFile reads the fields of one File, the kind in front
// of them already read.
func (r *binaryReader) decodeFile() *File {
	x := &File{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Doc = r.strs()
	x.Path = r.str()
	x.Annotations = r.annotations()
	if n := r.count(); n > 0 {
		x.Imports = make([]*Import, n)
		for i := range x.Imports {
			x.Imports[i] = ref[*Import](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Exports = make([]*Export, n)
		for i := range x.Exports {
			x.Exports[i] = ref[*Export](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Decls = make(Symbols, n)
		for i := range x.Decls {
			x.Decls[i] = r.symbol()
		}
	}
	return x
}

// encodeImport writes one Import behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeImport(x *Import) {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return
	}
	w.kind(symbol.KindImport)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.strs(x.Doc)
	w.str(x.Comment)
	w.str(x.Path)
	w.str(x.Alias)
	w.unsigned(uint64(len(x.Names)))
	for _, child := range x.Names {
		w.encodeBinding(child)
	}
	w.str(x.Default)
	w.boolean(x.Wildcard)
}

// decodeImport reads the fields of one Import, the kind in front
// of them already read.
func (r *binaryReader) decodeImport() *Import {
	x := &Import{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Doc = r.strs()
	x.Comment = r.str()
	x.Path = r.str()
	x.Alias = r.str()
	if n := r.count(); n > 0 {
		x.Names = make([]*Binding, n)
		for i := range x.Names {
			x.Names[i] = ref[*Binding](r)
		}
	}
	x.Default = r.str()
	x.Wildcard = r.boolean()
	return x
}

// encodeExport writes one Export behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeExport(x *Export) {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return
	}
	w.kind(symbol.KindExport)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.strs(x.Doc)
	w.str(x.Path)
	w.unsigned(uint64(len(x.Names)))
	for _, child := range x.Names {
		w.encodeBinding(child)
	}
	w.str(x.Default)
	w.boolean(x.Wildcard)
}

// decodeExport reads the fields of one Export, the kind in front
// of them already read.
func (r *binaryReader) decodeExport() *Export {
	x := &Export{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Doc = r.strs()
	x.Path = r.str()
	if n := r.count(); n > 0 {
		x.Names = make([]*Binding, n)
		for i := range x.Names {
			x.Names[i] = ref[*Binding](r)
		}
	}
	x.Default = r.str()
	x.Wildcard = r.boolean()
	return x
}

// encodeBinding writes one Binding behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeBinding(x *Binding) {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return
	}
	w.kind(symbol.KindBinding)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.str(x.Name)
	w.str(x.Alias)
	w.identity(x.Host)
}

// decodeBinding reads the fields of one Binding, the kind in front
// of them already read.
func (r *binaryReader) decodeBinding() *Binding {
	x := &Binding{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Name = r.str()
	x.Alias = r.str()
	x.Host = r.identity()
	return x
}

// encodeEnum writes one Enum behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeEnum(x *Enum) {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return
	}
	w.kind(symbol.KindEnum)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.strs(x.Doc)
	w.str(x.Comment)
	w.str(x.Name)
	w.unsigned(uint64(x.Visibility))
	w.boolean(x.Const)
	w.unsigned(uint64(len(x.Variants)))
	for _, child := range x.Variants {
		w.encodeEnumVariant(child)
	}
	w.unsigned(uint64(len(x.Fields)))
	for _, child := range x.Fields {
		w.encodeField(child)
	}
	w.unsigned(uint64(len(x.Methods)))
	for _, child := range x.Methods {
		w.encodeMethod(child)
	}
	w.annotations(x.Annotations)
}

// decodeEnum reads the fields of one Enum, the kind in front
// of them already read.
func (r *binaryReader) decodeEnum() *Enum {
	x := &Enum{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Doc = r.strs()
	x.Comment = r.str()
	x.Name = r.str()
	x.Visibility = symbol.Visibility(r.unsigned())
	x.Const = r.boolean()
	if n := r.count(); n > 0 {
		x.Variants = make([]*EnumVariant, n)
		for i := range x.Variants {
			x.Variants[i] = ref[*EnumVariant](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Fields = make([]*Field, n)
		for i := range x.Fields {
			x.Fields[i] = ref[*Field](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Methods = make([]*Method, n)
		for i := range x.Methods {
			x.Methods[i] = ref[*Method](r)
		}
	}
	x.Annotations = r.annotations()
	return x
}

// encodeEnumVariant writes one EnumVariant behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeEnumVariant(x *EnumVariant) {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return
	}
	w.kind(symbol.KindEnumVariant)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.strs(x.Doc)
	w.str(x.Comment)
	w.str(x.Name)
	w.str(x.Value)
	w.annotations(x.Annotations)
	w.identity(x.Host)
}

// decodeEnumVariant reads the fields of one EnumVariant, the kind in front
// of them already read.
func (r *binaryReader) decodeEnumVariant() *EnumVariant {
	x := &EnumVariant{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Doc = r.strs()
	x.Comment = r.str()
	x.Name = r.str()
	x.Value = r.str()
	x.Annotations = r.annotations()
	x.Host = r.identity()
	return x
}

// encodeSum writes one Sum behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeSum(x *Sum) {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return
	}
	w.kind(symbol.KindSum)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.strs(x.Doc)
	w.str(x.Comment)
	w.str(x.Name)
	w.unsigned(uint64(x.Visibility))
	w.unsigned(uint64(len(x.TypeParams)))
	for _, child := range x.TypeParams {
		w.encodeTypeParam(child)
	}
	w.unsigned(uint64(len(x.Variants)))
	for _, child := range x.Variants {
		w.encodeSumVariant(child)
	}
	w.unsigned(uint64(len(x.Methods)))
	for _, child := range x.Methods {
		w.encodeMethod(child)
	}
	w.annotations(x.Annotations)
}

// decodeSum reads the fields of one Sum, the kind in front
// of them already read.
func (r *binaryReader) decodeSum() *Sum {
	x := &Sum{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Doc = r.strs()
	x.Comment = r.str()
	x.Name = r.str()
	x.Visibility = symbol.Visibility(r.unsigned())
	if n := r.count(); n > 0 {
		x.TypeParams = make([]*TypeParam, n)
		for i := range x.TypeParams {
			x.TypeParams[i] = ref[*TypeParam](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Variants = make([]*SumVariant, n)
		for i := range x.Variants {
			x.Variants[i] = ref[*SumVariant](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Methods = make([]*Method, n)
		for i := range x.Methods {
			x.Methods[i] = ref[*Method](r)
		}
	}
	x.Annotations = r.annotations()
	return x
}

// encodeSumVariant writes one SumVariant behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeSumVariant(x *SumVariant) {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return
	}
	w.kind(symbol.KindSumVariant)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.strs(x.Doc)
	w.str(x.Comment)
	w.str(x.Name)
	w.unsigned(uint64(len(x.Fields)))
	for _, child := range x.Fields {
		w.encodeField(child)
	}
	w.annotations(x.Annotations)
	w.identity(x.Host)
}

// decodeSumVariant reads the fields of one SumVariant, the kind in front
// of them already read.
func (r *binaryReader) decodeSumVariant() *SumVariant {
	x := &SumVariant{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Doc = r.strs()
	x.Comment = r.str()
	x.Name = r.str()
	if n := r.count(); n > 0 {
		x.Fields = make([]*Field, n)
		for i := range x.Fields {
			x.Fields[i] = ref[*Field](r)
		}
	}
	x.Annotations = r.annotations()
	x.Host = r.identity()
	return x
}

// encodeField writes one Field behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeField(x *Field) {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return
	}
	w.kind(symbol.KindField)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.strs(x.Doc)
	w.str(x.Comment)
	w.str(x.Name)
	w.unsigned(uint64(x.Visibility))
	w.unsigned(uint64(x.Level))
	w.unsigned(uint64(x.Mutability))
	w.boolean(x.Hard)
	w.boolean(x.Optional)
	w.encodeTypeRef(x.Type)
	w.str(x.Value)
	w.str(x.Tag)
	w.annotations(x.Annotations)
	w.identity(x.Host)
}

// decodeField reads the fields of one Field, the kind in front
// of them already read.
func (r *binaryReader) decodeField() *Field {
	x := &Field{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Doc = r.strs()
	x.Comment = r.str()
	x.Name = r.str()
	x.Visibility = symbol.Visibility(r.unsigned())
	x.Level = symbol.Level(r.unsigned())
	x.Mutability = symbol.Mutability(r.unsigned())
	x.Hard = r.boolean()
	x.Optional = r.boolean()
	x.Type = ref[*TypeRef](r)
	x.Value = r.str()
	x.Tag = r.str()
	x.Annotations = r.annotations()
	x.Host = r.identity()
	return x
}

// encodeVariable writes one Variable behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeVariable(x *Variable) {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return
	}
	w.kind(symbol.KindVariable)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.strs(x.Doc)
	w.str(x.Comment)
	w.str(x.Name)
	w.unsigned(uint64(x.Visibility))
	w.unsigned(uint64(x.Mutability))
	w.encodeTypeRef(x.Type)
	w.str(x.Value)
	w.annotations(x.Annotations)
}

// decodeVariable reads the fields of one Variable, the kind in front
// of them already read.
func (r *binaryReader) decodeVariable() *Variable {
	x := &Variable{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Doc = r.strs()
	x.Comment = r.str()
	x.Name = r.str()
	x.Visibility = symbol.Visibility(r.unsigned())
	x.Mutability = symbol.Mutability(r.unsigned())
	x.Type = ref[*TypeRef](r)
	x.Value = r.str()
	x.Annotations = r.annotations()
	return x
}

// encodeConstant writes one Constant behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeConstant(x *Constant) {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return
	}
	w.kind(symbol.KindConstant)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.strs(x.Doc)
	w.str(x.Comment)
	w.str(x.Name)
	w.unsigned(uint64(x.Visibility))
	w.encodeTypeRef(x.Type)
	w.str(x.Value)
	w.annotations(x.Annotations)
}

// decodeConstant reads the fields of one Constant, the kind in front
// of them already read.
func (r *binaryReader) decodeConstant() *Constant {
	x := &Constant{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Doc = r.strs()
	x.Comment = r.str()
	x.Name = r.str()
	x.Visibility = symbol.Visibility(r.unsigned())
	x.Type = ref[*TypeRef](r)
	x.Value = r.str()
	x.Annotations = r.annotations()
	return x
}

// encodeStruct writes one Struct behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeStruct(x *Struct) error {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return nil
	}
	w.kind(symbol.KindStruct)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.strs(x.Doc)
	w.str(x.Comment)
	w.str(x.Name)
	w.unsigned(uint64(x.Visibility))
	w.unsigned(uint64(x.Level))
	w.boolean(x.Abstract)
	w.boolean(x.Final)
	w.boolean(x.Sealed)
	w.unsigned(uint64(len(x.TypeParams)))
	for _, child := range x.TypeParams {
		w.encodeTypeParam(child)
	}
	w.unsigned(uint64(len(x.Fields)))
	for _, child := range x.Fields {
		w.encodeField(child)
	}
	w.unsigned(uint64(len(x.Methods)))
	for _, child := range x.Methods {
		w.encodeMethod(child)
	}
	w.unsigned(uint64(len(x.Types)))
	for _, child := range x.Types {
		if err := w.symbol(child); err != nil {
			return err
		}
	}
	w.unsigned(uint64(len(x.Embeds)))
	for _, child := range x.Embeds {
		w.encodeEmbed(child)
	}
	w.unsigned(uint64(len(x.Extends)))
	for _, child := range x.Extends {
		w.encodeTypeRef(child)
	}
	w.unsigned(uint64(len(x.Implements)))
	for _, child := range x.Implements {
		w.encodeTypeRef(child)
	}
	w.unsigned(uint64(len(x.Permits)))
	for _, child := range x.Permits {
		w.encodeTypeRef(child)
	}
	w.annotations(x.Annotations)
	return nil
}

// decodeStruct reads the fields of one Struct, the kind in front
// of them already read.
func (r *binaryReader) decodeStruct() *Struct {
	x := &Struct{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Doc = r.strs()
	x.Comment = r.str()
	x.Name = r.str()
	x.Visibility = symbol.Visibility(r.unsigned())
	x.Level = symbol.Level(r.unsigned())
	x.Abstract = r.boolean()
	x.Final = r.boolean()
	x.Sealed = r.boolean()
	if n := r.count(); n > 0 {
		x.TypeParams = make([]*TypeParam, n)
		for i := range x.TypeParams {
			x.TypeParams[i] = ref[*TypeParam](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Fields = make([]*Field, n)
		for i := range x.Fields {
			x.Fields[i] = ref[*Field](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Methods = make([]*Method, n)
		for i := range x.Methods {
			x.Methods[i] = ref[*Method](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Types = make(Symbols, n)
		for i := range x.Types {
			x.Types[i] = r.symbol()
		}
	}
	if n := r.count(); n > 0 {
		x.Embeds = make([]*Embed, n)
		for i := range x.Embeds {
			x.Embeds[i] = ref[*Embed](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Extends = make([]*TypeRef, n)
		for i := range x.Extends {
			x.Extends[i] = ref[*TypeRef](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Implements = make([]*TypeRef, n)
		for i := range x.Implements {
			x.Implements[i] = ref[*TypeRef](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Permits = make([]*TypeRef, n)
		for i := range x.Permits {
			x.Permits[i] = ref[*TypeRef](r)
		}
	}
	x.Annotations = r.annotations()
	return x
}

// encodeInterface writes one Interface behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeInterface(x *Interface) error {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return nil
	}
	w.kind(symbol.KindInterface)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.strs(x.Doc)
	w.str(x.Comment)
	w.str(x.Name)
	w.unsigned(uint64(x.Visibility))
	w.boolean(x.Sealed)
	w.unsigned(uint64(len(x.TypeParams)))
	for _, child := range x.TypeParams {
		w.encodeTypeParam(child)
	}
	w.unsigned(uint64(len(x.Fields)))
	for _, child := range x.Fields {
		w.encodeField(child)
	}
	w.unsigned(uint64(len(x.Methods)))
	for _, child := range x.Methods {
		w.encodeMethod(child)
	}
	w.unsigned(uint64(len(x.Types)))
	for _, child := range x.Types {
		if err := w.symbol(child); err != nil {
			return err
		}
	}
	w.unsigned(uint64(len(x.Embeds)))
	for _, child := range x.Embeds {
		w.encodeEmbed(child)
	}
	w.unsigned(uint64(len(x.Extends)))
	for _, child := range x.Extends {
		w.encodeTypeRef(child)
	}
	w.unsigned(uint64(len(x.Permits)))
	for _, child := range x.Permits {
		w.encodeTypeRef(child)
	}
	w.annotations(x.Annotations)
	return nil
}

// decodeInterface reads the fields of one Interface, the kind in front
// of them already read.
func (r *binaryReader) decodeInterface() *Interface {
	x := &Interface{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Doc = r.strs()
	x.Comment = r.str()
	x.Name = r.str()
	x.Visibility = symbol.Visibility(r.unsigned())
	x.Sealed = r.boolean()
	if n := r.count(); n > 0 {
		x.TypeParams = make([]*TypeParam, n)
		for i := range x.TypeParams {
			x.TypeParams[i] = ref[*TypeParam](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Fields = make([]*Field, n)
		for i := range x.Fields {
			x.Fields[i] = ref[*Field](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Methods = make([]*Method, n)
		for i := range x.Methods {
			x.Methods[i] = ref[*Method](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Types = make(Symbols, n)
		for i := range x.Types {
			x.Types[i] = r.symbol()
		}
	}
	if n := r.count(); n > 0 {
		x.Embeds = make([]*Embed, n)
		for i := range x.Embeds {
			x.Embeds[i] = ref[*Embed](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Extends = make([]*TypeRef, n)
		for i := range x.Extends {
			x.Extends[i] = ref[*TypeRef](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Permits = make([]*TypeRef, n)
		for i := range x.Permits {
			x.Permits[i] = ref[*TypeRef](r)
		}
	}
	x.Annotations = r.annotations()
	return x
}

// encodeAlias writes one Alias behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeAlias(x *Alias) {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return
	}
	w.kind(symbol.KindAlias)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.strs(x.Doc)
	w.str(x.Comment)
	w.str(x.Name)
	w.unsigned(uint64(x.Visibility))
	w.boolean(x.Defined)
	w.unsigned(uint64(len(x.TypeParams)))
	for _, child := range x.TypeParams {
		w.encodeTypeParam(child)
	}
	w.encodeTypeRef(x.Target)
	w.annotations(x.Annotations)
}

// decodeAlias reads the fields of one Alias, the kind in front
// of them already read.
func (r *binaryReader) decodeAlias() *Alias {
	x := &Alias{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Doc = r.strs()
	x.Comment = r.str()
	x.Name = r.str()
	x.Visibility = symbol.Visibility(r.unsigned())
	x.Defined = r.boolean()
	if n := r.count(); n > 0 {
		x.TypeParams = make([]*TypeParam, n)
		for i := range x.TypeParams {
			x.TypeParams[i] = ref[*TypeParam](r)
		}
	}
	x.Target = ref[*TypeRef](r)
	x.Annotations = r.annotations()
	return x
}

// encodeTypeRef writes one TypeRef behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeTypeRef(x *TypeRef) {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return
	}
	w.kind(symbol.KindTypeRef)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.str(x.Spelling)
	w.identity(x.Target)
	w.str(x.Package)
	w.unsigned(uint64(x.Form))
	w.unsigned(uint64(len(x.Elems)))
	for _, child := range x.Elems {
		w.encodeTypeRef(child)
	}
	w.integer(x.Split)
	w.integer(x.Length)
	w.unsigned(uint64(x.Variance))
	w.boolean(x.Async)
	w.unsigned(uint64(len(x.Args)))
	for _, child := range x.Args {
		w.encodeTypeRef(child)
	}
	w.unsigned(uint64(len(x.Fields)))
	for _, child := range x.Fields {
		w.encodeField(child)
	}
	w.unsigned(uint64(len(x.Methods)))
	for _, child := range x.Methods {
		w.encodeMethod(child)
	}
}

// decodeTypeRef reads the fields of one TypeRef, the kind in front
// of them already read.
func (r *binaryReader) decodeTypeRef() *TypeRef {
	x := &TypeRef{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Spelling = r.str()
	x.Target = r.identity()
	x.Package = r.str()
	x.Form = symbol.TypeForm(r.unsigned())
	if n := r.count(); n > 0 {
		x.Elems = make([]*TypeRef, n)
		for i := range x.Elems {
			x.Elems[i] = ref[*TypeRef](r)
		}
	}
	x.Split = r.integer()
	x.Length = r.integer()
	x.Variance = symbol.Variance(r.unsigned())
	x.Async = r.boolean()
	if n := r.count(); n > 0 {
		x.Args = make([]*TypeRef, n)
		for i := range x.Args {
			x.Args[i] = ref[*TypeRef](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Fields = make([]*Field, n)
		for i := range x.Fields {
			x.Fields[i] = ref[*Field](r)
		}
	}
	if n := r.count(); n > 0 {
		x.Methods = make([]*Method, n)
		for i := range x.Methods {
			x.Methods[i] = ref[*Method](r)
		}
	}
	return x
}

// encodeTypeParam writes one TypeParam behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeTypeParam(x *TypeParam) {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return
	}
	w.kind(symbol.KindTypeParam)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.str(x.Name)
	w.unsigned(uint64(x.Variance))
	w.unsigned(uint64(len(x.Bounds)))
	for _, child := range x.Bounds {
		w.encodeTypeRef(child)
	}
	w.encodeTypeRef(x.Default)
	w.boolean(x.Const)
	w.encodeTypeRef(x.Type)
	w.str(x.DefaultValue)
}

// decodeTypeParam reads the fields of one TypeParam, the kind in front
// of them already read.
func (r *binaryReader) decodeTypeParam() *TypeParam {
	x := &TypeParam{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Name = r.str()
	x.Variance = symbol.Variance(r.unsigned())
	if n := r.count(); n > 0 {
		x.Bounds = make([]*TypeRef, n)
		for i := range x.Bounds {
			x.Bounds[i] = ref[*TypeRef](r)
		}
	}
	x.Default = ref[*TypeRef](r)
	x.Const = r.boolean()
	x.Type = ref[*TypeRef](r)
	x.DefaultValue = r.str()
	return x
}

// encodeEmbed writes one Embed behind its kind, and a zero byte
// for nil.
func (w *binaryWriter) encodeEmbed(x *Embed) {
	if x == nil {
		w.kind(symbol.KindInvalid)
		return
	}
	w.kind(symbol.KindEmbed)
	w.identity(x.ID)
	w.pos(x.Pos)
	w.strs(x.Doc)
	w.str(x.Comment)
	w.encodeTypeRef(x.Ref)
	w.str(x.Tag)
	w.annotations(x.Annotations)
	w.identity(x.Host)
}

// decodeEmbed reads the fields of one Embed, the kind in front
// of them already read.
func (r *binaryReader) decodeEmbed() *Embed {
	x := &Embed{}
	x.ID = r.identity()
	x.Pos = r.pos()
	x.Doc = r.strs()
	x.Comment = r.str()
	x.Ref = ref[*TypeRef](r)
	x.Tag = r.str()
	x.Annotations = r.annotations()
	x.Host = r.identity()
	return x
}
