// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/model. DO NOT EDIT.

package node

// ModelFingerprint identifies the node model's shape: a sha256 over
// every kind and node-side field the schema declares, hex-spelled.
//
// Every unit key folds it, because a schema change reshapes the
// graph the same source produces: a graph recorded under one shape
// must not be served under another. The hash reads the lowered
// schema rather than the rendered files, so a documentation edit
// does not change it.
const ModelFingerprint = "4db6cba83c1ef4aa1f9d3458a4acc599606dbb0cb4227a52532a9bb56683a03e"
