// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: MIT

// Code generated by internal/gen/model. DO NOT EDIT.

package node

import (
	"testing"

	"go.dokimi.dev/assert"
	"go.dokimi.dev/eidos/core/position"
	"go.dokimi.dev/eidos/core/symbol"
)

func TestWalk(t *testing.T) {
	t.Parallel()

	t.Run("Walk", func(t *testing.T) {
		t.Parallel()

		t.Run("visits nothing for a nil declaration", func(t *testing.T) {
			t.Parallel()

			Walk(nil, func(symbol.Symbol) bool {
				assert.True(t, false, "visit is never called for a nil declaration")
				return true
			})
		})

		t.Run("descends into every traversed field of Function", func(t *testing.T) {
			t.Parallel()

			subject := &Function{}
			subject.TypeParams = append(subject.TypeParams, &TypeParam{})
			subject.Params = append(subject.Params, &Param{})
			subject.Returns = append(subject.Returns, &Return{})

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 4,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of Method", func(t *testing.T) {
			t.Parallel()

			subject := &Method{}
			subject.Receiver = &Param{}
			subject.Receives = &TypeRef{}
			subject.TypeParams = append(subject.TypeParams, &TypeParam{})
			subject.Params = append(subject.Params, &Param{})
			subject.Returns = append(subject.Returns, &Return{})

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 6,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of Param", func(t *testing.T) {
			t.Parallel()

			subject := &Param{}
			subject.Type = &TypeRef{}

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 2,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of Return", func(t *testing.T) {
			t.Parallel()

			subject := &Return{}
			subject.Type = &TypeRef{}

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 2,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of Package", func(t *testing.T) {
			t.Parallel()

			subject := &Package{}
			subject.Files = append(subject.Files, &File{})

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 2,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of File", func(t *testing.T) {
			t.Parallel()

			subject := &File{}
			subject.Imports = append(subject.Imports, &Import{})
			subject.Exports = append(subject.Exports, &Export{})
			subject.Decls = append(subject.Decls, &File{})

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 4,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of Import", func(t *testing.T) {
			t.Parallel()

			subject := &Import{}
			subject.Names = append(subject.Names, &Binding{})

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 2,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of Export", func(t *testing.T) {
			t.Parallel()

			subject := &Export{}
			subject.Names = append(subject.Names, &Binding{})

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 2,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of Enum", func(t *testing.T) {
			t.Parallel()

			subject := &Enum{}
			subject.Variants = append(subject.Variants, &EnumVariant{})
			subject.Fields = append(subject.Fields, &Field{})
			subject.Methods = append(subject.Methods, &Method{})

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 4,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of Sum", func(t *testing.T) {
			t.Parallel()

			subject := &Sum{}
			subject.TypeParams = append(subject.TypeParams, &TypeParam{})
			subject.Variants = append(subject.Variants, &SumVariant{})
			subject.Methods = append(subject.Methods, &Method{})

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 4,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of SumVariant", func(t *testing.T) {
			t.Parallel()

			subject := &SumVariant{}
			subject.Fields = append(subject.Fields, &Field{})

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 2,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of Field", func(t *testing.T) {
			t.Parallel()

			subject := &Field{}
			subject.Type = &TypeRef{}

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 2,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of Variable", func(t *testing.T) {
			t.Parallel()

			subject := &Variable{}
			subject.Type = &TypeRef{}

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 2,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of Constant", func(t *testing.T) {
			t.Parallel()

			subject := &Constant{}
			subject.Type = &TypeRef{}

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 2,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of Struct", func(t *testing.T) {
			t.Parallel()

			subject := &Struct{}
			subject.TypeParams = append(subject.TypeParams, &TypeParam{})
			subject.Fields = append(subject.Fields, &Field{})
			subject.Methods = append(subject.Methods, &Method{})
			subject.Types = append(subject.Types, &Struct{})
			subject.Embeds = append(subject.Embeds, &Embed{})
			subject.Extends = append(subject.Extends, &TypeRef{})
			subject.Implements = append(subject.Implements, &TypeRef{})

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 8,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of Interface", func(t *testing.T) {
			t.Parallel()

			subject := &Interface{}
			subject.TypeParams = append(subject.TypeParams, &TypeParam{})
			subject.Fields = append(subject.Fields, &Field{})
			subject.Methods = append(subject.Methods, &Method{})
			subject.Types = append(subject.Types, &Interface{})
			subject.Embeds = append(subject.Embeds, &Embed{})
			subject.Extends = append(subject.Extends, &TypeRef{})

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 7,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of Alias", func(t *testing.T) {
			t.Parallel()

			subject := &Alias{}
			subject.TypeParams = append(subject.TypeParams, &TypeParam{})
			subject.Target = &TypeRef{}

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 3,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of TypeRef", func(t *testing.T) {
			t.Parallel()

			subject := &TypeRef{}
			subject.Args = append(subject.Args, &TypeRef{})

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 2,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of TypeParam", func(t *testing.T) {
			t.Parallel()

			subject := &TypeParam{}
			subject.Bounds = append(subject.Bounds, &TypeRef{})
			subject.Default = &TypeRef{}
			subject.Type = &TypeRef{}

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 4,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of Constraint", func(t *testing.T) {
			t.Parallel()

			subject := &Constraint{}
			subject.Terms = append(subject.Terms, &TypeRef{})

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 2,
				"the walk descends into every traversed field")
		})

		t.Run("descends into every traversed field of Embed", func(t *testing.T) {
			t.Parallel()

			subject := &Embed{}
			subject.Ref = &TypeRef{}

			var seen int
			Walk(subject, func(symbol.Symbol) bool {
				seen++
				return true
			})
			assert.Equal(t, seen, 2,
				"the walk descends into every traversed field")
		})

		t.Run("prunes a subtree when visit answers false", func(t *testing.T) {
			t.Parallel()

			{
				subject := &Function{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Params = append(subject.Params, &Param{})
				subject.Returns = append(subject.Returns, &Return{})
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &Method{}
				subject.Receiver = &Param{}
				subject.Receives = &TypeRef{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Params = append(subject.Params, &Param{})
				subject.Returns = append(subject.Returns, &Return{})
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &Param{}
				subject.Type = &TypeRef{}
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &Return{}
				subject.Type = &TypeRef{}
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &Package{}
				subject.Files = append(subject.Files, &File{})
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &File{}
				subject.Imports = append(subject.Imports, &Import{})
				subject.Exports = append(subject.Exports, &Export{})
				subject.Decls = append(subject.Decls, &File{})
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &Import{}
				subject.Names = append(subject.Names, &Binding{})
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &Export{}
				subject.Names = append(subject.Names, &Binding{})
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &Enum{}
				subject.Variants = append(subject.Variants, &EnumVariant{})
				subject.Fields = append(subject.Fields, &Field{})
				subject.Methods = append(subject.Methods, &Method{})
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &Sum{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Variants = append(subject.Variants, &SumVariant{})
				subject.Methods = append(subject.Methods, &Method{})
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &SumVariant{}
				subject.Fields = append(subject.Fields, &Field{})
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &Field{}
				subject.Type = &TypeRef{}
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &Variable{}
				subject.Type = &TypeRef{}
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &Constant{}
				subject.Type = &TypeRef{}
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &Struct{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Fields = append(subject.Fields, &Field{})
				subject.Methods = append(subject.Methods, &Method{})
				subject.Types = append(subject.Types, &Struct{})
				subject.Embeds = append(subject.Embeds, &Embed{})
				subject.Extends = append(subject.Extends, &TypeRef{})
				subject.Implements = append(subject.Implements, &TypeRef{})
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &Interface{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Fields = append(subject.Fields, &Field{})
				subject.Methods = append(subject.Methods, &Method{})
				subject.Types = append(subject.Types, &Interface{})
				subject.Embeds = append(subject.Embeds, &Embed{})
				subject.Extends = append(subject.Extends, &TypeRef{})
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &Alias{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Target = &TypeRef{}
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &TypeRef{}
				subject.Args = append(subject.Args, &TypeRef{})
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &TypeParam{}
				subject.Bounds = append(subject.Bounds, &TypeRef{})
				subject.Default = &TypeRef{}
				subject.Type = &TypeRef{}
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &Constraint{}
				subject.Terms = append(subject.Terms, &TypeRef{})
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}

			{
				subject := &Embed{}
				subject.Ref = &TypeRef{}
				var seen int
				Walk(subject, func(symbol.Symbol) bool {
					seen++
					return false
				})
				assert.Equal(t, seen, 1,
					"answering false prunes the subtree")
			}
		})
	})

	t.Run("All", func(t *testing.T) {
		t.Parallel()

		t.Run("yields the same declarations as Walk", func(t *testing.T) {
			t.Parallel()

			{
				subject := &Function{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Params = append(subject.Params, &Param{})
				subject.Returns = append(subject.Returns, &Return{})
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &Method{}
				subject.Receiver = &Param{}
				subject.Receives = &TypeRef{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Params = append(subject.Params, &Param{})
				subject.Returns = append(subject.Returns, &Return{})
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &Param{}
				subject.Type = &TypeRef{}
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &Return{}
				subject.Type = &TypeRef{}
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &Package{}
				subject.Files = append(subject.Files, &File{})
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &File{}
				subject.Imports = append(subject.Imports, &Import{})
				subject.Exports = append(subject.Exports, &Export{})
				subject.Decls = append(subject.Decls, &File{})
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &Import{}
				subject.Names = append(subject.Names, &Binding{})
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &Export{}
				subject.Names = append(subject.Names, &Binding{})
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &Enum{}
				subject.Variants = append(subject.Variants, &EnumVariant{})
				subject.Fields = append(subject.Fields, &Field{})
				subject.Methods = append(subject.Methods, &Method{})
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &Sum{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Variants = append(subject.Variants, &SumVariant{})
				subject.Methods = append(subject.Methods, &Method{})
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &SumVariant{}
				subject.Fields = append(subject.Fields, &Field{})
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &Field{}
				subject.Type = &TypeRef{}
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &Variable{}
				subject.Type = &TypeRef{}
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &Constant{}
				subject.Type = &TypeRef{}
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &Struct{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Fields = append(subject.Fields, &Field{})
				subject.Methods = append(subject.Methods, &Method{})
				subject.Types = append(subject.Types, &Struct{})
				subject.Embeds = append(subject.Embeds, &Embed{})
				subject.Extends = append(subject.Extends, &TypeRef{})
				subject.Implements = append(subject.Implements, &TypeRef{})
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &Interface{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Fields = append(subject.Fields, &Field{})
				subject.Methods = append(subject.Methods, &Method{})
				subject.Types = append(subject.Types, &Interface{})
				subject.Embeds = append(subject.Embeds, &Embed{})
				subject.Extends = append(subject.Extends, &TypeRef{})
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &Alias{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Target = &TypeRef{}
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &TypeRef{}
				subject.Args = append(subject.Args, &TypeRef{})
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &TypeParam{}
				subject.Bounds = append(subject.Bounds, &TypeRef{})
				subject.Default = &TypeRef{}
				subject.Type = &TypeRef{}
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &Constraint{}
				subject.Terms = append(subject.Terms, &TypeRef{})
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}

			{
				subject := &Embed{}
				subject.Ref = &TypeRef{}
				var walked int
				Walk(subject, func(symbol.Symbol) bool {
					walked++
					return true
				})
				var yielded int
				for range All(subject) {
					yielded++
				}
				assert.Equal(t, yielded, walked,
					"All yields the same declarations Walk visits")
			}
		})

		t.Run("stops when the range stops", func(t *testing.T) {
			t.Parallel()

			{
				subject := &Function{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Params = append(subject.Params, &Param{})
				subject.Returns = append(subject.Returns, &Return{})
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &Method{}
				subject.Receiver = &Param{}
				subject.Receives = &TypeRef{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Params = append(subject.Params, &Param{})
				subject.Returns = append(subject.Returns, &Return{})
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &Param{}
				subject.Type = &TypeRef{}
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &Return{}
				subject.Type = &TypeRef{}
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &Package{}
				subject.Files = append(subject.Files, &File{})
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &File{}
				subject.Imports = append(subject.Imports, &Import{})
				subject.Exports = append(subject.Exports, &Export{})
				subject.Decls = append(subject.Decls, &File{})
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &Import{}
				subject.Names = append(subject.Names, &Binding{})
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &Export{}
				subject.Names = append(subject.Names, &Binding{})
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &Enum{}
				subject.Variants = append(subject.Variants, &EnumVariant{})
				subject.Fields = append(subject.Fields, &Field{})
				subject.Methods = append(subject.Methods, &Method{})
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &Sum{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Variants = append(subject.Variants, &SumVariant{})
				subject.Methods = append(subject.Methods, &Method{})
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &SumVariant{}
				subject.Fields = append(subject.Fields, &Field{})
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &Field{}
				subject.Type = &TypeRef{}
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &Variable{}
				subject.Type = &TypeRef{}
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &Constant{}
				subject.Type = &TypeRef{}
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &Struct{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Fields = append(subject.Fields, &Field{})
				subject.Methods = append(subject.Methods, &Method{})
				subject.Types = append(subject.Types, &Struct{})
				subject.Embeds = append(subject.Embeds, &Embed{})
				subject.Extends = append(subject.Extends, &TypeRef{})
				subject.Implements = append(subject.Implements, &TypeRef{})
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &Interface{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Fields = append(subject.Fields, &Field{})
				subject.Methods = append(subject.Methods, &Method{})
				subject.Types = append(subject.Types, &Interface{})
				subject.Embeds = append(subject.Embeds, &Embed{})
				subject.Extends = append(subject.Extends, &TypeRef{})
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &Alias{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Target = &TypeRef{}
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &TypeRef{}
				subject.Args = append(subject.Args, &TypeRef{})
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &TypeParam{}
				subject.Bounds = append(subject.Bounds, &TypeRef{})
				subject.Default = &TypeRef{}
				subject.Type = &TypeRef{}
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &Constraint{}
				subject.Terms = append(subject.Terms, &TypeRef{})
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}

			{
				subject := &Embed{}
				subject.Ref = &TypeRef{}
				var yielded int
				for range All(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the iteration stops when the range stops")
			}
		})
	})

	t.Run("Declarations", func(t *testing.T) {
		t.Parallel()

		t.Run("yields every declaration All does", func(t *testing.T) {
			t.Parallel()

			{
				subject := &Function{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Params = append(subject.Params, &Param{})
				subject.Returns = append(subject.Returns, &Return{})
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &Method{}
				subject.Receiver = &Param{}
				subject.Receives = &TypeRef{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Params = append(subject.Params, &Param{})
				subject.Returns = append(subject.Returns, &Return{})
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &Param{}
				subject.Type = &TypeRef{}
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &Return{}
				subject.Type = &TypeRef{}
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &Package{}
				subject.Files = append(subject.Files, &File{})
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &File{}
				subject.Imports = append(subject.Imports, &Import{})
				subject.Exports = append(subject.Exports, &Export{})
				subject.Decls = append(subject.Decls, &File{})
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &Import{}
				subject.Names = append(subject.Names, &Binding{})
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &Export{}
				subject.Names = append(subject.Names, &Binding{})
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &Enum{}
				subject.Variants = append(subject.Variants, &EnumVariant{})
				subject.Fields = append(subject.Fields, &Field{})
				subject.Methods = append(subject.Methods, &Method{})
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &Sum{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Variants = append(subject.Variants, &SumVariant{})
				subject.Methods = append(subject.Methods, &Method{})
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &SumVariant{}
				subject.Fields = append(subject.Fields, &Field{})
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &Field{}
				subject.Type = &TypeRef{}
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &Variable{}
				subject.Type = &TypeRef{}
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &Constant{}
				subject.Type = &TypeRef{}
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &Struct{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Fields = append(subject.Fields, &Field{})
				subject.Methods = append(subject.Methods, &Method{})
				subject.Types = append(subject.Types, &Struct{})
				subject.Embeds = append(subject.Embeds, &Embed{})
				subject.Extends = append(subject.Extends, &TypeRef{})
				subject.Implements = append(subject.Implements, &TypeRef{})
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &Interface{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Fields = append(subject.Fields, &Field{})
				subject.Methods = append(subject.Methods, &Method{})
				subject.Types = append(subject.Types, &Interface{})
				subject.Embeds = append(subject.Embeds, &Embed{})
				subject.Extends = append(subject.Extends, &TypeRef{})
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &Alias{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Target = &TypeRef{}
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &TypeRef{}
				subject.Args = append(subject.Args, &TypeRef{})
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &TypeParam{}
				subject.Bounds = append(subject.Bounds, &TypeRef{})
				subject.Default = &TypeRef{}
				subject.Type = &TypeRef{}
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &Constraint{}
				subject.Terms = append(subject.Terms, &TypeRef{})
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}

			{
				subject := &Embed{}
				subject.Ref = &TypeRef{}
				var yielded int
				for range All(subject) {
					yielded++
				}
				var named int
				for range Declarations(subject) {
					named++
				}
				assert.Equal(t, named, yielded,
					"Declarations yields every declaration All does")
			}
		})

		t.Run("skips a symbol that does not name itself", func(t *testing.T) {
			t.Parallel()

			subject := &File{Decls: Symbols{unnamed{}}}
			for decl := range Declarations(subject) {
				_, isFile := decl.(*File)
				assert.True(t, isFile,
					"a symbol that does not name itself is skipped, not yielded")
			}
		})

		t.Run("stops when the range stops", func(t *testing.T) {
			t.Parallel()

			{
				subject := &Function{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Params = append(subject.Params, &Param{})
				subject.Returns = append(subject.Returns, &Return{})
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &Method{}
				subject.Receiver = &Param{}
				subject.Receives = &TypeRef{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Params = append(subject.Params, &Param{})
				subject.Returns = append(subject.Returns, &Return{})
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &Param{}
				subject.Type = &TypeRef{}
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &Return{}
				subject.Type = &TypeRef{}
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &Package{}
				subject.Files = append(subject.Files, &File{})
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &File{}
				subject.Imports = append(subject.Imports, &Import{})
				subject.Exports = append(subject.Exports, &Export{})
				subject.Decls = append(subject.Decls, &File{})
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &Import{}
				subject.Names = append(subject.Names, &Binding{})
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &Export{}
				subject.Names = append(subject.Names, &Binding{})
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &Enum{}
				subject.Variants = append(subject.Variants, &EnumVariant{})
				subject.Fields = append(subject.Fields, &Field{})
				subject.Methods = append(subject.Methods, &Method{})
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &Sum{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Variants = append(subject.Variants, &SumVariant{})
				subject.Methods = append(subject.Methods, &Method{})
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &SumVariant{}
				subject.Fields = append(subject.Fields, &Field{})
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &Field{}
				subject.Type = &TypeRef{}
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &Variable{}
				subject.Type = &TypeRef{}
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &Constant{}
				subject.Type = &TypeRef{}
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &Struct{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Fields = append(subject.Fields, &Field{})
				subject.Methods = append(subject.Methods, &Method{})
				subject.Types = append(subject.Types, &Struct{})
				subject.Embeds = append(subject.Embeds, &Embed{})
				subject.Extends = append(subject.Extends, &TypeRef{})
				subject.Implements = append(subject.Implements, &TypeRef{})
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &Interface{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Fields = append(subject.Fields, &Field{})
				subject.Methods = append(subject.Methods, &Method{})
				subject.Types = append(subject.Types, &Interface{})
				subject.Embeds = append(subject.Embeds, &Embed{})
				subject.Extends = append(subject.Extends, &TypeRef{})
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &Alias{}
				subject.TypeParams = append(subject.TypeParams, &TypeParam{})
				subject.Target = &TypeRef{}
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &TypeRef{}
				subject.Args = append(subject.Args, &TypeRef{})
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &TypeParam{}
				subject.Bounds = append(subject.Bounds, &TypeRef{})
				subject.Default = &TypeRef{}
				subject.Type = &TypeRef{}
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &Constraint{}
				subject.Terms = append(subject.Terms, &TypeRef{})
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}

			{
				subject := &Embed{}
				subject.Ref = &TypeRef{}
				var yielded int
				for range Declarations(subject) {
					yielded++
					break
				}
				assert.Equal(t, yielded, 1,
					"the typed iteration stops when the range stops")
			}
		})
	})
}

// unnamed is a symbol from outside this model: it answers the shared
// vocabulary and no identity, which is the only thing [Declarations]
// skips.
type unnamed struct{}

func (unnamed) Kind() symbol.Kind      { return symbol.KindInvalid }
func (unnamed) Position() position.Pos { return position.Pos{} }
func (unnamed) Docs() []string         { return nil }
