// Copyright Dokimasia B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/facade. DO NOT EDIT.

package toolchain_test

import (
	"reflect"
	"testing"

	"go.dokimi.dev/assert"

	core "go.dokimi.dev/eidos/core/toolchain"
	"go.dokimi.dev/eidos/sdk/toolchain"
)

// The facade re-exports go.dokimi.dev/eidos/core/toolchain: every type is the kernel's
// own type, every constant and variable equals the kernel's value,
// and every wrapper has the kernel function's signature.
func TestFacade(t *testing.T) {
	t.Parallel()

	t.Run("Generated", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[toolchain.Generated](), reflect.TypeFor[core.Generated](), "the facade aliases the kernel's type")
		})
	})

	t.Run("TestReport", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[toolchain.TestReport](), reflect.TypeFor[core.TestReport](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Adapter", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[toolchain.Adapter](), reflect.TypeFor[core.Adapter](), "the facade aliases the kernel's type")
		})
	})

	t.Run("AssertParses", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(toolchain.AssertParses), reflect.TypeOf(core.AssertParses), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("AssertTypeChecks", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(toolchain.AssertTypeChecks), reflect.TypeOf(core.AssertTypeChecks), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("AssertTestsPass", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(toolchain.AssertTestsPass), reflect.TypeOf(core.AssertTestsPass), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("AssertSatisfies", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(toolchain.AssertSatisfies), reflect.TypeOf(core.AssertSatisfies), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("AssertDoesNotSatisfy", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(toolchain.AssertDoesNotSatisfy), reflect.TypeOf(core.AssertDoesNotSatisfy), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("RequiredInCI", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(toolchain.RequiredInCI), reflect.TypeOf(core.RequiredInCI), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("Prepare", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(toolchain.Prepare), reflect.TypeOf(core.Prepare), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("TB", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[toolchain.TB](), reflect.TypeFor[core.TB](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Require", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(toolchain.Require), reflect.TypeOf(core.Require), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("Setup", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[toolchain.Setup](), reflect.TypeFor[core.Setup](), "the facade aliases the kernel's type")
		})
	})

	t.Run("RunToolchainSuite", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(toolchain.RunToolchainSuite), reflect.TypeOf(core.RunToolchainSuite), "the wrapper has the kernel function's signature")
		})
	})
}
