// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/facade. DO NOT EDIT.

// Package frontend re-exports [go.dokimi.dev/eidos/core/frontend]:
// one alias, constant or wrapper per exported symbol, so plugin
// code speaks the facade's paths while the kernel package stays
// the single home of every definition.
//
// # Dependency position
//
// sdk/frontend imports core/frontend, sdk/plugin and sdk/symbol.
package frontend

import (
	core "go.dokimi.dev/eidos/core/frontend"
	"go.dokimi.dev/eidos/sdk/plugin"
	"go.dokimi.dev/eidos/sdk/symbol"
)

// Classifier inspects a parsed unit and stamps classification
// facts through the unit's builder — a test-file marker, a foreign
// generator's output — at plugin authority under the frontend's
// identity. It runs after the author's parse, on the same unit, so
// what it inspects is what the parse declared; a returned error is
// fatal to the load the way a parse error is. There is no
// exclusion hook beside it: a classifier stamps what it saw and
// drops nothing, because whether a classified file takes part is
// the consumer's call.
type Classifier = core.Classifier

// Builder accumulates a frontend declaration: the identity and
// language every declaration carries, the comment syntax the
// parse strips through, the file claim, and the functions the
// pipeline varies in. Everything on it is data except the
// functions; Build freezes it, and a Builder is not reused
// afterwards.
type Builder = core.Builder

// New starts a frontend declaration for one language.
func New(name plugin.ID, lang symbol.Lang, syntax plugin.CommentSyntax) *Builder {
	return core.New(name, lang, syntax)
}
