// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/facade. DO NOT EDIT.

package frontend_test

import (
	"reflect"
	"testing"

	"go.dokimi.dev/assert"

	core "go.dokimi.dev/eidos/core/frontend"
	"go.dokimi.dev/eidos/sdk/frontend"
)

// The facade re-exports go.dokimi.dev/eidos/core/frontend: every type is the kernel's
// own type, every constant and variable equals the kernel's value,
// and every wrapper has the kernel function's signature.
func TestFacade(t *testing.T) {
	t.Parallel()

	t.Run("Classifier", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[frontend.Classifier](), reflect.TypeFor[core.Classifier](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Builder", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[frontend.Builder](), reflect.TypeFor[core.Builder](), "the facade aliases the kernel's type")
		})
	})

	t.Run("New", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(frontend.New), reflect.TypeOf(core.New), "the wrapper has the kernel function's signature")
		})
	})
}
