// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/facade. DO NOT EDIT.

// Package plugin re-exports [go.dokimi.dev/eidos/core/plugin]:
// one alias, constant or wrapper per exported symbol, so plugin
// code speaks the facade's paths while the kernel package stays
// the single home of every definition.
//
// # Dependency position
//
// sdk/plugin imports core/plugin, sdk/diag, sdk/directive,
// sdk/meta, sdk/store, sdk/symbol and the Go stdlib.
package plugin

import (
	"io/fs"

	core "go.dokimi.dev/eidos/core/plugin"
	"go.dokimi.dev/eidos/sdk/diag"
	"go.dokimi.dev/eidos/sdk/directive"
	"go.dokimi.dev/eidos/sdk/meta"
	"go.dokimi.dev/eidos/sdk/store"
	"go.dokimi.dev/eidos/sdk/symbol"
)

// Target names a rendering target. It is a registered name: the
// composition declares the targets it recognises, and a plan whose
// backend names anything else is a composition fault. The zero
// Target names nothing.
type Target = core.Target

// Backend renders one plan's emit. A plan holds exactly one, and
// its target must be a registered name; a composition that runs no
// renderer still validates both, so a plan is whole before
// anything arrives on disk.
type Backend = core.Backend

// Cardinality says how many outputs a family produces. The zero
// value addresses nothing: every declared family states its
// cardinality, and [Emit.Add] refuses a unit that does not.
type Cardinality = core.Cardinality

const (
	// PerSource is one output per source file.
	PerSource = core.PerSource
	// PerPackage is one output per package.
	PerPackage = core.PerPackage
	// PerPlan is one output per plan.
	PerPlan = core.PerPlan
)

// Output declares one file family a generator emits.
//
// The target spells the join and extension of Word at render, which
// is why neither appears here: one declaration serves store_stub.go
// and store.stub.ts alike.
type Output = core.Output

// Unit is one accumulated output entity: everything one plugin
// contributed to one (family, cardinality key) in one phase call.
// It carries the full routing key, so no consumer re-derives any
// part of it from the declarations.
type Unit = core.Unit

// Emit holds one plan's accumulated units, plus a per-kind index
// over their declarations that is maintained at [Emit.Add]: each
// unit's tree is walked once when it arrives, so an emit-triggered
// rule enumerates its matches rather than the emit graph.
//
// An Emit is not safe for concurrent use: annotators and generators
// run sequentially, and a unit arriving mid-enumeration would race
// the index it is being read from.
type Emit = core.Emit

// NewEmit returns an emit store holding nothing.
func NewEmit() *Emit {
	return core.NewEmit()
}

// Depth says how deep one unit loads.
//
// Signature-only loading is the same Parse observing
// [DepthSignatures] and skipping bodies and unexported members:
// one code path, so a dependency package cannot drift from the
// in-scope parse.
type Depth = core.Depth

const (
	// DepthFull loads everything the unit's source states.
	DepthFull = core.DepthFull
	// DepthSignatures loads the exported shape alone: no bodies,
	// no unexported members. The same bytes at the two depths
	// produce two graphs and key differently.
	DepthSignatures = core.DepthSignatures
)

// Frontend loads one language's source into the node graph. The
// kit lowers to this role and the exotic case implements it
// directly; either way the conformance suite holds both to the
// same checks.
type Frontend = core.Frontend

// SourceRef names a file without opening it: the
// workspace-relative path, and the shared inputs whose bytes fold
// into any dependent unit's fingerprint.
type SourceRef = core.SourceRef

// FileReader is the partition's recorded door: reads over the
// workspace tree, before units exist. It is not jailed to the
// selection, because a unit's shape can depend on a file the
// selection must not claim — a Go module file, a TypeScript config
// — and a partition that cannot look would guess; hermeticity holds
// because every read folds into every resulting unit's fingerprint
// instead. It is not the graph's
// [go.dokimi.dev/eidos/sdk/store.Reader], and the two never meet.
type FileReader = core.FileReader

// ImportScope is what the resolution phase hands a language's
// Resolve for one file: the file's assigned identity, and the
// bindings the frontend recorded at parse time through
// [GraphBuilder.Scope], in the language's own form. The kernel
// stores the bindings and hands them back to that language's
// Resolve alone, which type-asserts its own shape: Go binds
// package aliases, TypeScript binds members with rename and form,
// proto scopes per declaration site, and a kernel that fixed one
// shape would fix one language's.
type ImportScope = core.ImportScope

// Index is the dispatcher's routing surface over one frozen run:
// untracked, scope-filtered enumeration, plus the validated
// directive table and the skip table derived from it. Enumerating
// it records nothing, because dispatch is not a plugin's read; a
// plugin's own reads go through the [store.Reader] it is handed.
//
// Index wraps the graph rather than exposing it, and the wrapping
// is load-bearing twice over. Nothing reachable from a phase
// context can make a structural write, because the graph's write
// surface is not here; and nothing reachable can read another plugin's
// raw directives. What dispatch needs is exactly what is here.
//
// An Index is safe for concurrent reads: everything it holds is
// fixed at [NewIndex], and the graph beneath it is frozen.
type Index = core.Index

// NewIndex builds the routing surface for one run.
//
// It refuses a missing graph, a missing fact store and an unfrozen
// graph, because routing over any of those would return partial
// results. validated holds each subject's typed instances in
// position order, as validation returned them; the index keeps the
// map, and the caller does not mutate it after handing it over. A
// nil scope admits everything.
func NewIndex(g *store.Graph, f *meta.Facts, validated map[symbol.Identity][]directive.Directive, sc store.Scope) (*Index, error) {
	return core.NewIndex(g, f, validated, sc)
}

// ValidateOptions holds a plugin's options declaration to the tag
// contract: a pointer to a struct, exported fields only, an opt
// tag naming each field's config key, a doc tag stating its
// meaning, and no key claimed twice. It returns one error per
// finding, in field order, and nothing where the plugin declares
// no options. The composition runs it before populating; the
// conformance suite runs it as a check, so a plugin failing at
// composition fails in its own tests first.
func ValidateOptions(p Plugin) []error {
	return core.ValidateOptions(p)
}

// EncodeOptions returns a plugin's options in their canonical
// encoding, which is what a unit key and the composition
// fingerprint fold, and nil for a plugin declaring none. The
// encoding is encoding/json over the declared struct. It refuses a
// struct the encoding cannot see whole: an unexported field at any
// depth, a field its json tag hides, and a value the encoder
// refuses. A type that marshals itself is taken as it encodes.
// Every option is inside the encoding, so a changed option always
// changes the key.
func EncodeOptions(p Plugin) ([]byte, error) {
	return core.EncodeOptions(p)
}

// ID is a plugin's declared name: the one identity everywhere it
// appears. The diagnostic origin, the emit attribution and the
// arbitration rank's plugin field all carry this same type, so no
// boundary converts. It aliases [diag.Origin] rather than
// defining its own type because those envelopes live beneath the
// service provider interface, where this package cannot be
// imported; the definition sits at the bottom and this is its
// spelling wherever plugins are the subject.
type ID = core.ID

// Plugin is the base contract: a stable name.
//
// The name never changes between versions, because everything
// durable keys on it: findings, units, claims, config sections and
// the composition's roster.
type Plugin = core.Plugin

// Role names one phase role a plugin can hold.
//
// Priorities are per role: one shared number cannot place a
// dual-role plugin's annotator half and generator half
// independently, and the two phases' orderings have no reason to
// share integers. The zero Role names no role.
type Role = core.Role

const (
	// RoleAnnotator is the role that stamps facts over the frozen
	// graph.
	RoleAnnotator = core.RoleAnnotator
	// RoleGenerator is the role that produces emit values into one
	// plan.
	RoleGenerator = core.RoleGenerator
)

// Capability is a label one plugin provides and another requires.
//
// The provider exports it as a constant and requirers reference
// that constant, so a misspelled requirement is a compile error in
// a typed plugin and a collected fault only for what a manifest
// spelled. Capability topology orders execution inside one
// priority bucket.
type Capability = core.Capability

// DirectiveProvider declares the schemas a plugin owns, for
// registration at composition.
type DirectiveProvider = core.DirectiveProvider

// KeyProvider registers the plugin's metadata keys at composition.
// The call runs once per workspace, and the plugin keeps the typed
// handles it is returned: they are composition constants, the same
// class as a directive schema, not run state. It takes the
// registry rather than returning data because registration returns
// the handles back, which data cannot. Faults are collected by the
// caller, so the error names what failed rather than stopping the
// collection.
type KeyProvider = core.KeyProvider

// OutputProvider declares the file families a generator emits.
type OutputProvider = core.OutputProvider

// CapabilityProvider orders a plugin: a priority per role,
// plus the capability topology inside one priority bucket.
type CapabilityProvider = core.CapabilityProvider

// OptionsProvider declares a typed options struct: a pointer whose
// exported fields are the options, whose tags document them, and
// whose constructed values are the defaults. The composition
// populates it; the workspace folds it into the composition
// fingerprint a load keys units by.
type OptionsProvider = core.OptionsProvider

// Versioned declares a behavior version. Bump it with any change
// to what the plugin produces: a frontend's version folds into
// every unit key, and every version folds into the composition
// fingerprint, so a stale version serves stale cached work with
// nothing reporting why.
type Versioned = core.Versioned

// RenderedFile is one rendered output as a value: the derived
// filename and the finished bytes. Nothing here touches disk;
// paths, staging and commit belong to the sink that consumes it.
type RenderedFile = core.RenderedFile

// Renderer renders one plan's emit into files as values.
//
// A problem with one file attaches to the context's sink and the
// pass continues with the remaining files; a returned error is
// fatal to the pass. Two calls over one store return the same
// bytes, which the conformance suite holds every renderer to.
type Renderer = core.Renderer

// RenderContext carries what one render call may touch.
type RenderContext = core.RenderContext

// SyntaxProvider declares a target's comment forms: what the
// output contract writes a generated file's frame through, and
// what a frontend reading that file back recognizes it by. A
// backend implements it, and a composition staging output asks
// through it rather than restating the language's own spelling.
type SyntaxProvider = core.SyntaxProvider

// TemplateProvider declares a plugin's template trees: the bodies
// its references name, per target, and the helpers those templates
// call. Overrides names the shared vocabulary entries the plugin
// deliberately replaces, which is the replace verb: a shared name
// shadowed without a declaration is a lint finding, and where two
// plugins declare an override of one name, the latest schedule
// position wins, because a plugin that changes how a construct
// renders necessarily runs after what it changes.
type TemplateProvider = core.TemplateProvider

// Annotator stamps facts over the frozen graph.
//
// A problem with one subject attaches to the context's sink and the
// phase continues; a returned error is fatal to the phase. An
// annotator never adds or removes declarations, which the store
// enforces rather than this docblock: nothing reachable from the
// context can write to the graph.
type Annotator = core.Annotator

// Generator produces emit values into one plan.
//
// A problem with one subject attaches to the context's sink and the
// phase continues; a returned error is fatal to the phase. A
// generator is never seeing languages: it reads the graph through its
// context and emits neutral values into the plan's store.
type Generator = core.Generator

// AnnotatorContext carries what one Annotate call may touch.
//
// The two read surfaces split by rule: Index is the dispatcher's
// routing path and records nothing, and Reader is the plugin's
// tracked path, recording into the phase's read set. Plugin and
// Bucket are the arbitration rank fields every stamp made under
// this call carries.
type AnnotatorContext = core.AnnotatorContext

// GeneratorContext carries what one Generate call may touch. Its
// Index and Reader are scoped to the plan's sources, and Emit is
// the plan's store, where every accumulator flushes.
type GeneratorContext = core.GeneratorContext

// RefusedConstruct reports a lowering hook refusing a declaration:
// the target declares no idiom for the construct, and the
// declaration is withheld from render.
var RefusedConstruct = core.RefusedConstruct

// RefusedName reports a respell hook refusing a declared name: the
// target cannot spell it at its visibility, and the declaration is
// withheld from render, because rendering it under another access
// would misstate the declaration.
var RefusedName = core.RefusedName

// CollidingNames reports two declarations in one scope settling to
// one name: both keep their emitted names, references to either
// follow the emitted names, and the finding says what to fix.
var CollidingNames = core.CollidingNames

// AmbiguousReference reports a bare reference matching declarations
// whose settled names diverge: the reference stands as written.
var AmbiguousReference = core.AmbiguousReference

// VerbatimParams reports a verbatim body pinning its callable's
// parameter and result names: the body's text reads them as
// emitted, so the signature keeps them as emitted too, and one
// would have respelled differently.
var VerbatimParams = core.VerbatimParams

// Lower rewrites one declaration into the target's own construct
// shape: the same fact, the target's declarations. Every returned
// declaration carries the input's origin, and the output states
// the lowered fact in the target's shape rather than the model's,
// so a second settle changes nothing. An error is the target
// refusing the construct.
//
// A nil list without an error keeps the declaration as it stands,
// so the common pass-through spends no allocation; a hook that
// reshaped the declaration in place returns nil the same way,
// because the store already holds it.
type Lower = core.Lower

// Lowerer is the provider a backend implements when its target
// reshapes constructs. A backend without it renders declarations
// as emitted.
type Lowerer = core.Lowerer

// Respell spells one declared name in the target's own convention.
// Host is the kind of the declaration a member sits in,
// [symbol.KindInvalid] at file level; a kind without visibility
// passes the zero value. An error means the target cannot spell
// the name at that visibility.
type Respell = core.Respell

// Respeller is the provider a backend implements when its target
// respells declared names. A backend without it renders names as
// emitted.
type Respeller = core.Respeller

// Settle takes one plan's store through the backend's lowering
// seams, once, after the schedule and before the render: every
// declaration lowers into the target's construct shapes, every
// declared name respells into the target's convention, references
// follow their declarations, and the per-kind index rebuilds over
// what remains. The store is marked settled when it returns, and a
// settled store settles to itself, so a second call changes
// nothing.
//
// Findings attach to the sink under the backend's name: a refused
// construct or name withholds its declaration, colliding names
// keep their emitted spellings, and an ambiguous reference stands
// as written. A returned error is a defect in the backend's own
// hooks, a lowering that drops its input's origin, and fails the
// plan rather than one declaration.
func Settle(e *Emit, b Backend, sink *diag.Sink) error {
	return core.Settle(e, b, sink)
}

// RuleID is a rule's ordinal in its plugin's declaration order.
//
// It is stable exactly as long as the declaration is: reordering
// rules renumbers them. Anything durable keyed on one is
// invalidated by a reorder, which the conformance suite's
// declaration check makes visible.
type RuleID = core.RuleID

// Phase says when a subscription's rule runs. The zero Phase names
// no phase.
type Phase = core.Phase

const (
	// PhaseAnnotate runs over the frozen graph, stamping facts.
	PhaseAnnotate = core.PhaseAnnotate
	// PhaseGenerate runs over node subjects, within a plan.
	PhaseGenerate = core.PhaseGenerate
	// PhaseEmit runs over emit values earlier buckets produced in
	// the same plan.
	PhaseEmit = core.PhaseEmit
)

// Subscription is one gate tuple as data: what a rule watches,
// which is also what invalidation routes through. Ungated is the
// zero value throughout, so a bare rule's record carries only its
// rule, kind and phase.
type Subscription = core.Subscription

// Subscribed is a plugin that declares its gates, so the engine
// reads them as data without executing a handler.
//
// A hand-rolled plugin may skip it entirely, which reads as one
// implicit subscription to everything in scope: honest, and costs
// full-graph dispatch.
type Subscribed = core.Subscribed

// CommentSyntax is a language's comment forms, declared once per
// satellite and shared by the kits: the frontend strips comments
// with it, and the output contract writes the generated-file
// header through it.
type CommentSyntax = core.CommentSyntax

// CommentBlock is one block-comment form, gutter included, so a
// doc block's continuation lines strip and render the same way.
type CommentBlock = core.CommentBlock

// SourceUnit is one frontend compilation unit under parse: the only
// surface a Parse call touches. Bytes enter through Read alone,
// jailed to the unit's files and their declared shared inputs,
// and every accepted read folds into the unit's fingerprint, so a
// frontend cannot depend on bytes the cache does not know about.
type SourceUnit = core.SourceUnit

// NewSourceUnit assembles a unit for the load driver and the
// conformance suite: the member files, the tree reads resolve in,
// the depth, the language's comment syntax, and the sink findings
// report to under the frontend's origin.
func NewSourceUnit(files []SourceRef, fsys fs.FS, depth Depth, syntax CommentSyntax, sink *diag.Sink, origin diag.Origin) *SourceUnit {
	return core.NewSourceUnit(files, fsys, depth, syntax, sink, origin)
}

// CarrierMark opens a directive carrier line inside a comment: the
// kit's one cross-language convention, so a directive spells the
// same way whatever language carries it.
const CarrierMark = core.CarrierMark

// Carrier is one directive payload and the line it sits on, marker
// stripped, ready for the kernel grammar.
type Carrier = core.Carrier

// CommentParts is one raw comment taken apart three ways: the
// documentation lines, the carrier lines, and the tool-directive
// lines — the go:build kin — as annotations. What a language does
// with each part is its own: a frontend filters its configuration
// lines out of the annotations and its legacy forms out of the
// carriers before attaching anything.
type CommentParts = core.CommentParts

// GraphBuilder is the unit's write handle into the node model. A
// unit declares as many packages as its bytes do; two units
// contributing one package path merge at the splice, declarations
// appended in unit order. The splice validates what a unit built
// and panics on a structural defect — an emit-side symbol, a named
// kind without a name — because a malformed graph discovered at the
// resolution step points away from the frontend that built it.
type GraphBuilder = core.GraphBuilder

// ScopeRecord pairs one parsed file with its import bindings, in
// the language's own form. The file is the node the unit built,
// because canonical identities do not exist until the splice
// assigns them, and a derivation spelled twice would drift; the
// kernel derives the identity there and hands the bindings back to
// that language's Resolve alone.
type ScopeRecord = core.ScopeRecord

// Attachment is one raw directive instance on a declaration this
// unit built. The subject is a pointer for the reason
// [ScopeRecord]'s file is: the splice resolves it to the assigned
// identity, so an attachment on a declaration another unit already
// declared attaches to the identity that stands.
type Attachment = core.Attachment

// StampRecord is one classification stamp on a declaration this
// unit built: the second raw attachment class, resolved at the
// splice the way [Attachment] is. The stamp's origin is the
// kernel's to fill there — a frontend's own value is overwritten,
// so a stamp cannot speak for another plugin.
type StampRecord = core.StampRecord
