// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

// Code generated by internal/gen/facade. DO NOT EDIT.

package plugin_test

import (
	"reflect"
	"testing"

	"go.dokimi.dev/assert"

	core "go.dokimi.dev/eidos/core/plugin"
	"go.dokimi.dev/eidos/sdk/plugin"
)

// The facade re-exports go.dokimi.dev/eidos/core/plugin: every type is the kernel's
// own type, every constant and variable equals the kernel's value,
// and every wrapper has the kernel function's signature.
func TestFacade(t *testing.T) {
	t.Parallel()

	t.Run("Target", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Target](), reflect.TypeFor[core.Target](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Backend", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Backend](), reflect.TypeFor[core.Backend](), "the facade aliases the kernel's type")
		})
	})

	t.Run("ContinuedCarrier", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, plugin.ContinuedCarrier, core.ContinuedCarrier, "the facade re-declares the kernel's value")
		})
	})

	t.Run("Need", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Need](), reflect.TypeFor[core.Need](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Unplaced", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Unplaced](), reflect.TypeFor[core.Unplaced](), "the facade aliases the kernel's type")
		})
	})

	t.Run("DependencyRound", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.DependencyRound](), reflect.TypeFor[core.DependencyRound](), "the facade aliases the kernel's type")
		})
	})

	t.Run("StoreReader", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.StoreReader](), reflect.TypeFor[core.StoreReader](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Dependent", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Dependent](), reflect.TypeFor[core.Dependent](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Cardinality", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Cardinality](), reflect.TypeFor[core.Cardinality](), "the facade aliases the kernel's type")
		})
	})

	t.Run("PerSource", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, plugin.PerSource, core.PerSource, "the facade re-declares the kernel's value")
		})
	})

	t.Run("PerPackage", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, plugin.PerPackage, core.PerPackage, "the facade re-declares the kernel's value")
		})
	})

	t.Run("PerPlan", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, plugin.PerPlan, core.PerPlan, "the facade re-declares the kernel's value")
		})
	})

	t.Run("Output", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Output](), reflect.TypeFor[core.Output](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Unit", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Unit](), reflect.TypeFor[core.Unit](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Emit", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Emit](), reflect.TypeFor[core.Emit](), "the facade aliases the kernel's type")
		})
	})

	t.Run("NewEmit", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(plugin.NewEmit), reflect.TypeOf(core.NewEmit), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("ExportKey", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.ExportKey](), reflect.TypeFor[core.ExportKey](), "the facade aliases the kernel's type")
		})
	})

	t.Run("ExportedSymbol", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.ExportedSymbol](), reflect.TypeFor[core.ExportedSymbol](), "the facade aliases the kernel's type")
		})
	})

	t.Run("ExportDoc", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.ExportDoc](), reflect.TypeFor[core.ExportDoc](), "the facade aliases the kernel's type")
		})
	})

	t.Run("NewExport", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(plugin.NewExport), reflect.TypeOf(core.NewExport), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("File", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.File](), reflect.TypeFor[core.File](), "the facade aliases the kernel's type")
		})
	})

	t.Run("FileSpeller", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.FileSpeller](), reflect.TypeFor[core.FileSpeller](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Depth", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Depth](), reflect.TypeFor[core.Depth](), "the facade aliases the kernel's type")
		})
	})

	t.Run("DepthFull", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, plugin.DepthFull, core.DepthFull, "the facade re-declares the kernel's value")
		})
	})

	t.Run("DepthSignatures", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, plugin.DepthSignatures, core.DepthSignatures, "the facade re-declares the kernel's value")
		})
	})

	t.Run("Frontend", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Frontend](), reflect.TypeFor[core.Frontend](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Importer", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Importer](), reflect.TypeFor[core.Importer](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Exporter", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Exporter](), reflect.TypeFor[core.Exporter](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Candidates", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Candidates](), reflect.TypeFor[core.Candidates](), "the facade aliases the kernel's type")
		})
	})

	t.Run("SourceRef", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.SourceRef](), reflect.TypeFor[core.SourceRef](), "the facade aliases the kernel's type")
		})
	})

	t.Run("FileReader", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.FileReader](), reflect.TypeFor[core.FileReader](), "the facade aliases the kernel's type")
		})
	})

	t.Run("ImportScope", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.ImportScope](), reflect.TypeFor[core.ImportScope](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Validated", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Validated](), reflect.TypeFor[core.Validated](), "the facade aliases the kernel's type")
		})
	})

	t.Run("ValidatedMap", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.ValidatedMap](), reflect.TypeFor[core.ValidatedMap](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Index", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Index](), reflect.TypeFor[core.Index](), "the facade aliases the kernel's type")
		})
	})

	t.Run("NewIndex", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(plugin.NewIndex), reflect.TypeOf(core.NewIndex), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("WholeCall", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, plugin.WholeCall, core.WholeCall, "the facade re-declares the kernel's value")
		})
	})

	t.Run("UnitRef", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.UnitRef](), reflect.TypeFor[core.UnitRef](), "the facade aliases the kernel's type")
		})
	})

	t.Run("EmitRef", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.EmitRef](), reflect.TypeFor[core.EmitRef](), "the facade aliases the kernel's type")
		})
	})

	t.Run("MatchKey", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.MatchKey](), reflect.TypeFor[core.MatchKey](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Selection", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Selection](), reflect.TypeFor[core.Selection](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Invocation", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Invocation](), reflect.TypeFor[core.Invocation](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Journal", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Journal](), reflect.TypeFor[core.Journal](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Names", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Names](), reflect.TypeFor[core.Names](), "the facade aliases the kernel's type")
		})
	})

	t.Run("NameEntry", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.NameEntry](), reflect.TypeFor[core.NameEntry](), "the facade aliases the kernel's type")
		})
	})

	t.Run("NameKey", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.NameKey](), reflect.TypeFor[core.NameKey](), "the facade aliases the kernel's type")
		})
	})

	t.Run("NameRead", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.NameRead](), reflect.TypeFor[core.NameRead](), "the facade aliases the kernel's type")
		})
	})

	t.Run("FactRead", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.FactRead](), reflect.TypeFor[core.FactRead](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Settled", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Settled](), reflect.TypeFor[core.Settled](), "the facade aliases the kernel's type")
		})
	})

	t.Run("NamesOf", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(plugin.NamesOf), reflect.TypeOf(core.NamesOf), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("ValidateOptions", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(plugin.ValidateOptions), reflect.TypeOf(core.ValidateOptions), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("EncodeOptions", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(plugin.EncodeOptions), reflect.TypeOf(core.EncodeOptions), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("Module", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Module](), reflect.TypeFor[core.Module](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Resident", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Resident](), reflect.TypeFor[core.Resident](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Placement", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Placement](), reflect.TypeFor[core.Placement](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Packager", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Packager](), reflect.TypeFor[core.Packager](), "the facade aliases the kernel's type")
		})
	})

	t.Run("PackageRule", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.PackageRule](), reflect.TypeFor[core.PackageRule](), "the facade aliases the kernel's type")
		})
	})

	t.Run("ID", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.ID](), reflect.TypeFor[core.ID](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Plugin", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Plugin](), reflect.TypeFor[core.Plugin](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Role", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Role](), reflect.TypeFor[core.Role](), "the facade aliases the kernel's type")
		})
	})

	t.Run("RoleAnnotator", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, plugin.RoleAnnotator, core.RoleAnnotator, "the facade re-declares the kernel's value")
		})
	})

	t.Run("RoleGenerator", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, plugin.RoleGenerator, core.RoleGenerator, "the facade re-declares the kernel's value")
		})
	})

	t.Run("Capability", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Capability](), reflect.TypeFor[core.Capability](), "the facade aliases the kernel's type")
		})
	})

	t.Run("DirectiveProvider", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.DirectiveProvider](), reflect.TypeFor[core.DirectiveProvider](), "the facade aliases the kernel's type")
		})
	})

	t.Run("KeyProvider", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.KeyProvider](), reflect.TypeFor[core.KeyProvider](), "the facade aliases the kernel's type")
		})
	})

	t.Run("OutputProvider", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.OutputProvider](), reflect.TypeFor[core.OutputProvider](), "the facade aliases the kernel's type")
		})
	})

	t.Run("CapabilityProvider", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.CapabilityProvider](), reflect.TypeFor[core.CapabilityProvider](), "the facade aliases the kernel's type")
		})
	})

	t.Run("OptionsProvider", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.OptionsProvider](), reflect.TypeFor[core.OptionsProvider](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Versioned", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Versioned](), reflect.TypeFor[core.Versioned](), "the facade aliases the kernel's type")
		})
	})

	t.Run("RenderedFile", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.RenderedFile](), reflect.TypeFor[core.RenderedFile](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Renderer", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Renderer](), reflect.TypeFor[core.Renderer](), "the facade aliases the kernel's type")
		})
	})

	t.Run("RenderContext", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.RenderContext](), reflect.TypeFor[core.RenderContext](), "the facade aliases the kernel's type")
		})
	})

	t.Run("SyntaxProvider", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.SyntaxProvider](), reflect.TypeFor[core.SyntaxProvider](), "the facade aliases the kernel's type")
		})
	})

	t.Run("TemplateProvider", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.TemplateProvider](), reflect.TypeFor[core.TemplateProvider](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Annotator", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Annotator](), reflect.TypeFor[core.Annotator](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Generator", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Generator](), reflect.TypeFor[core.Generator](), "the facade aliases the kernel's type")
		})
	})

	t.Run("WorkspaceCheck", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.WorkspaceCheck](), reflect.TypeFor[core.WorkspaceCheck](), "the facade aliases the kernel's type")
		})
	})

	t.Run("AnnotatorContext", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.AnnotatorContext](), reflect.TypeFor[core.AnnotatorContext](), "the facade aliases the kernel's type")
		})
	})

	t.Run("GeneratorContext", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.GeneratorContext](), reflect.TypeFor[core.GeneratorContext](), "the facade aliases the kernel's type")
		})
	})

	t.Run("PlanRecord", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.PlanRecord](), reflect.TypeFor[core.PlanRecord](), "the facade aliases the kernel's type")
		})
	})

	t.Run("CheckContext", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.CheckContext](), reflect.TypeFor[core.CheckContext](), "the facade aliases the kernel's type")
		})
	})

	t.Run("RefusedConstruct", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, plugin.RefusedConstruct, core.RefusedConstruct, "the facade re-declares the kernel's value")
		})
	})

	t.Run("RefusedName", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, plugin.RefusedName, core.RefusedName, "the facade re-declares the kernel's value")
		})
	})

	t.Run("CollidingNames", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, plugin.CollidingNames, core.CollidingNames, "the facade re-declares the kernel's value")
		})
	})

	t.Run("AmbiguousReference", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, plugin.AmbiguousReference, core.AmbiguousReference, "the facade re-declares the kernel's value")
		})
	})

	t.Run("VerbatimParams", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, plugin.VerbatimParams, core.VerbatimParams, "the facade re-declares the kernel's value")
		})
	})

	t.Run("Lower", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Lower](), reflect.TypeFor[core.Lower](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Lowerer", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Lowerer](), reflect.TypeFor[core.Lowerer](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Respell", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Respell](), reflect.TypeFor[core.Respell](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Respeller", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Respeller](), reflect.TypeFor[core.Respeller](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Settle", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(plugin.Settle), reflect.TypeOf(core.Settle), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("SettleWith", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(plugin.SettleWith), reflect.TypeOf(core.SettleWith), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("ErrStoreAbsent", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, plugin.ErrStoreAbsent, core.ErrStoreAbsent, "the facade re-declares the kernel's value")
		})
	})

	t.Run("StorePath", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(plugin.StorePath), reflect.TypeOf(core.StorePath), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("CutStorePath", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(plugin.CutStorePath), reflect.TypeOf(core.CutStorePath), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("ValidStoreName", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(plugin.ValidStoreName), reflect.TypeOf(core.ValidStoreName), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("StoreFS", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.StoreFS](), reflect.TypeFor[core.StoreFS](), "the facade aliases the kernel's type")
		})
	})

	t.Run("StoreLocator", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.StoreLocator](), reflect.TypeFor[core.StoreLocator](), "the facade aliases the kernel's type")
		})
	})

	t.Run("ReadFile", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(plugin.ReadFile), reflect.TypeOf(core.ReadFile), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("ReadDir", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(plugin.ReadDir), reflect.TypeOf(core.ReadDir), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("Stat", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(plugin.Stat), reflect.TypeOf(core.Stat), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("RuleID", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.RuleID](), reflect.TypeFor[core.RuleID](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Phase", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Phase](), reflect.TypeFor[core.Phase](), "the facade aliases the kernel's type")
		})
	})

	t.Run("PhaseAnnotate", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, plugin.PhaseAnnotate, core.PhaseAnnotate, "the facade re-declares the kernel's value")
		})
	})

	t.Run("PhaseGenerate", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, plugin.PhaseGenerate, core.PhaseGenerate, "the facade re-declares the kernel's value")
		})
	})

	t.Run("PhaseEmit", func(t *testing.T) {
		t.Parallel()

		t.Run("equals the kernel's value", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, plugin.PhaseEmit, core.PhaseEmit, "the facade re-declares the kernel's value")
		})
	})

	t.Run("Subscription", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Subscription](), reflect.TypeFor[core.Subscription](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Subscribed", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Subscribed](), reflect.TypeFor[core.Subscribed](), "the facade aliases the kernel's type")
		})
	})

	t.Run("CommentSyntax", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.CommentSyntax](), reflect.TypeFor[core.CommentSyntax](), "the facade aliases the kernel's type")
		})
	})

	t.Run("CommentBlock", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.CommentBlock](), reflect.TypeFor[core.CommentBlock](), "the facade aliases the kernel's type")
		})
	})

	t.Run("SourceUnit", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.SourceUnit](), reflect.TypeFor[core.SourceUnit](), "the facade aliases the kernel's type")
		})
	})

	t.Run("NewSourceUnit", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(plugin.NewSourceUnit), reflect.TypeOf(core.NewSourceUnit), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("Carrier", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Carrier](), reflect.TypeFor[core.Carrier](), "the facade aliases the kernel's type")
		})
	})

	t.Run("CommentParts", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.CommentParts](), reflect.TypeFor[core.CommentParts](), "the facade aliases the kernel's type")
		})
	})

	t.Run("CutCarrier", func(t *testing.T) {
		t.Parallel()

		t.Run("has the kernel function's signature", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeOf(plugin.CutCarrier), reflect.TypeOf(core.CutCarrier), "the wrapper has the kernel function's signature")
		})
	})

	t.Run("GraphBuilder", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.GraphBuilder](), reflect.TypeFor[core.GraphBuilder](), "the facade aliases the kernel's type")
		})
	})

	t.Run("ScopeRecord", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.ScopeRecord](), reflect.TypeFor[core.ScopeRecord](), "the facade aliases the kernel's type")
		})
	})

	t.Run("Attachment", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.Attachment](), reflect.TypeFor[core.Attachment](), "the facade aliases the kernel's type")
		})
	})

	t.Run("StampRecord", func(t *testing.T) {
		t.Parallel()

		t.Run("is the kernel's type", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, reflect.TypeFor[plugin.StampRecord](), reflect.TypeFor[core.StampRecord](), "the facade aliases the kernel's type")
		})
	})
}
