// Copyright ThesmOS B.V. 2026
// SPDX-License-Identifier: Apache-2.0

package output_test

import (
	"bytes"
	"slices"
	"strconv"
	"strings"
	"testing"

	"go.dokimi.dev/assert"

	"go.dokimi.dev/eidos/core/output"
	"go.dokimi.dev/eidos/core/plugin"
)

// goSyntax is the comment spelling of a line-commented language.
func goSyntax() plugin.CommentSyntax {
	return plugin.CommentSyntax{
		Line:   []string{"//"},
		Blocks: []plugin.CommentBlock{{Open: "/*", Close: "*/"}},
	}
}

// blockSyntax is a language with block comments and nothing else.
func blockSyntax() plugin.CommentSyntax {
	return plugin.CommentSyntax{
		Blocks: []plugin.CommentBlock{{Open: "<!--", Close: "-->"}},
	}
}

// bodyText is the fixture body, blank line included: the frame's
// boundary is its own first blank line, never the body's.
const bodyText = "package svc\n\nfunc Load() {}\n"

// hexDigest is sha256 of bodyText in hex, computed outside this
// package, so the test pins the bytes rather than mirroring the
// code. A malformed-frame case reuses it wherever the trailer has
// to carry a well-formed digest for the parse to reach the line
// under test.
const hexDigest = "614193ef93d47f9a586ce9d422874980fd6690fcb657630610e96233cc5cd1dd"

// bodyHash is the trailer's claim over bodyText.
const bodyHash = "sha256:" + hexDigest

// stamped is the frame the fixture file produces, in full.
const stamped = "// Code generated by acme. DO NOT EDIT.\n" +
	"// acme:plugin acme-audit\n" +
	"// acme:plugin stubgen\n" +
	"// acme:source svc/store.go\n" +
	"\n" +
	bodyText +
	"// acme:provenance " + bodyHash + "\n"

// fixtureFile returns the rendered file the frame is built over.
func fixtureFile() plugin.RenderedFile {
	return plugin.RenderedFile{
		Name:    "store_stub.go",
		Plugins: []plugin.ID{"stubgen", "acme-audit"},
		Sources: []string{"svc/store.go"},
		Body:    []byte(bodyText),
	}
}

// contract composes the fixture contract, failing the test where
// the composition refuses.
func contract(tb assert.TB, b output.Brand, s plugin.CommentSyntax) *output.Contract {
	tb.Helper()

	c, err := output.NewContract(b, s)
	assert.NoError(tb, err, "the fixture contract composes")
	return c
}

// The contract is what makes a generated file provable from its
// own bytes: a marker the ecosystem recognises, the derivation
// that attributes it, and a trailer that proves ownership and
// integrity with no state anywhere else.
func TestContract(t *testing.T) {
	t.Parallel()

	t.Run("NewContract", func(t *testing.T) {
		t.Parallel()

		t.Run("refuses a brand outside the charset", func(t *testing.T) {
			t.Parallel()

			for _, b := range []output.Brand{
				"", "Acme", "acme gen", "acme.gen", "acme_gen", "acme/gen", "acme:gen",
			} {
				_, err := output.NewContract(b, goSyntax())
				assert.HasError(t, err,
					"a brand outside lowercase, digits and hyphens is refused: "+string(b))
			}
		})

		t.Run("composes a brand inside the charset", func(t *testing.T) {
			t.Parallel()

			for _, b := range []output.Brand{"acme", "acme-gen", "gen2"} {
				_, err := output.NewContract(b, goSyntax())
				assert.NoError(t, err, "a valid brand composes: "+string(b))
			}
		})

		t.Run("refuses a syntax carrying no comment form", func(t *testing.T) {
			t.Parallel()

			_, err := output.NewContract("acme", plugin.CommentSyntax{})
			assert.HasError(t, err,
				"a language without comments cannot carry the frame")
		})

		t.Run("takes the block form where no line form exists", func(t *testing.T) {
			t.Parallel()

			c := contract(t, "acme", blockSyntax())
			out, err := c.Stamp(fixtureFile())
			assert.NoError(t, err, "the block language stamps")
			assert.HasPrefix(t, string(out),
				"<!-- Code generated by acme. DO NOT EDIT. -->\n",
				"each frame line wraps in the first block form")
			assert.HasSuffix(t, string(out),
				"<!-- acme:provenance "+bodyHash+" -->\n",
				"the trailer included")
		})
	})

	t.Run("Brand", func(t *testing.T) {
		t.Parallel()

		t.Run("returns the name the contract stamps under", func(t *testing.T) {
			t.Parallel()

			assert.Equal(t, contract(t, "acme-gen", goSyntax()).Brand(),
				output.Brand("acme-gen"),
				"a consumer holding a contract reads its ownership claim off it, "+
					"rather than carrying the brand beside it")
		})
	})

	t.Run("Stamp", func(t *testing.T) {
		t.Parallel()

		t.Run("frames the file", func(t *testing.T) {
			t.Parallel()

			c := contract(t, "acme", goSyntax())
			out, err := c.Stamp(fixtureFile())
			assert.NoError(t, err, "the fixture stamps")
			assert.Equal(t, string(out), stamped,
				"marker, derivation sorted, blank line, body, trailer")
		})

		t.Run("returns the same bytes twice", func(t *testing.T) {
			t.Parallel()

			c := contract(t, "acme", goSyntax())
			first, err := c.Stamp(fixtureFile())
			assert.NoError(t, err, "the first stamp")
			second, err := c.Stamp(fixtureFile())
			assert.NoError(t, err, "the second stamp")
			assert.Equal(t, string(second), string(first),
				"the stamp carries no clock and no counter")
		})

		t.Run("dedupes and sorts the derivation", func(t *testing.T) {
			t.Parallel()

			c := contract(t, "acme", goSyntax())
			f := fixtureFile()
			f.Plugins = []plugin.ID{"stubgen", "acme-audit", "stubgen"}
			f.Sources = []string{"svc/store.go", "svc/store.go"}
			out, err := c.Stamp(f)
			assert.NoError(t, err, "the unsorted fixture stamps")
			assert.Equal(t, string(out), stamped,
				"the frame is deterministic whatever order the renderer used")
		})

		t.Run("a file deriving from nothing carries no derivation", func(t *testing.T) {
			t.Parallel()

			c := contract(t, "acme", goSyntax())
			out, err := c.Stamp(plugin.RenderedFile{
				Name: "registry.go", Body: []byte("package svc\n"),
			})
			assert.NoError(t, err, "a plan file stamps")
			assert.Equal(t, string(out),
				"// Code generated by acme. DO NOT EDIT.\n"+
					"\n"+
					"package svc\n"+
					"// acme:provenance sha256:"+
					"29fe8614d6d9cb93b43663f869d741c2da0a14c530532c2cd9b6f19f31c3dec6\n",
				"the marker and the trailer alone")
		})

		t.Run("refuses what would break the frame", func(t *testing.T) {
			t.Parallel()

			c := contract(t, "acme", goSyntax())
			tests := []struct {
				name string
				file plugin.RenderedFile
				why  string
			}{
				{
					name: "a body not ending in a newline",
					file: plugin.RenderedFile{Body: []byte("package svc")},
					why:  "the trailer would weld onto the body's last line",
				},
				{
					name: "an empty body",
					file: plugin.RenderedFile{},
					why:  "an empty body ends in no newline either",
				},
				{
					name: "a body carrying a carriage return",
					file: plugin.RenderedFile{Body: []byte("package svc\r\n")},
					why:  "the text policy is LF, and the formatter is where CRLF is fixed",
				},
				{
					name: "a plugin name carrying a line break",
					file: plugin.RenderedFile{
						Plugins: []plugin.ID{"stub\ngen"}, Body: []byte("package svc\n"),
					},
					why: "a derivation line is one line",
				},
				{
					name: "a source carrying a line break",
					file: plugin.RenderedFile{
						Sources: []string{"svc\n/store.go"}, Body: []byte("package svc\n"),
					},
					why: "a derivation line is one line",
				},
				{
					name: "an empty plugin name",
					file: plugin.RenderedFile{
						Plugins: []plugin.ID{""}, Body: []byte("package svc\n"),
					},
					why: "a nameless emitter attributes nothing",
				},
			}
			for _, tt := range tests {
				t.Run(tt.name, func(t *testing.T) {
					t.Parallel()
					_, err := c.Stamp(tt.file)
					assert.HasError(t, err, tt.why)
				})
			}
		})
	})

	t.Run("Read", func(t *testing.T) {
		t.Parallel()

		t.Run("reads a frame under any brand", func(t *testing.T) {
			t.Parallel()

			p, held := output.Read([]byte(stamped))
			assert.True(t, held, "the frame parses without a contract")
			assert.Equal(t, p.Brand, output.Brand("acme"), "the brand it claims")
			assert.Equal(t, p.Plugins, []plugin.ID{"acme-audit", "stubgen"},
				"every plugin line")
			assert.Equal(t, p.Sources, []string{"svc/store.go"}, "every source line")
			assert.Equal(t, p.Hash, bodyHash, "and the hash it attests")
		})

		t.Run("reads a block-commented frame", func(t *testing.T) {
			t.Parallel()

			c := contract(t, "acme", blockSyntax())
			out, err := c.Stamp(fixtureFile())
			assert.NoError(t, err, "the block language stamps")
			p, held := output.Read(out)
			assert.True(t, held, "the block frame parses")
			assert.Equal(t, p.Sources, []string{"svc/store.go"},
				"the derivation reads through the block form")
		})

		t.Run("returns nothing for a file carrying no frame", func(t *testing.T) {
			t.Parallel()

			for _, src := range []string{
				"",
				"package svc\n",
				"// Code generated by acme. DO NOT EDIT.\n\npackage svc\n",
			} {
				_, held := output.Read([]byte(src))
				assert.False(t, held, "a file without a trailer carries no record")
			}
		})

		t.Run("skips a key it does not know", func(t *testing.T) {
			t.Parallel()

			grown := strings.Replace(stamped,
				"// acme:source svc/store.go\n",
				"// acme:source svc/store.go\n// acme:plan go-services\n", 1)
			p, held := output.Read([]byte(grown))
			assert.True(t, held, "an unknown key does not break the parse")
			assert.Equal(t, p.Sources, []string{"svc/store.go"},
				"and the keys it knows read unchanged")
		})

		t.Run("refuses a frame it cannot read whole", func(t *testing.T) {
			t.Parallel()

			tests := []struct {
				name    string
				stamped string
				why     string
			}{
				{
					name:    "a trailer naming no brand",
					stamped: "package svc\n:provenance " + bodyHash + "\n",
					why:     "the brand reads backwards from the digest key, and there is none",
				},
				{
					name:    "a digest cut short",
					stamped: "package svc\n// acme:provenance sha256:614193ef\n",
					why:     "a digest narrower than sha256 attests nothing",
				},
				{
					name: "a digest outside hex",
					stamped: "package svc\n// acme:provenance sha256:" +
						strings.Repeat("z", len(hexDigest)) + "\n",
					why: "the trailer's claim is a hex digest, whatever its width",
				},
				{
					name:    "a marker line the brand did not write",
					stamped: "package svc\n// acme:provenance " + bodyHash + "\n",
					why:     "the frame opens with the marker, and this file opens with code",
				},
				{
					name: "a frame with no blank line to end it",
					stamped: "// Code generated by acme. DO NOT EDIT.\n" +
						"// acme:provenance " + bodyHash + "\n",
					why: "the blank line is what separates the derivation from the body",
				},
				{
					name: "a derivation line outside the comment form",
					stamped: "// Code generated by acme. DO NOT EDIT.\n" +
						"plain text\n\n" + bodyText +
						"// acme:provenance " + bodyHash + "\n",
					why: "every frame line is spelled through the language's comment form",
				},
				{
					name: "a derivation line under another brand",
					stamped: "// Code generated by acme. DO NOT EDIT.\n" +
						"// rival:plugin stubgen\n\n" + bodyText +
						"// acme:provenance " + bodyHash + "\n",
					why: "one frame carries one brand, so a foreign key is not a skipped key",
				},
				{
					name: "a block-form line missing its closer",
					stamped: "<!-- Code generated by acme. DO NOT EDIT. -->\n" +
						"<!-- acme:plugin stubgen\n\n" + bodyText +
						"<!-- acme:provenance " + bodyHash + " -->\n",
					why: "an unclosed comment would swallow the body it precedes",
				},
			}
			for _, tt := range tests {
				t.Run(tt.name, func(t *testing.T) {
					t.Parallel()

					_, held := output.Read([]byte(tt.stamped))
					assert.False(t, held, tt.why)
				})
			}
		})
	})

	t.Run("Verify", func(t *testing.T) {
		t.Parallel()

		t.Run("accepts what Stamp produced", func(t *testing.T) {
			t.Parallel()

			c := contract(t, "acme", goSyntax())
			out, err := c.Stamp(fixtureFile())
			assert.NoError(t, err, "the fixture stamps")
			p, err := c.Verify(out)
			assert.NoError(t, err, "and verifies whole")
			assert.Equal(t, p.Plugins, []plugin.ID{"acme-audit", "stubgen"},
				"returning the derivation it verified")
		})

		t.Run("refuses what broke", func(t *testing.T) {
			t.Parallel()

			c := contract(t, "acme", goSyntax())
			tests := []struct {
				name    string
				stamped string
				why     string
			}{
				{
					name:    "a file carrying no frame",
					stamped: "package svc\n",
					why:     "a hand-written file proves nothing",
				},
				{
					name:    "another brand's file",
					stamped: strings.ReplaceAll(stamped, "acme", "rival"),
					why:     "ownership is brand-keyed, so another tool's file is not ours",
				},
				{
					name:    "a body edited after stamping",
					stamped: strings.Replace(stamped, "func Load() {}", "func Load() { x() }", 1),
					why:     "the hash no longer matches the body",
				},
				{
					name:    "bytes appended after the trailer",
					stamped: stamped + "func Extra() {}\n",
					why:     "the trailer is the file's final line",
				},
				{
					name:    "a blank line appended after the trailer",
					stamped: stamped + "\n",
					why:     "anything after the trailer counts, blank or not",
				},
			}
			for _, tt := range tests {
				t.Run(tt.name, func(t *testing.T) {
					t.Parallel()
					_, err := c.Verify([]byte(tt.stamped))
					assert.HasError(t, err, tt.why)
				})
			}
		})
	})
}

// FuzzParse holds the frame's round trip over arbitrary derivation
// and body bytes: what [output.Contract.Stamp] writes,
// [output.Read] reads back exactly, [output.Contract.Verify]
// accepts, and a body edited by one byte afterwards it refuses.
// Reading is the half with no schema to lean on — the trailer names
// the brand and the comment form — so the property is stated
// against what stamping produced rather than against a hand-written
// expectation.
//
// Truncation is deliberately not a property here. A body that ends
// in a well-formed trailer of its own makes the prefix up to that
// line a whole frame, which verifies as the file it is.
func FuzzParse(f *testing.F) {
	f.Add("acme", "stubgen", "svc/store.go", bodyText, 0)
	f.Add("acme", "acme-audit", "svc/store.go", "package svc\n", 7)
	f.Add("gen2", "x", "y", "\n", 1)
	f.Add("acme", "// acme:plugin stubgen", "// acme:provenance "+bodyHash,
		stamped, 3)
	// A stamped file nested in a body: the frame meets its own
	// grammar twice over.
	f.Add("acme", "stubgen", "svc/store.go",
		bodyText+"// acme:provenance "+bodyHash+"\n", 11)

	f.Fuzz(func(t *testing.T, brand, plug, src, body string, at int) {
		c, err := output.NewContract(output.Brand(brand), goSyntax())
		if err != nil {
			return // a brand outside the charset frames nothing
		}
		out, err := c.Stamp(plugin.RenderedFile{
			Plugins: []plugin.ID{plugin.ID(plug)},
			Sources: []string{src},
			Body:    []byte(body),
		})
		if err != nil {
			return // what no line can carry never reaches the parse
		}

		got, held := output.Read(out)
		assert.True(t, held, "every stamped file carries a frame Read finds")
		assert.Equal(t, got.Brand, output.Brand(brand),
			"the trailer names the brand that stamped it")
		assert.Equal(t, got.Plugins, []plugin.ID{plugin.ID(plug)},
			"and the derivation reads back as written")
		assert.Equal(t, got.Sources, []string{src}, "both halves of it")
		verified, err := c.Verify(out)
		assert.NoError(t, err, "the contract accepts what it stamped")
		assert.Equal(t, verified, got, "and reads the same record Read did")

		edited := slices.Clone(out)
		// The body's last occurrence is the body itself or the
		// trailer that attests it; either edit is one the trailer
		// stops claiming.
		edited[bytes.LastIndex(out, []byte(body))+index(at, len(body))] ^= 0x20
		_, err = c.Verify(edited)
		assert.HasError(t, err,
			"a body edited after stamping no longer hashes to what the trailer claims")
	})
}

// index folds an arbitrary fuzz integer into an offset inside a
// slice of that width.
func index(at, width int) int {
	at %= width
	if at < 0 {
		at += width
	}
	return at
}

// benchFiles returns n rendered files of a realistic size: a
// two-kilobyte body, two emitters and one source each.
func benchFiles(n int) []plugin.RenderedFile {
	body := append(bytes.Repeat([]byte("\tcall()\n"), 250), '\n')
	files := make([]plugin.RenderedFile, 0, n)
	for i := range n {
		at := "svc/pkg" + strconv.Itoa(i) + "/store.go"
		files = append(files, plugin.RenderedFile{
			Name:    "store_stub.go",
			Plugins: []plugin.ID{"stubgen", "acme-audit"},
			Sources: []string{at},
			Body:    body,
		})
	}
	return files
}

// BenchmarkStamp measures the frame at the canonical file count:
// 1000 files of two kilobytes, which is one sha256 pass over two
// megabytes plus the frame's own bytes. The digest is the floor
// and the rest is one buffer per file.
func BenchmarkStamp(b *testing.B) {
	b.ReportAllocs()

	c, err := output.NewContract("acme", goSyntax())
	if err != nil {
		b.Fatalf("NewContract: unexpected error: %v", err)
	}
	files := benchFiles(1_000)
	b.ResetTimer()
	for b.Loop() {
		for _, f := range files {
			if _, err := c.Stamp(f); err != nil {
				b.Fatalf("Stamp: unexpected error: %v", err)
			}
		}
	}
}
